import type { Question } from '../../types'
import { mkFactory, SRC } from './helpers'

const q = mkFactory({ category: 'grammatik', source: SRC.lexgram, idPrefix: 'gr' })

export const GRAMMAR_QUESTIONS: Question[] = [
  // ---------- Verben mit Präpositionen ----------
  q.mc('vp1', 'verben-praepositionen', 1, 'Ich freue mich schon ___ die Sommerferien.', ['auf', 'über', 'für', 'an'], 0,
    'sich freuen **auf** + Akk = cieszyć się na coś, co dopiero będzie. „über” = z czegoś, co już jest.', { tags: ['freuen-auf'] }),
  q.mc('vp2', 'verben-praepositionen', 2, 'Vielen Dank! Ich freue mich sehr ___ dein Geschenk.', ['über', 'auf', 'für', 'mit'], 0,
    'Prezent już dostałem → sich freuen **über** + Akk.', { tags: ['freuen-ueber'] }),
  q.mc('vp3', 'verben-praepositionen', 1, 'Entschuldigung, ich habe eine Frage. Er fragt ___ dem Weg zum Museum.', ['nach', 'über', 'um', 'von'], 0,
    'fragen **nach** + Dativ (pytać o coś/o drogę).', { tags: ['fragen-nach'] }),
  q.mc('vp4', 'verben-praepositionen', 2, 'Ob wir morgen wandern gehen, hängt ___ Wetter ab.', ['vom', 'von das', 'auf das', 'am'], 0,
    'abhängen **von** + Dativ → von dem = **vom** Wetter.', { tags: ['abhaengen-von'] }),
  q.mc('vp5', 'verben-praepositionen', 2, 'Darf ich Sie ___ einen kleinen Gefallen bitten?', ['um', 'für', 'nach', 'auf'], 0,
    'bitten **um** + Akk (prosić o coś).', { tags: ['bitten-um'] }),
  q.mc('vp6', 'verben-praepositionen', 2, 'Unsere Klasse nimmt dieses Jahr ___ Wettbewerb teil.', ['am', 'an den', 'beim', 'zum'], 0,
    'teilnehmen **an + Dativ**: an dem = **am** Wettbewerb.', { tags: ['teilnehmen-an'] }),
  q.mc('vp7', 'verben-praepositionen', 1, 'Meine Schwester interessiert sich sehr ___ Astronomie.', ['für', 'an', 'über', 'mit'], 0,
    'sich interessieren **für** + Akk.', { tags: ['interessieren-fuer'] }),
  q.mc('vp8', 'verben-praepositionen', 2, 'Kannst du dich noch ___ unseren ersten Schultag erinnern?', ['an', 'auf', 'über', 'von'], 0,
    'sich erinnern **an** + Akk.', { tags: ['erinnern-an'] }),
  q.mc('vp9', 'verben-praepositionen', 2, 'Wer kümmert sich ___ den Hund, wenn ihr im Urlaub seid?', ['um', 'für', 'über', 'mit'], 0,
    'sich kümmern **um** + Akk (troszczyć się o).', { tags: ['kuemmern-um'] }),
  q.mc('vp10', 'verben-praepositionen', 3, 'Viele Touristen ärgern sich ___ die langen Schlangen vor Schloss Neuschwanstein.', ['über', 'auf', 'an', 'vor'], 0,
    'sich ärgern **über** + Akk (złościć się na coś/z powodu).', { tags: ['aergern-ueber'] }),
  q.input('vp11', 'verben-praepositionen', 2, 'Ich warte schon seit einer Stunde ___ den Bus. (1 słowo)', ['auf'],
    'warten **auf** + Akk.', { tags: ['warten-auf'] }),
  q.input('vp12', 'verben-praepositionen', 3, 'Hast du keine Angst ___ der Prüfung? (1 słowo)', ['vor'],
    'Angst haben **vor** + Dativ (bać się czegoś).', { tags: ['angst-vor'] }),
  q.gap('vp13', 'verben-praepositionen', 3,
    'Ich habe mich schon {0} das kalte Wetter gewöhnt. Meine Mutter träumt {1} einem Haus am Meer. Er beschäftigt sich gern {2} Geschichte.',
    [['an'], ['von'], ['mit']],
    'sich gewöhnen **an** + Akk; träumen **von** + Dat; sich beschäftigen **mit** + Dat.', { tags: ['gewoehnen-an', 'traeumen-von'] }),
  q.gap('vp14', 'verben-praepositionen', 3,
    'Wir haben lange {0} den Ausflug gesprochen. Ich bedanke mich {1} dir für die Hilfe.',
    [['über'], ['bei']],
    'sprechen **über** + Akk (o czymś); sich bedanken **bei** jemandem **für** etwas.', { tags: ['bedanken-bei'] }),
  q.input('vp15', 'verben-praepositionen', 3, 'Wir müssen noch ___ die Bibliothek suchen. Wo ist sie nur? (przyimek + rodzajnik)', ['nach der'],
    'suchen **nach** + Dativ; die Bibliothek (f) → nach **der** Bibliothek.', { tags: ['suchen-nach'], stage: ['rejonowy', 'wojewodzki'] }),

  // ---------- Präpositionaladverbien / Fragewörter ----------
  q.mc('pa1', 'praepositionaladverbien', 1, '___ wartest du? — Auf die Antwort von meinem Lehrer.', ['Worauf', 'Wofür', 'Wonach', 'Worüber'], 0,
    'Odpowiedź „Auf ...” → pytanie **Worauf**. Ten sam przyimek w pytaniu i odpowiedzi.', { tags: ['wo-plus'] }),
  q.mc('pa2', 'praepositionaladverbien', 2, '___ Jacke liegt hier auf dem Stuhl? — Das ist die Jacke von Julia.', ['Wessen', 'Wem', 'Welcher', 'Wen'], 0,
    'Pytanie o właściciela = **Wessen** (Genitiv, „czyja”).', { tags: ['wessen'] }),
  q.mc('pa3', 'praepositionaladverbien', 2, '___ denkst du gerade? — An meine Oma in Wien.', ['An wen', 'Woran', 'Worauf', 'Wem'], 0,
    'Chodzi o **osobę** → przyimek + zaimek: **An wen**. „Woran” tylko dla rzeczy.', { tags: ['wo-person'] }),
  q.mc('pa4', 'praepositionaladverbien', 2, '___ kann ich dir helfen? — Bei meinem Referat über die Donau.', ['Wobei', 'Womit', 'Wofür', 'Wovon'], 0,
    'helfen **bei** + Dat → pytanie **Wobei**.', { tags: ['wo-plus'] }),
  q.mc('pa5', 'praepositionaladverbien', 2, 'Das Konzert war super! Ich spreche noch lange ___.', ['darüber', 'davon', 'worüber', 'dafür'], 0,
    'sprechen **über** → odesłanie do rzeczy: **darüber**.', { tags: ['da-plus'] }),
  q.mc('pa6', 'praepositionaladverbien', 3, 'Ich habe mich sehr ___ gefreut, dass du gekommen bist.', ['darüber', 'daran', 'darauf', 'dafür'], 0,
    'Wizyta już się odbyła → sich freuen **über** → **darüber**, dass...', { tags: ['da-plus', 'freuen-ueber'] }),
  q.match('pa7', 'praepositionaladverbien', 2, [
    ['Wonach suchst du?', 'Nach meinem Schlüssel.'],
    ['Wovon träumst du?', 'Von einer Reise nach Island.'],
    ['Womit fährst du zur Schule?', 'Mit dem Fahrrad.'],
    ['Wofür interessierst du dich?', 'Für Fotografie.'],
    ['Worüber lachst du?', 'Über den Witz von Tim.'],
  ], 'Klucz: przyimek w pytaniu = przyimek w odpowiedzi.', { prompt: 'Dopasuj odpowiedzi do pytań. Dwie odpowiedzi są zbędne.', extra: ['Auf den Zug.', 'An meinen Freund.'], tags: ['wo-plus'] }),
  q.input('pa8', 'praepositionaladverbien', 2, '___ hast du Angst? — Vor großen Hunden. (1 słowo)', ['Wovor'],
    'Angst **vor** → **Wovor**.', { tags: ['wo-plus'] }),
  q.mc('pa9', 'praepositionaladverbien', 2, '___ ist es von hier bis zum Bahnhof? — Etwa zwei Kilometer.', ['Wie weit', 'Wie lange', 'Wie viel', 'Wie oft'], 0,
    'Pytanie o odległość = **Wie weit**. „Wie lange” pyta o czas trwania.', { tags: ['fragewort'] }),

  // ---------- Kasus ----------
  q.mc('ka1', 'kasus', 2, 'Ich spiele am Wochenende oft mit meinen ___ Fußball.', ['Freunden', 'Freunde', 'Freundes', 'Freund'], 0,
    'mit + Dativ Plural → rzeczownik dostaje **-n**: Freunden.', { tags: ['dat-pl'] }),
  q.mc('ka2', 'kasus', 2, 'Hast du schon mit dem neuen ___ gesprochen?', ['Nachbarn', 'Nachbar', 'Nachbars', 'Nachbarem'], 0,
    'der Nachbar - n-Deklination: den/dem/des Nachbar**n**.', { tags: ['n-dekl'] }),
  q.mc('ka3', 'kasus', 3, 'Der Lehrer hat dem ___ eine gute Note gegeben.', ['Studenten', 'Student', 'Students', 'Studente'], 0,
    'der Student - n-Deklination: dem Student**en**.', { tags: ['n-dekl'] }),
  q.mc('ka4', 'kasus', 2, 'Wir waren drei Wochen in Österreich und haben in vielen schönen ___ übernachtet.', ['Hotels', 'Hotelen', 'Hoteln', 'Hotel'], 0,
    'Dativ Plural: rzeczowniki z Plural na **-s** NIE dostają -n: in den Hotels, mit den Autos.', { tags: ['dat-pl'] }),
  q.mc('ka5', 'kasus', 3, 'Das ist das Fahrrad meines ___ .', ['Bruders', 'Bruder', 'Brudern', 'Brudes'], 0,
    'Genitiv maskulin: des/meines Bruder**s**.', { tags: ['genitiv'] }),
  q.input('ka6', 'kasus', 3, 'In zwei ___ (die Nacht, Plural) sind wir in Salzburg.', ['Nächten'],
    'in + Dativ (Wann?) Plural: die Nächte → in zwei Nächte**n**.', { tags: ['dat-pl'], stage: ['rejonowy', 'wojewodzki'] }),
  q.mc('ka7', 'kasus', 2, 'Ich schreibe eine E-Mail an Herrn Müller. — ___ Herr Müller, ...', ['Sehr geehrter', 'Sehr geehrten', 'Sehr geehrte', 'Sehr geehrtem'], 0,
    'W nagłówku jest Nominativ (bez rodzajnika) → mocna odmiana: **Sehr geehrter Herr Müller**.', { tags: ['adj-stark'] }),
  q.mc('ka8', 'kasus', 3, 'Kannst du bitte dem ___ da drüben den Ball zurückgeben?', ['Jungen', 'Junge', 'Jungem', 'Jung'], 0,
    'der Junge - n-Deklination: dem Junge**n**.', { tags: ['n-dekl'] }),

  // ---------- Präpositionen ----------
  q.mc('pr1', 'praepositionen', 1, '___ diesem Wetter bleiben wir lieber zu Hause.', ['Bei', 'Mit', 'In', 'Zu'], 0,
    'Stały zwrot: **bei** diesem Wetter / bei Regen.', { tags: ['praep-idiom'] }),
  q.mc('pr2', 'praepositionen', 1, 'Nächsten Sommer fahren wir ___ Schweiz.', ['in die', 'nach', 'zu der', 'in der'], 0,
    'Kraj z rodzajnikiem (die Schweiz) → **in die** Schweiz (kierunek).', { tags: ['nach-in-zu'] }),
  q.mc('pr3', 'praepositionen', 1, 'Ich muss heute Nachmittag ___ Zahnarzt.', ['zum', 'nach', 'beim', 'in'], 0,
    'Kierunek do osoby/instytucji → **zu** + Dat: zu dem = **zum** Zahnarzt.', { tags: ['nach-in-zu'] }),
  q.mc('pr4', 'praepositionen', 2, 'Ich lerne ___ drei Jahren Klavier und spiele immer noch jeden Tag.', ['seit', 'vor', 'ab', 'für'], 0,
    'Czynność trwa do dziś → **seit** + Dat.', { tags: ['temporal-praep'] }),
  q.mc('pr5', 'praepositionen', 2, '___ des schlechten Wetters fand das Konzert im Freien statt.', ['Trotz', 'Wegen', 'Während', 'Statt'], 0,
    'Mimo złej pogody → **trotz** + Genitiv. „Wegen” dałoby odwrotną logikę.', { tags: ['genitiv-praep'] }),
  q.mc('pr6', 'praepositionen', 2, 'Wir gehen ___ den Park spazieren, weil das der kürzeste Weg ist.', ['durch', 'über', 'mit', 'bei'], 0,
    'Przez (na wskroś) → **durch** + Akk.', { tags: ['akk-praep'] }),
  q.mc('pr7', 'praepositionen', 2, 'Nach dem Training fahre ich direkt nach ___ .', ['Hause', 'Haus', 'dem Haus', 'Häuser'], 0,
    'Stały zwrot kierunkowy: **nach Hause** (miejsce: zu Hause).', { tags: ['nach-in-zu'] }),
  q.input('pr8', 'praepositionen', 2, 'Der Unterricht beginnt ___ 8 Uhr. (1 słowo)', ['um'],
    'Godzina → **um**.', { tags: ['temporal-praep'] }),
  q.input('pr9', 'praepositionen', 2, 'Mein Geburtstag ist ___ 12. Mai. (1 słowo)', ['am'],
    'Data → **am** (an dem).', { tags: ['temporal-praep'] }),
  q.mc('pr10', 'praepositionen', 3, 'Der Laden ist ___ der Mittagspause geschlossen.', ['während', 'seit', 'bis', 'ab'], 0,
    'W trakcie → **während** + Genitiv.', { tags: ['genitiv-praep'] }),

  // ---------- Wechselpräpositionen ----------
  q.mc('wp1', 'wechselpraepositionen', 1, 'Leg das Handy bitte nicht auf ___ Tisch!', ['den', 'dem', 'der', 'des'], 0,
    'legen = ruch (Wohin?) → auf + Akk: **den** Tisch.', { tags: ['wohin-akk'] }),
  q.mc('wp2', 'wechselpraepositionen', 1, 'Das Buch liegt schon auf ___ Tisch.', ['dem', 'den', 'das', 'die'], 0,
    'liegen = położenie (Wo?) → auf + Dat: **dem** Tisch.', { tags: ['wo-dat'] }),
  q.mc('wp3', 'wechselpraepositionen', 2, 'Wir sind gestern Abend spät in ___ Hotel angekommen.', ['dem', 'das', 'den', 'die'], 0,
    'ankommen odpowiada na „Wo?” → in + Dativ: in **dem** (im) Hotel.', { tags: ['wo-dat'] }),
  q.mc('wp4', 'wechselpraepositionen', 2, 'Kannst du das Bild bitte an ___ Wand hängen?', ['die', 'der', 'den', 'dem'], 0,
    'hängen (przechodni, ruch) → an + Akk: **die** Wand.', { tags: ['wohin-akk'] }),
  q.mc('wp5', 'wechselpraepositionen', 2, 'Die Katze sitzt zwischen ___ Stühlen.', ['den', 'die', 'der', 'dem'], 0,
    'sitzen (Wo?) → zwischen + Dat Pl: **den** Stühlen.', { tags: ['wo-dat'] }),
  q.input('wp6', 'wechselpraepositionen', 3, 'Stell die Milch bitte in ___ Kühlschrank! (rodzajnik)', ['den'],
    'stellen = ruch → in + Akk: der Kühlschrank → **den** Kühlschrank.', { tags: ['wohin-akk'] }),
  q.gap('wp7', 'wechselpraepositionen', 3,
    'Am Samstag gehen wir in {0} Museum. Danach sitzen wir in {1} Café neben {2} Dom.',
    [['das'], ['einem', 'dem'], ['dem']],
    'gehen in (Wohin?) → Akk: das Museum; sitzen in (Wo?) → Dat: einem/dem Café; neben (Wo?) → Dat: dem Dom.', { tags: ['wohin-akk', 'wo-dat'] }),

  // ---------- Adjektivdeklination ----------
  q.mc('ad1', 'adjektivdeklination', 1, 'Das ist ein sehr ___ Museum.', ['bekanntes', 'bekannte', 'bekannten', 'bekannter'], 0,
    'ein + neutrum (Nom) - rodzajnik bez końcówki → przymiotnik -**es**.', { tags: ['adj-gemischt'] }),
  q.mc('ad2', 'adjektivdeklination', 2, 'Gibt es hier noch ___ Plätze?', ['freie', 'freien', 'freier', 'freies'], 0,
    'Bez rodzajnika, Plural, Akk → odmiana mocna: **freie**.', { tags: ['adj-stark'] }),
  q.mc('ad3', 'adjektivdeklination', 2, 'Mit ___ Grüßen, Anna', ['freundlichen', 'freundliche', 'freundlicher', 'freundlichem'], 0,
    'mit + Dativ Plural bez rodzajnika → **-en**.', { tags: ['adj-stark'] }),
  q.mc('ad4', 'adjektivdeklination', 2, 'Wir wohnen in einer ___ Wohnung im Zentrum.', ['kleinen', 'kleine', 'kleiner', 'kleines'], 0,
    'in einer (Dat f) → przymiotnik **-en**.', { tags: ['adj-gemischt'] }),
  q.mc('ad5', 'adjektivdeklination', 3, 'Viele ___ Leute besuchen jedes Jahr die Museumsinsel.', ['junge', 'jungen', 'junger', 'junges'], 0,
    'Po **viele** → odmiana mocna: junge Leute (nie „jungen”).', { tags: ['adj-stark'] }),
  q.mc('ad6', 'adjektivdeklination', 3, 'Alle ___ Schüler haben die Prüfung bestanden.', ['neuen', 'neue', 'neuer', 'neues'], 0,
    'Po **alle** → odmiana słaba: alle neu**en** Schüler.', { tags: ['adj-schwach'] }),
  q.input('ad7', 'adjektivdeklination', 2, 'Ich trinke gern ___ Tee mit Zitrone. (heiß)', ['heißen'],
    'Akk maskulin bez rodzajnika → mocna odmiana: heiß**en** Tee.', { tags: ['adj-stark'] }),
  q.input('ad8', 'adjektivdeklination', 3, 'Der Kölner Dom ist eines der ___ Bauwerke Europas. (berühmt, stopień najwyższy)', ['berühmtesten'],
    'eines der + Genitiv Plural, superlatyw: berühm**test**en.', { tags: ['adj-schwach', 'superlativ'], stage: ['rejonowy', 'wojewodzki'] }),
  q.gap('ad9', 'adjektivdeklination', 3,
    'Neuschwanstein ist ein {0} (romantisch) Schloss mit einer {1} (wunderbar) Aussicht auf die {2} (bayerisch) Alpen.',
    [['romantisches'], ['wunderbaren'], ['bayerischen']],
    'ein + neutrum → -es; mit einer (Dat f) → -en; die + Plural → -en.', { tags: ['adj-gemischt', 'adj-schwach'] }),
  q.mc('ad10', 'adjektivdeklination', 2, 'Hast du den ___ Film schon gesehen?', ['neuen', 'neue', 'neuer', 'neues'], 0,
    'den (Akk m) → przymiotnik -**en**.', { tags: ['adj-schwach'] }),

  // ---------- Komparation ----------
  q.mc('ko1', 'komparation', 1, 'Die Zugspitze ist höher ___ der Brocken.', ['als', 'wie', 'so', 'dann'], 0,
    'Stopień wyższy + **als**.', { tags: ['als-wie'] }),
  q.mc('ko2', 'komparation', 1, 'Mein Bruder ist genauso alt ___ dein Bruder.', ['wie', 'als', 'so', 'wenn'], 0,
    'Równość: (genau)so ... **wie**.', { tags: ['als-wie'] }),
  q.mc('ko3', 'komparation', 2, 'Ich esse gern Pizza, aber am ___ esse ich Pasta.', ['liebsten', 'gernsten', 'besten', 'meisten'], 0,
    'gern → lieber → **am liebsten**.', { tags: ['komp-unregel'] }),
  q.input('ko4', 'komparation', 2, 'Der Rhein ist lang, aber die Donau ist noch ___. (lang)', ['länger'],
    'lang → **länger** (przegłos).', { tags: ['komp-umlaut'] }),
  q.input('ko5', 'komparation', 3, 'Der Kölner Dom war nach seiner Fertigstellung 1880 kurz das ___ Gebäude der Welt. (hoch)', ['höchste'],
    'hoch → höher → am höchsten; przed rzeczownikiem: das **höchste** Gebäude.', { tags: ['superlativ', 'komp-unregel'] }),
  q.mc('ko6', 'komparation', 2, 'Das ist ein ___ Turm als der in unserer Stadt.', ['höherer', 'hoher', 'höher', 'höchster'], 0,
    'Stopień wyższy przed rzeczownikiem też się odmienia: ein höher**er** Turm.', { tags: ['komp-attributiv'] }),

  // ---------- Wortstellung ----------
  q.order('ws1', 'wortstellung', 1, ['Morgen', 'fahre', 'ich', 'mit', 'dem', 'Zug', 'nach', 'Wien.'],
    'Inwersja: okolicznik czasu na 1. miejscu → czasownik na 2., potem podmiot.', { alt: [['Ich', 'fahre', 'morgen', 'mit', 'dem', 'Zug', 'nach', 'Wien.']], tags: ['inversion'] }),
  q.order('ws2', 'wortstellung', 2, ['Ich', 'bleibe', 'zu', 'Hause,', 'weil', 'ich', 'krank', 'bin.'],
    'weil → czasownik osobowy na końcu.', { tags: ['nebensatz'] }),
  q.order('ws3', 'wortstellung', 3, ['Er', 'sagt,', 'dass', 'er', 'nicht', 'kommen', 'kann.'],
    'Zdanie podrzędne z modalnym: bezokolicznik + czasownik modalny na końcu.', { tags: ['nebensatz'] }),
  q.mc('ws4', 'wortstellung', 2, 'Wenn es morgen regnet, ...', ['bleiben wir zu Hause.', 'wir bleiben zu Hause.', 'wir zu Hause bleiben.', 'zu Hause wir bleiben.'], 0,
    'Zdanie podrzędne na początku = 1. pozycja → od razu czasownik: **bleiben wir**.', { tags: ['nebensatz-vorn'] }),
  q.mc('ws5', 'wortstellung', 2, 'Ich weiß nicht, ...', ['ob er das Buch schon gelesen hat.', 'ob er hat das Buch schon gelesen.', 'ob hat er das Buch schon gelesen.', 'ob er das Buch schon hat gelesen.'], 0,
    'Perfekt w zdaniu podrzędnym: Partizip + **hat** na samym końcu.', { tags: ['nebensatz'] }),
  q.order('ws6', 'wortstellung', 3, ['Nachdem', 'wir', 'gegessen', 'hatten,', 'gingen', 'wir', 'ins', 'Kino.'],
    'Nebensatz na początku → czasownik główny zaraz po przecinku.', { tags: ['nebensatz-vorn'] }),
  q.mc('ws7', 'wortstellung', 2, 'Der Film ist so spannend, dass ...', ['ich ihn noch einmal sehen möchte.', 'ich möchte ihn noch einmal sehen.', 'möchte ich ihn noch einmal sehen.', 'ich ihn möchte noch einmal sehen.'], 0,
    'dass → czasownik osobowy (möchte) na końcu.', { tags: ['nebensatz'] }),

  // ---------- Konnektoren ----------
  q.mc('kn1', 'konnektoren', 1, 'Ich gehe heute nicht zum Training, ___ ich bin erkältet.', ['denn', 'weil', 'obwohl', 'deshalb'], 0,
    'Szyk Hauptsatz (bin na 2. miejscu) + przyczyna → **denn**. „weil” wymagałoby „erkältet bin”.', { tags: ['denn-weil'] }),
  q.mc('kn2', 'konnektoren', 2, '___ es stark regnet, gehen wir spazieren.', ['Obwohl', 'Weil', 'Trotzdem', 'Denn'], 0,
    'Kontrast (mimo deszczu) + Nebensatz → **Obwohl**.', { tags: ['obwohl-trotzdem'] }),
  q.mc('kn3', 'konnektoren', 2, 'Es regnet stark. ___ gehen wir spazieren.', ['Trotzdem', 'Obwohl', 'Deshalb', 'Weil'], 0,
    'Kontrast + inwersja (gehen wir) → **Trotzdem**.', { tags: ['obwohl-trotzdem'] }),
  q.mc('kn4', 'konnektoren', 2, 'Ich habe morgen eine Prüfung, ___ kann ich heute nicht mitkommen.', ['deshalb', 'denn', 'obwohl', 'weil'], 0,
    'Skutek + inwersja (kann ich) → **deshalb**.', { tags: ['deshalb'] }),
  q.mc('kn5', 'konnektoren', 2, 'Das ist nicht mein Heft, ___ das von Lukas.', ['sondern', 'aber', 'oder', 'denn'], 0,
    'Korekta po zaprzeczeniu → **sondern**.', { tags: ['sondern'] }),
  q.mc('kn6', 'konnektoren', 3, 'Paul hat die ganze Nacht gelernt. ___ hat er die Prüfung nicht bestanden.', ['Trotzdem', 'Deshalb', 'Außerdem', 'Also'], 0,
    'Wynik sprzeczny z oczekiwaniem → **Trotzdem**.', { tags: ['obwohl-trotzdem'] }),
  q.mc('kn7', 'konnektoren', 3, 'Die Wohnung ist sehr hell. ___ hat sie einen großen Balkon.', ['Außerdem', 'Trotzdem', 'Deshalb', 'Sondern'], 0,
    'Dodatkowa zaleta → **Außerdem** (poza tym).', { tags: ['ausserdem'] }),
  q.transform('kn8', 'konnektoren', 3, 'Obwohl er müde war, spielte er weiter. → Er war müde. ___', ['Trotzdem spielte er weiter.', 'Er spielte trotzdem weiter.'],
    'obwohl (Nebensatz) ↔ trotzdem (inwersja).', { hint: 'Użyj: trotzdem', tags: ['obwohl-trotzdem'], stage: ['rejonowy', 'wojewodzki'] }),
  q.transform('kn9', 'konnektoren', 3, 'Ich hatte keine Zeit, deshalb bin ich nicht gekommen. → Ich bin nicht gekommen, ___', ['weil ich keine Zeit hatte.'],
    'deshalb (skutek) ↔ weil (przyczyna) + czasownik na końcu.', { hint: 'Użyj: weil', tags: ['denn-weil'], stage: ['rejonowy', 'wojewodzki'] }),

  // ---------- wenn / als / ob ----------
  q.mc('wa1', 'wenn-als-ob', 1, '___ ich zehn Jahre alt war, sind wir nach Wien gezogen.', ['Als', 'Wenn', 'Wann', 'Ob'], 0,
    'Jednorazowo w przeszłości → **Als**.', { tags: ['als-wenn'] }),
  q.mc('wa2', 'wenn-als-ob', 2, 'Immer ___ wir Oma besuchten, backte sie einen Kuchen.', ['wenn', 'als', 'wann', 'ob'], 0,
    'Powtarzalnie w przeszłości (immer) → **wenn**.', { tags: ['als-wenn'] }),
  q.mc('wa3', 'wenn-als-ob', 2, 'Weißt du, ___ der Zug nach Berlin abfährt?', ['wann', 'wenn', 'als', 'ob'], 0,
    'Pytanie zależne o czas → **wann**.', { tags: ['wann'] }),
  q.mc('wa4', 'wenn-als-ob', 2, 'Ich weiß noch nicht, ___ ich zur Party komme.', ['ob', 'wenn', 'wann', 'als'], 0,
    '„czy” (pytanie tak/nie) → **ob**.', { tags: ['ob'] }),
  q.mc('wa5', 'wenn-als-ob', 3, '___ ich klein war, hatte ich Angst vor Hunden.', ['Als', 'Wenn', 'Wann', 'Während'], 0,
    'Okres życia (dzieciństwo) = jedna całość w przeszłości → **Als**.', { tags: ['als-wenn'] }),
  q.input('wa6', 'wenn-als-ob', 2, '___ du Lust hast, können wir am Samstag ins Kino gehen. (1 słowo)', ['Wenn'],
    'Warunek → **Wenn**.', { tags: ['als-wenn'] }),

  // ---------- Perfekt ----------
  q.mc('pe1', 'perfekt', 1, 'Letztes Jahr ___ wir nach Salzburg gefahren.', ['sind', 'haben', 'waren', 'hatten'], 0,
    'fahren (zmiana miejsca) → Perfekt z **sein**.', { tags: ['sein-haben'] }),
  q.mc('pe2', 'perfekt', 2, 'Der Film hat um acht Uhr ___ .', ['begonnen', 'begann', 'gebeginnt', 'beginnen'], 0,
    'beginnen - begann - **begonnen** (bez ge-, bo be-).', { tags: ['partizip-stark'] }),
  q.mc('pe3', 'perfekt', 2, 'Hast du die Aufgabe ___ ?', ['verstanden', 'geverstanden', 'verstehen', 'verstandet'], 0,
    'ver- to przedrostek nierozdzielny → bez ge-: **verstanden**.', { tags: ['partizip-untrennbar'] }),
  q.mc('pe4', 'perfekt', 2, 'Meine Tante ist vor drei Jahren nach Hamburg ___ .', ['umgezogen', 'geumzogen', 'umgeziehen', 'umziehen'], 0,
    'umziehen (rozdzielny) → um-**ge**-zogen, Perfekt z sein.', { tags: ['partizip-trennbar'] }),
  q.input('pe5', 'perfekt', 2, 'Wir haben im Urlaub viel ___ . (fotografieren)', ['fotografiert'],
    '-ieren → bez ge-: **fotografiert**.', { tags: ['partizip-ieren'] }),
  q.input('pe6', 'perfekt', 2, 'Ich habe meinen Schlüssel ___ . (verlieren)', ['verloren'],
    'verlieren - verlor - **verloren**.', { tags: ['partizip-stark'] }),
  q.input('pe7', 'perfekt', 3, 'Was ist denn hier ___ ? (passieren)', ['passiert'],
    'passieren → Perfekt z **sein**, Partizip **passiert** (bez ge-).', { tags: ['partizip-ieren', 'sein-haben'] }),
  q.mc('pe8', 'perfekt', 3, 'Heute Morgen ___ ich um sechs Uhr aufgewacht.', ['bin', 'habe', 'war', 'wurde'], 0,
    'aufwachen = zmiana stanu → **sein**.', { tags: ['sein-haben'] }),
  q.mc('pe9', 'perfekt', 3, 'Gestern ___ ich meinem alten Lehrer in der Stadt begegnet.', ['bin', 'habe', 'hatte', 'wurde'], 0,
    'begegnen łączy się z **sein** (mimo że nie oznacza ruchu).', { tags: ['sein-haben'] }),
  q.gap('pe10', 'perfekt', 3,
    'Gestern {0} ich meine Freundin getroffen. Wir {1} zusammen ins Museum gegangen und {2} danach Eis gegessen.',
    [['habe'], ['sind'], ['haben']],
    'treffen → haben; gehen → sein; essen → haben.', { tags: ['sein-haben'] }),
  q.input('pe11', 'perfekt', 2, 'Wer hat dir das ___ ? (bringen)', ['gebracht'],
    'bringen - brachte - **gebracht** (czasownik mieszany).', { tags: ['partizip-gemischt'] }),

  // ---------- Präteritum ----------
  q.mc('pt1', 'praeteritum', 1, 'Früher ___ es in unserer Stadt kein Kino.', ['gab', 'gibt', 'gebt', 'gegeben'], 0,
    'es gibt → Präteritum: es **gab**.', { tags: ['praet-stark'] }),
  q.mc('pt2', 'praeteritum', 2, 'Karl der Große ___ in Aachen eine prächtige Pfalzkapelle bauen.', ['ließ', 'lass', 'lasste', 'ließe'], 0,
    'lassen - **ließ** - gelassen („kazał zbudować”).', { tags: ['praet-stark'] }),
  q.input('pt3', 'praeteritum', 2, 'Als Kind ___ ich oft bei meinen Großeltern. (sein)', ['war'],
    'sein → Präteritum ich **war**.', { tags: ['praet-stark'] }),
  q.input('pt4', 'praeteritum', 3, 'Mozart ___ schon als Kind Klavier und Geige. (spielen)', ['spielte'],
    'Czasownik regularny: spiel-**te**.', { tags: ['praet-schwach'] }),
  q.input('pt5', 'praeteritum', 3, 'Die Brüder Grimm ___ viele Märchen. (sammeln)', ['sammelten'],
    'sammeln → sie **sammelten**.', { tags: ['praet-schwach'] }),
  q.mc('pt6', 'praeteritum', 3, 'Nachdem wir den Dom ___ , gingen wir essen.', ['besichtigt hatten', 'besichtigt haben', 'besichtigten', 'besichtigen'], 0,
    'Zdanie główne w Präteritum → po nachdem **Plusquamperfekt**.', { tags: ['plusquamperfekt'] }),
  q.input('pt7', 'praeteritum', 3, 'Er ___ nicht, was er sagen sollte. (wissen)', ['wusste'],
    'wissen - **wusste** - gewusst (mieszany).', { tags: ['praet-gemischt'] }),
  q.mc('pt8', 'praeteritum', 2, 'Goethe ___ 1749 in Frankfurt am Main geboren.', ['wurde', 'war', 'ist', 'hatte'], 0,
    'Urodzić się w przeszłości: er **wurde** ... geboren (Passiv, Präteritum). „ist geboren” o żyjących.', { tags: ['praet-stark', 'passiv-praet'] }),

  // ---------- Zeitformen / Präsens ----------
  q.mc('zf1', 'zeitformen', 1, 'Warum ___ du so schnell? Wir haben Zeit!', ['isst', 'esst', 'esse', 'ist'], 0,
    'essen → du **isst** (e → i).', { tags: ['praesens-vokal'] }),
  q.mc('zf2', 'zeitformen', 2, '___ nicht so schnell, die Straße ist glatt!', ['Fahr', 'Fährt', 'Fahrt du', 'Fähr'], 0,
    'Imperativ (du): **Fahr!** - bez przegłosu.', { tags: ['imperativ'] }),
  q.input('zf3', 'zeitformen', 2, 'Meine Schwester ___ jeden Abend ein Buch. (lesen)', ['liest'],
    'lesen → sie **liest**.', { tags: ['praesens-vokal'] }),
  q.input('zf4', 'zeitformen', 2, 'Wann ___ du morgen nach Hause? (kommen) — Um vier.', ['kommst'],
    'Präsens du: **kommst**.', { tags: ['praesens'] }),
  q.mc('zf5', 'zeitformen', 3, 'Er ist nicht gekommen. Er ___ wohl krank sein.', ['wird', 'würde', 'wurde', 'werde'], 0,
    'Przypuszczenie o teraźniejszości: Futur I - er **wird** wohl krank sein.', { tags: ['futur'] }),
  q.input('zf6', 'zeitformen', 3, '___ doch mal den Text genau! (lesen, Imperativ du)', ['Lies'],
    'lesen → Imperativ: **Lies!**', { tags: ['imperativ'] }),

  // ---------- Modalverben ----------
  q.mc('mo1', 'modalverben', 1, 'Mama, ___ ich heute Abend länger aufbleiben?', ['darf', 'muss', 'soll', 'will'], 0,
    'Prośba o pozwolenie → **dürfen**.', { tags: ['duerfen'] }),
  q.mc('mo2', 'modalverben', 2, 'Du ___ nicht mitkommen, wenn du keine Lust hast.', ['musst', 'darfst', 'sollst', 'kannst'], 0,
    'Nie ma konieczności → **nicht müssen**. „nicht dürfen” = zakaz.', { tags: ['nicht-muessen'] }),
  q.mc('mo3', 'modalverben', 2, 'Im Museum ___ man nicht fotografieren. Das ist verboten.', ['darf', 'muss', 'will', 'mag'], 0,
    'Zakaz → **nicht dürfen**.', { tags: ['duerfen'] }),
  q.mc('mo4', 'modalverben', 2, 'Der Arzt hat gesagt, ich ___ mehr Wasser trinken.', ['soll', 'will', 'darf', 'mag'], 0,
    'Polecenie/rada innej osoby → **sollen**.', { tags: ['sollen'] }),
  q.input('mo5', 'modalverben', 2, 'Gestern ___ ich nicht zur Schule gehen, weil ich krank war. (können)', ['konnte'],
    'Präteritum bez przegłosu: **konnte**.', { tags: ['modal-praet'] }),
  q.input('mo6', 'modalverben', 2, '___ du mir bitte helfen? (können)', ['Kannst'],
    'Prośba o pomoc → können: du **kannst**.', { tags: ['koennen'] }),
  q.transform('mo7', 'modalverben', 3, 'Es ist mir nicht erlaubt, allein in die Stadt zu fahren. → Ich ___', ['darf nicht allein in die Stadt fahren.'],
    'es ist (nicht) erlaubt ↔ (nicht) **dürfen**.', { hint: 'Użyj czasownika modalnego', tags: ['duerfen', 'modal-paraphrase'], stage: ['rejonowy', 'wojewodzki'] }),
  q.transform('mo8', 'modalverben', 3, 'Es ist nicht nötig, dass du mich abholst. → Du ___', ['musst mich nicht abholen.'],
    'es ist nicht nötig ↔ **nicht müssen**.', { hint: 'Użyj czasownika modalnego', tags: ['nicht-muessen', 'modal-paraphrase'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('mo9', 'modalverben', 2, 'Hier ___ du leider nicht parken. (dürfen)', ['darfst'],
    'dürfen → du **darfst**.', { tags: ['duerfen'] }),

  // ---------- Konjunktiv II ----------
  q.mc('kj1', 'konjunktiv2', 1, '___ Sie mir bitte sagen, wie spät es ist?', ['Könnten', 'Konnten', 'Können wären', 'Kannten'], 0,
    'Uprzejma prośba → Konjunktiv II: **Könnten** Sie ...?', { tags: ['hoeflich'] }),
  q.mc('kj2', 'konjunktiv2', 2, 'Wenn ich mehr Zeit ___ , würde ich öfter lesen.', ['hätte', 'habe', 'hatte', 'haben würde'], 0,
    'Warunek nierzeczywisty: haben → **hätte**.', { tags: ['irreal'] }),
  q.mc('kj3', 'konjunktiv2', 2, 'An deiner Stelle ___ ich mit dem Lehrer sprechen.', ['würde', 'werde', 'wurde', 'wird'], 0,
    'Rada: An deiner Stelle **würde** ich ...', { tags: ['ratschlag'] }),
  q.mc('kj4', 'konjunktiv2', 3, 'Wenn ich das gewusst ___ , wäre ich früher gekommen.', ['hätte', 'wäre', 'würde', 'habe'], 0,
    'Przeszłość nierzeczywista: hätte + Partizip II (wissen → haben).', { tags: ['irreal-vergangen'] }),
  q.input('kj5', 'konjunktiv2', 2, 'Wenn ich reich ___ , würde ich eine Weltreise machen. (sein)', ['wäre'],
    'sein → **wäre**.', { tags: ['irreal'] }),
  q.input('kj6', 'konjunktiv2', 3, 'Du ___ mehr schlafen, du siehst müde aus. (sollen - rada)', ['solltest'],
    'Rada: du **solltest** (Konjunktiv II od sollen, bez przegłosu).', { tags: ['ratschlag'] }),

  // ---------- Passiv ----------
  q.mc('pv1', 'passiv', 1, 'In Österreich ___ Deutsch gesprochen.', ['wird', 'ist', 'hat', 'werden'], 0,
    'Passiv Präsens: **wird** + Partizip II.', { tags: ['passiv-praes'] }),
  q.mc('pv2', 'passiv', 2, 'Der Kölner Dom ___ im Jahr 1880 vollendet.', ['wurde', 'wird', 'war', 'ist'], 0,
    'Passiv Präteritum: **wurde** + Partizip II.', { tags: ['passiv-praet'] }),
  q.mc('pv3', 'passiv', 3, 'Das Schloss ist im 19. Jahrhundert gebaut ___ .', ['worden', 'geworden', 'gewesen', 'werden'], 0,
    'Perfekt Passiv: ist + Partizip + **worden** (nie „geworden”).', { tags: ['passiv-perfekt'] }),
  q.mc('pv4', 'passiv', 2, 'Die Altstadt muss dringend renoviert ___ .', ['werden', 'worden', 'wird', 'wurde'], 0,
    'Passiv z modalnym: Partizip + **werden** (bezokolicznik).', { tags: ['passiv-modal'] }),
  q.input('pv5', 'passiv', 3, 'Die Porta Nigra ___ von den Römern gebaut. (werden, Präteritum)', ['wurde'],
    'Präteritum Passiv, liczba pojedyncza: **wurde**.', { tags: ['passiv-praet'], stage: ['rejonowy', 'wojewodzki'] }),
  q.transform('pv6', 'passiv', 3, 'Man renoviert das Rathaus. → Das Rathaus ___', ['wird renoviert.'],
    '„man” + strona czynna ↔ strona bierna bez sprawcy.', { tags: ['passiv-praes'], stage: ['rejonowy', 'wojewodzki'] }),
  q.transform('pv7', 'passiv', 3, 'Die Römer gründeten die Stadt Trier. → Die Stadt Trier ___', ['wurde von den Römern gegründet.'],
    'Sprawca w Passiv: **von** + Dativ (den Römern).', { tags: ['passiv-praet', 'passiv-von'], stage: ['wojewodzki'] }),
  q.gap('pv8', 'passiv', 3,
    'Die Wartburg {0} um 1067 gegründet. Hier {1} das Neue Testament von Martin Luther ins Deutsche übersetzt. Heute {2} die Burg jedes Jahr von vielen Touristen besucht.',
    [['wurde'], ['wurde'], ['wird']],
    'Wydarzenia historyczne → Präteritum Passiv (wurde); dziś → Präsens Passiv (wird).', { tags: ['passiv-praet', 'passiv-praes'], stage: ['rejonowy', 'wojewodzki'] }),

  // ---------- Relativsätze ----------
  q.mc('rs1', 'relativsaetze', 1, 'Das ist der Mann, ___ neben uns wohnt.', ['der', 'den', 'dem', 'dessen'], 0,
    'Podmiot zdania względnego (wer wohnt?) → Nominativ: **der**.', { tags: ['rel-nom'] }),
  q.mc('rs2', 'relativsaetze', 2, 'Das ist der Film, ___ ich dir empfohlen habe.', ['den', 'der', 'dem', 'das'], 0,
    'empfehlen + Akk (was?) → der Film → **den**.', { tags: ['rel-akk'] }),
  q.mc('rs3', 'relativsaetze', 2, 'Das ist mein Freund, ___ ich das Buch geliehen habe.', ['dem', 'den', 'der', 'dessen'], 0,
    'jemandem etwas leihen → osoba w Dativ: **dem**.', { tags: ['rel-dat'] }),
  q.mc('rs4', 'relativsaetze', 2, 'Die Kinder, mit ___ ich Fußball spiele, sind aus meiner Klasse.', ['denen', 'den', 'die', 'deren'], 0,
    'mit + Dativ **Plural** → **denen**.', { tags: ['rel-dat', 'rel-praep'] }),
  q.mc('rs5', 'relativsaetze', 3, 'Die Frau, ___ Sohn in meiner Klasse ist, ist Ärztin.', ['deren', 'dessen', 'der', 'die'], 0,
    'Dzierżawczy (jej syn), odniesienie do die Frau → **deren**.', { tags: ['rel-gen'] }),
  q.mc('rs6', 'relativsaetze', 3, 'Wien ist die Stadt, in ___ ich sieben Jahre gewohnt habe.', ['der', 'die', 'dem', 'denen'], 0,
    'wohnen in (Wo?) → Dativ, die Stadt → **der**.', { tags: ['rel-praep', 'rel-dat'] }),
  q.mc('rs7', 'relativsaetze', 3, 'Das ist alles, ___ ich über die Wartburg weiß.', ['was', 'das', 'dass', 'welches'], 0,
    'Po **alles, nichts, etwas** → **was**.', { tags: ['rel-was'] }),
  q.input('rs8', 'relativsaetze', 2, 'Der Lehrer, ___ wir so viel verdanken, geht in Rente. (zaimek względny)', ['dem'],
    'jemandem etwas verdanken → Dativ: **dem**.', { tags: ['rel-dat'] }),
  q.input('rs9', 'relativsaetze', 3, 'Das sind die Nachbarn, ___ Hund immer bellt. (zaimek względny)', ['deren'],
    'Plural + dzierżawczy → **deren**.', { tags: ['rel-gen'] }),
  q.input('rs10', 'relativsaetze', 3, 'Die Freunde, ___ ich geholfen habe, haben sich bedankt. (zaimek względny)', ['denen'],
    'helfen + Dativ, Plural → **denen**.', { tags: ['rel-dat'] }),
  q.input('rs11', 'relativsaetze', 3, 'Das ist der Freund, auf ___ ich schon eine Stunde warte. (zaimek względny)', ['den'],
    'warten **auf** + Akk, der Freund → auf **den**.', { tags: ['rel-praep', 'rel-akk'] }),
  q.transform('rs12', 'relativsaetze', 3, 'Ich habe einen Onkel. Sein Haus steht direkt am Rhein. → Ich habe einen Onkel, ___', ['dessen Haus direkt am Rhein steht.'],
    'sein Haus (maskulin, dzierżawczy) → **dessen**; czasownik na końcu.', { tags: ['rel-gen'], stage: ['wojewodzki'] }),

  // ---------- Reflexivverben ----------
  q.mc('rv1', 'reflexivverben', 1, 'Worauf freust ___ dich am meisten?', ['du', 'dich', 'dir', 'sich'], 0,
    'Podmiot w pytaniu: freust **du** dich.', { tags: ['reflexiv'] }),
  q.mc('rv2', 'reflexivverben', 2, 'Ich wasche ___ jeden Morgen die Haare.', ['mir', 'mich', 'mein', 'sich'], 0,
    'die Haare = Akk → zaimek zwrotny w **Dativ**: mir.', { tags: ['reflexiv-dat'] }),
  q.mc('rv3', 'reflexivverben', 2, 'Kannst du ___ vorstellen, wie groß der Kölner Dom ist?', ['dir', 'dich', 'du', 'sich'], 0,
    'sich (Dat) etwas vorstellen → **dir**.', { tags: ['reflexiv-dat'] }),
  q.mc('rv4', 'reflexivverben', 2, 'Beeil ___ , der Zug fährt gleich ab!', ['dich', 'dir', 'du', 'sich'], 0,
    'sich beeilen (Akk) → Beeil **dich**!', { tags: ['reflexiv'] }),
  q.input('rv5', 'reflexivverben', 2, 'Zieh ___ eine warme Jacke an, es ist kalt! (zaimek)', ['dir'],
    'eine Jacke = Akk → zaimek zwrotny w Dativ: **dir**.', { tags: ['reflexiv-dat'] }),
  q.input('rv6', 'reflexivverben', 2, 'Ich habe ___ gestern erkältet. (zaimek)', ['mich'],
    'sich erkälten (bez innego dopełnienia) → **mich**.', { tags: ['reflexiv'] }),
  q.mc('rv7', 'reflexivverben', 3, 'Ich wünsche ___ zum Geburtstag ein neues Fahrrad.', ['mir', 'mich', 'sich', 'mein'], 0,
    'sich (Dat) etwas wünschen → **mir**.', { tags: ['reflexiv-dat'] }),

  // ---------- Pronomen ----------
  q.mc('pn1', 'pronomen', 1, 'Das Geschenk gefällt ___ sehr. (on)', ['ihm', 'ihn', 'er', 'sein'], 0,
    'gefallen + Dativ → **ihm**.', { tags: ['dat-verb'] }),
  q.mc('pn2', 'pronomen', 2, 'Kannst du ___ bitte helfen? (ja)', ['mir', 'mich', 'ich', 'mein'], 0,
    'helfen + Dativ → **mir**.', { tags: ['dat-verb'] }),
  q.mc('pn3', 'pronomen', 2, 'Wir fahren mit ___ Auto nach Italien. (wasz)', ['eurem', 'euren', 'euerem', 'eure'], 0,
    'mit + Dat neutrum, euer → **eurem** (e wypada).', { tags: ['possessiv'] }),
  q.input('pn4', 'pronomen', 3, 'Wie geht es ___ , Frau Müller? (Pani)', ['Ihnen'],
    'Forma grzecznościowa w Dativ: **Ihnen** (wielka litera).', { tags: ['sie-form'] }),
  q.input('pn5', 'pronomen', 3, 'Du hast morgen Geburtstag? Dann gratuliere ich ___ schon heute! (ty)', ['dir'],
    'gratulieren + Dativ → **dir**.', { tags: ['dat-verb'] }),
  q.mc('pn6', 'pronomen', 3, 'Hast du Anna das Buch schon gegeben? — Ja, ich habe ___ gestern gegeben.', ['es ihr', 'ihr es', 'sie ihm', 'ihm es'], 0,
    'Dwa zaimki: najpierw Akk (es), potem Dat (ihr).', { tags: ['pronomen-stellung'] }),

  // ---------- Infinitiv mit zu ----------
  q.mc('iz1', 'infinitiv-zu', 1, 'Ich habe heute keine Lust, ins Kino ___ .', ['zu gehen', 'gehen', 'gehe', 'zu geht'], 0,
    'Lust haben + **zu** + bezokolicznik.', { tags: ['zu-inf'] }),
  q.mc('iz2', 'infinitiv-zu', 2, 'Vergiss nicht, deine Oma ___ !', ['anzurufen', 'zu anrufen', 'anrufen', 'anruft zu'], 0,
    'Czasownik rozdzielny: zu w środku → an**zu**rufen.', { tags: ['zu-trennbar'] }),
  q.mc('iz3', 'infinitiv-zu', 2, 'Ich spare Geld, ___ mir ein neues Fahrrad zu kaufen.', ['um', 'damit', 'ohne', 'statt'], 0,
    'Cel, ten sam podmiot → **um** ... zu.', { tags: ['um-zu'] }),
  q.mc('iz4', 'infinitiv-zu', 3, 'Ich erkläre es dir noch einmal, ___ du es verstehst.', ['damit', 'um', 'ohne', 'dass zu'], 0,
    'Cel, różne podmioty (ich / du) → **damit**.', { tags: ['damit'] }),
  q.mc('iz5', 'infinitiv-zu', 3, 'Er ist gegangen, ___ sich zu verabschieden.', ['ohne', 'statt', 'um', 'damit'], 0,
    'bez pożegnania → **ohne** ... zu.', { tags: ['ohne-zu'] }),
  q.transform('iz6', 'infinitiv-zu', 3, 'Er spielt Computer. Er sollte lernen. → Statt ___', ['zu lernen, spielt er Computer.'],
    '**statt ... zu** + inwersja w zdaniu głównym.', { hint: 'statt ... zu', tags: ['statt-zu'], stage: ['wojewodzki'] }),
  q.transform('iz7', 'infinitiv-zu', 3, 'Ich fahre nach Berlin, weil ich die Museumsinsel besuchen will. → Ich fahre nach Berlin, um ___', ['die Museumsinsel zu besuchen.'],
    'Cel, ten sam podmiot → um ... zu.', { tags: ['um-zu'], stage: ['wojewodzki'] }),

  // ---------- Trennbare Verben ----------
  q.mc('tv1', 'trennbare-verben', 1, 'Der Zug ___ um 7:15 Uhr ___ .', ['fährt ... ab', 'abfährt ... -', 'fährt ... an', 'ab ... fährt'], 0,
    'abfahren rozdziela się w zdaniu głównym: fährt ... **ab**.', { tags: ['trennbar'] }),
  q.mc('tv2', 'trennbare-verben', 2, 'Ich weiß nicht, wann der Film ___ .', ['anfängt', 'fängt an', 'an fängt', 'anfangt'], 0,
    'W zdaniu podrzędnym przedrostek łączy się z czasownikiem: **anfängt**.', { tags: ['trennbar-nebensatz'] }),
  q.input('tv3', 'trennbare-verben', 2, 'Kannst du mich morgen vom Bahnhof ___ ? (odebrać)', ['abholen'],
    'abholen - odebrać kogoś.', { tags: ['trennbar'] }),
  q.mc('tv4', 'trennbare-verben', 3, 'Die Lehrerin ___ den Text ins Polnische.', ['übersetzt', 'setzt ... über', 'übergesetzt', 'übersetzte zu'], 0,
    'übersetzen (tłumaczyć) jest **nierozdzielny**: sie übersetzt.', { tags: ['untrennbar'] }),

  // ---------- Indirekte Fragen ----------
  q.mc('if1', 'indirekte-fragen', 2, 'Können Sie mir sagen, ___ ?', ['wo der Bahnhof ist', 'wo ist der Bahnhof', 'wo der Bahnhof sein', 'ist wo der Bahnhof'], 0,
    'Pytanie zależne: czasownik na koniec.', { tags: ['indirekt'] }),
  q.transform('if2', 'indirekte-fragen', 3, 'Wie alt ist dein Bruder? → Ich möchte wissen, ___', ['wie alt dein Bruder ist.'],
    'Zaimek pytający + podmiot + ... + czasownik na końcu.', { tags: ['indirekt'], stage: ['wojewodzki'] }),
  q.transform('if3', 'indirekte-fragen', 3, 'Kommt Lisa morgen zur Party? → Weißt du, ___', ['ob Lisa morgen zur Party kommt?'],
    'Pytanie tak/nie → **ob** + czasownik na końcu.', { tags: ['indirekt', 'ob'], stage: ['wojewodzki'] }),
  q.order('if4', 'indirekte-fragen', 2, ['Weißt', 'du,', 'wann', 'das', 'Museum', 'öffnet?'],
    'wann + podmiot + czasownik na końcu.', { tags: ['indirekt'] }),

  // ---------- Imperativ / Negation ----------
  q.mc('im1', 'imperativ', 2, 'Kinder, ___ bitte leise! Das Baby schläft.', ['seid', 'seit', 'sind', 'sei'], 0,
    'Imperativ ihr od sein: **seid**. („seit” = od kiedy)', { tags: ['imperativ'] }),
  q.input('im2', 'imperativ', 2, '___ dein Gemüse, bevor es kalt wird! (essen, du)', ['Iss'],
    'essen → Imperativ du: **Iss!**', { tags: ['imperativ'] }),
  q.input('im3', 'imperativ', 3, '___ doch dein Handy mit! (nehmen, du)', ['Nimm'],
    'nehmen → **Nimm!** (mitnehmen → Nimm ... mit!)', { tags: ['imperativ'] }),
  q.mc('ng1', 'negation', 1, 'Ich habe heute ___ Zeit.', ['keine', 'nicht', 'nichts', 'nie'], 0,
    'Rzeczownik bez rodzajnika → **kein(e)**.', { tags: ['kein-nicht'] }),
  q.mc('ng2', 'negation', 2, 'Kommst du nicht mit? — ___, natürlich komme ich mit!', ['Doch', 'Ja', 'Nein', 'Nicht'], 0,
    'Odpowiedź twierdząca na pytanie przeczące → **Doch**.', { tags: ['doch'] }),

  // ---------- Temporal ----------
  q.mc('tp1', 'temporal', 1, 'Es ist 9:30 Uhr. Es ist ___ .', ['halb zehn', 'halb neun', 'Viertel nach neun', 'Viertel vor zehn'], 0,
    'halb zehn = pół godziny **przed** dziesiątą = 9:30.', { tags: ['uhrzeit'] }),
  q.mc('tp2', 'temporal', 2, '___ du ins Bett gehst, putz dir die Zähne!', ['Bevor', 'Vor', 'Nachdem', 'Seit'], 0,
    'Spójnik czasowy „zanim” → **Bevor** (vor to przyimek).', { tags: ['bevor'] }),
  q.transform('tp3', 'temporal', 3, 'Vor dem Frühstück gehe ich joggen. → Bevor ___', ['ich frühstücke, gehe ich joggen.'],
    'vor + Dat ↔ bevor + zdanie podrzędne; potem inwersja.', { hint: 'bevor', tags: ['bevor'], stage: ['wojewodzki'] }),
  q.mc('tp4', 'temporal', 2, '___ er in Wien wohnt, geht er oft in die Oper.', ['Seit', 'Seid', 'Bevor', 'Als'], 0,
    'Od kiedy (i trwa nadal) → **Seit** (spójnik).', { tags: ['seit'] }),
  q.input('tp5', 'temporal', 2, 'Es ist 7:45 Uhr. Es ist Viertel ___ acht.', ['vor'],
    '7:45 = kwadrans **przed** ósmą: Viertel vor acht.', { tags: ['uhrzeit'] }),

  // ---------- Genitiv ----------
  q.mc('gn1', 'genitiv', 2, 'Die Residenz ___ Fürstbischofs in Würzburg ist barock.', ['des', 'der', 'dem', 'den'], 0,
    'Genitiv maskulin: **des** Fürstbischofs.', { tags: ['genitiv'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('gn2', 'genitiv', 3, 'Wegen des starken ___ (der Regen) wurde der Ausflug abgesagt.', ['Regens'],
    'Genitiv maskulin: des Regen**s**.', { tags: ['genitiv'], stage: ['rejonowy', 'wojewodzki'] }),
  q.mc('gn3', 'genitiv', 3, 'Das ist das Schloss ___ Königs Ludwig II.', ['des', 'der', 'dem', 'von dem'], 0,
    'Genitiv: das Schloss **des** Königs.', { tags: ['genitiv'], stage: ['rejonowy', 'wojewodzki'] }),
]
