import type { Question } from '../../types'
import { BUNDESLAENDER, OESTERREICH_LAENDER } from '../dach'
import { mkFactory, SRC } from './helpers'

const q = mkFactory({ category: 'landeskunde', source: SRC.lk, idPrefix: 'lk' })

const handcrafted: Question[] = [
  // ----- Deutschland -----
  q.mc('de1', 'lk-deutschland', 1, 'Wie heißt der höchste Berg Deutschlands?', ['die Zugspitze', 'der Brocken', 'der Watzmann', 'der Feldberg'], 0,
    'Zugspitze, 2962 m, w Alpach Wetterstein (Bawaria). Brocken (1141 m) to najwyższy szczyt Harzu.', { tags: ['geo-de'] }),
  q.mc('de2', 'lk-deutschland', 1, 'Welche ist die größte Insel Deutschlands?', ['Rügen', 'Sylt', 'Usedom', 'Helgoland'], 0,
    'Rügen (Ostsee, Meklemburgia-Pomorze Przednie).', { tags: ['geo-de'] }),
  q.mc('de3', 'lk-deutschland', 1, 'An welchem Fluss liegt Berlin?', ['an der Spree', 'an der Elbe', 'am Rhein', 'an der Donau'], 0,
    'Berlin leży nad Sprewą (i Hawelą).', { tags: ['geo-de', 'fluesse'] }),
  q.mc('de4', 'lk-deutschland', 1, 'Wie viele Bundesländer hat Deutschland?', ['16', '9', '26', '12'], 0,
    'Niemcy: 16 krajów związkowych; Austria: 9; Szwajcaria: 26 kantonów.', { tags: ['zahlen'] }),
  q.mc('de5', 'lk-deutschland', 2, 'Welches ist flächenmäßig das größte Bundesland?', ['Bayern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Baden-Württemberg'], 0,
    'Bayern - największy powierzchniowo; najludniejszy: Nadrenia Północna-Westfalia.', { tags: ['geo-de'] }),
  q.mc('de6', 'lk-deutschland', 2, 'Welches Bundesland hat die meisten Einwohner?', ['Nordrhein-Westfalen', 'Bayern', 'Berlin', 'Baden-Württemberg'], 0,
    'NRW - ok. 18 mln mieszkańców.', { tags: ['geo-de'] }),
  q.multi('de7', 'lk-deutschland', 2, 'Welche Bundesländer sind Stadtstaaten?', ['Berlin', 'Hamburg', 'Bremen', 'München', 'Saarland'], [0, 1, 2],
    'Trzy miasta-landy: Berlin, Hamburg, Brema. Monachium to stolica Bawarii.', { tags: ['geo-de', 'stadtstaaten'] }),
  q.mc('de8', 'lk-deutschland', 2, 'Welches ist die Hauptstadt von Hessen?', ['Wiesbaden', 'Frankfurt am Main', 'Kassel', 'Darmstadt'], 0,
    'Pułapka: Frankfurt jest największy, ale stolicą Hesji jest Wiesbaden.', { tags: ['hauptstaedte'] }),
  q.mc('de9', 'lk-deutschland', 2, 'Welcher große See liegt an der Grenze von Deutschland, Österreich und der Schweiz?', ['der Bodensee', 'der Chiemsee', 'die Müritz', 'der Starnberger See'], 0,
    'Jezioro Bodeńskie (Bodensee).', { tags: ['geo-de', 'seen'] }),
  q.mc('de10', 'lk-deutschland', 2, 'Wie viele Nachbarländer hat Deutschland?', ['9', '7', '8', '10'], 0,
    'Dania, Polska, Czechy, Austria, Szwajcaria, Francja, Luksemburg, Belgia, Holandia = 9.', { tags: ['zahlen'] }),
  q.mc('de11', 'lk-deutschland', 3, 'Welches Mittelgebirge liegt im Südwesten Deutschlands und ist für Kuckucksuhren bekannt?', ['der Schwarzwald', 'der Harz', 'das Erzgebirge', 'der Thüringer Wald'], 0,
    'Schwarzwald (Badenia-Wirtembergia) - zegary z kukułką, tort szwarcwaldzki.', { tags: ['geo-de'] }),
  q.mc('de12', 'lk-deutschland', 2, 'Welche Stadt nennt man „Elbflorenz“?', ['Dresden', 'Hamburg', 'Magdeburg', 'Leipzig'], 0,
    'Drezno nad Łabą - ze względu na barokową architekturę.', { tags: ['staedte'] }),
  q.mc('de13', 'lk-deutschland', 3, 'In welcher Stadt steht die Elbphilharmonie?', ['in Hamburg', 'in Dresden', 'in Berlin', 'in Bremen'], 0,
    'Elbphilharmonie - sala koncertowa w HafenCity w Hamburgu (otwarta 2017).', { tags: ['staedte', 'bauwerke'] }),
  q.input('de14', 'lk-deutschland', 3, 'Wie heißt die Landeshauptstadt von Sachsen-Anhalt?', ['Magdeburg'],
    'Magdeburg nad Łabą.', { prompt: 'Odpowiedz po niemiecku (pisownia nazw własnych musi być poprawna).', tags: ['hauptstaedte'] }),
  q.mc('de15', 'lk-deutschland', 2, 'Welches Tier ist das Symbol (Wappentier) Berlins?', ['der Bär', 'der Adler', 'der Löwe', 'der Hirsch'], 0,
    'Niedźwiedź - herb Berlina (Berliner Bär).', { tags: ['symbole'] }),
  q.mc('de16', 'lk-deutschland', 3, 'Welche Abkürzung steht für die deutsche Eisenbahn?', ['DB', 'ÖBB', 'SBB', 'DE'], 0,
    'DB = Deutsche Bahn; ÖBB - Austria, SBB - Szwajcaria.', { tags: ['alltag'] }),
  q.mc('de17', 'lk-deutschland', 3, 'In welchem Bundesland liegt die Insel Sylt?', ['Schleswig-Holstein', 'Niedersachsen', 'Mecklenburg-Vorpommern', 'Hamburg'], 0,
    'Sylt - najdalej na północ wysunięta wyspa Niemiec, Morze Północne, Szlezwik-Holsztyn.', { tags: ['geo-de'] }),
  q.mc('de18', 'lk-deutschland', 2, 'Das bekannteste Wahrzeichen Berlins ist ...', ['das Brandenburger Tor', 'der Kölner Dom', 'die Frauenkirche', 'das Holstentor'], 0,
    'Brama Brandenburska - symbol zjednoczenia Niemiec. Holstentor stoi w Lubece.', { tags: ['bauwerke'] }),

  // ----- Österreich -----
  q.mc('at1', 'lk-oesterreich', 1, 'Wie viele Bundesländer hat Österreich?', ['9', '16', '26', '8'], 0,
    'Austria ma 9 krajów związkowych.', { tags: ['zahlen'] }),
  q.mc('at2', 'lk-oesterreich', 1, 'An welchem Fluss liegt Wien?', ['an der Donau', 'am Inn', 'an der Salzach', 'am Rhein'], 0,
    'Wiedeń leży nad Dunajem.', { tags: ['fluesse'] }),
  q.mc('at3', 'lk-oesterreich', 2, 'Wie heißt der höchste Berg Österreichs?', ['der Großglockner', 'die Zugspitze', 'das Matterhorn', 'der Dachstein'], 0,
    'Großglockner, 3798 m.', { tags: ['geo-at'] }),
  q.mc('at4', 'lk-oesterreich', 1, 'In welchem Land wurde die Mozartkugel erfunden?', ['in Österreich', 'in Deutschland', 'in der Schweiz', 'in Liechtenstein'], 0,
    'Mozartkugel - Salzburg (cukiernik Paul Fürst, 1890).', { tags: ['kulinarik'] }),
  q.mc('at5', 'lk-oesterreich', 2, 'In welcher Stadt wurde Wolfgang Amadeus Mozart geboren?', ['Salzburg', 'Wien', 'Linz', 'Innsbruck'], 0,
    'Mozart urodził się w Salzburgu w 1756 r., zmarł w Wiedniu w 1791 r.', { tags: ['personen'] }),
  q.mc('at6', 'lk-oesterreich', 2, 'Wie heißt die berühmte Kathedrale im Zentrum Wiens?', ['der Stephansdom', 'der Kölner Dom', 'die Frauenkirche', 'das Münster'], 0,
    'Stephansdom (katedra św. Szczepana), „Steffl”.', { tags: ['bauwerke'] }),
  q.mc('at7', 'lk-oesterreich', 2, 'Welches Schloss war die Sommerresidenz der Habsburger in Wien?', ['Schönbrunn', 'Sanssouci', 'Neuschwanstein', 'Linderhof'], 0,
    'Schönbrunn - letnia rezydencja Habsburgów (UNESCO od 1996).', { tags: ['bauwerke'] }),
  q.input('at8', 'lk-oesterreich', 3, 'Wie heißt die Landeshauptstadt von Tirol?', ['Innsbruck'],
    'Innsbruck nad rzeką Inn.', { prompt: 'Odpowiedz po niemiecku.', tags: ['hauptstaedte-at'] }),
  q.mc('at9', 'lk-oesterreich', 3, 'Seit wann ist Österreich Mitglied der Europäischen Union?', ['seit 1995', 'seit 1955', 'seit 2004', 'seit 1990'], 0,
    'Austria w UE od 1995 r.; 1955 - traktat państwowy i neutralność.', { tags: ['geschichte-at'] }),
  q.mc('at10', 'lk-oesterreich', 3, 'Welche berühmte Torte kommt aus Wien?', ['die Sachertorte', 'die Schwarzwälder Kirschtorte', 'die Linzer Torte', 'der Baumkuchen'], 0,
    'Sachertorte - Wiedeń (hotel Sacher). Uwaga: Linzer Torte też jest austriacka, ale z Linzu.', { tags: ['kulinarik'] }),

  // ----- Schweiz -----
  q.mc('ch1', 'lk-schweiz', 1, 'Wie lautet der offizielle Name der Schweiz?', ['Schweizerische Eidgenossenschaft', 'Bundesrepublik Schweiz', 'Königreich Schweiz', 'Republik Helvetien'], 0,
    'Schweizerische Eidgenossenschaft (łac. Confoederatio Helvetica → skrót CH).', { tags: ['name-ch'] }),
  q.mc('ch2', 'lk-schweiz', 1, 'Wie viele Kantone hat die Schweiz?', ['26', '16', '9', '20'], 0,
    'Szwajcaria: 26 kantonów.', { tags: ['zahlen'] }),
  q.multi('ch3', 'lk-schweiz', 2, 'Welche Sprachen sind Amtssprachen der Schweiz?', ['Deutsch', 'Französisch', 'Italienisch', 'Rätoromanisch', 'Englisch'], [0, 1, 2, 3],
    'Cztery języki urzędowe: niemiecki, francuski, włoski, retoromański.', { tags: ['sprachen'] }),
  q.mc('ch4', 'lk-schweiz', 2, 'Welches Gericht aus geschmolzenem Käse gilt als typisch schweizerisch?', ['das Käsefondue', 'die Käsespätzle', 'der Flammkuchen', 'die Pizza'], 0,
    'Fondue serowe (także raclette).', { tags: ['kulinarik'] }),
  q.mc('ch5', 'lk-schweiz', 2, 'Wie heißt die Bundesstadt der Schweiz?', ['Bern', 'Zürich', 'Genf', 'Basel'], 0,
    'Bern - „Bundesstadt”. Zurych to największe miasto.', { tags: ['hauptstaedte-ch'] }),
  q.mc('ch6', 'lk-schweiz', 2, 'Welche Währung hat die Schweiz?', ['den Schweizer Franken', 'den Euro', 'die Schweizer Mark', 'den Schilling'], 0,
    'Frank szwajcarski (CHF). Szwajcaria nie jest w UE.', { tags: ['alltag'] }),
  q.mc('ch7', 'lk-schweiz', 3, 'Welcher Held soll mit seiner Armbrust einen Apfel vom Kopf seines Sohnes geschossen haben?', ['Wilhelm Tell', 'Siegfried', 'Robin Hood', 'Till Eulenspiegel'], 0,
    'Wilhelm Tell - legendarny bohater Szwajcarii; dramat Schillera (1804).', { tags: ['personen', 'legenden'] }),
  q.mc('ch8', 'lk-schweiz', 3, 'Wann feiert die Schweiz ihren Nationalfeiertag?', ['am 1. August', 'am 3. Oktober', 'am 26. Oktober', 'am 1. Mai'], 0,
    '1 sierpnia (przysięga na łące Rütli, 1291). 3.10 - Niemcy, 26.10 - Austria.', { tags: ['feiertage'] }),
  q.mc('ch9', 'lk-schweiz', 3, 'Wie heißt die Hauptstadt von Liechtenstein?', ['Vaduz', 'Bern', 'Bregenz', 'Chur'], 0,
    'Vaduz - stolica Księstwa Liechtensteinu.', { tags: ['liechtenstein'] }),
  q.mc('ch10', 'lk-schweiz', 3, 'Welcher bekannte Berg mit markanter Pyramidenform liegt bei Zermatt?', ['das Matterhorn', 'der Eiger', 'der Großglockner', 'der Säntis'], 0,
    'Matterhorn (4478 m) - symbol Szwajcarii.', { tags: ['geo-ch'] }),

  // ----- Geschichte -----
  q.mc('ge1', 'lk-geschichte', 1, 'In welchem Jahr wurde Deutschland wiedervereinigt?', ['1990', '1989', '1949', '1961'], 0,
    '3 października 1990. Mur berliński upadł 9 listopada 1989.', { tags: ['einheit'] }),
  q.mc('ge2', 'lk-geschichte', 2, 'Wann fiel die Berliner Mauer?', ['am 9. November 1989', 'am 3. Oktober 1990', 'am 13. August 1961', 'am 1. September 1939'], 0,
    '9.11.1989 - upadek muru. 13.08.1961 - budowa muru.', { tags: ['einheit'] }),
  q.mc('ge3', 'lk-geschichte', 2, 'Was bedeutet die Abkürzung DDR?', ['Deutsche Demokratische Republik', 'Deutsche Demokratische Regierung', 'Demokratisches Deutsches Reich', 'Deutsches Demokratisches Reich'], 0,
    'DDR = Deutsche Demokratische Republik (NRD, 1949-1990).', { tags: ['ddr'] }),
  q.mc('ge4', 'lk-geschichte', 2, 'Wer veröffentlichte 1517 in Wittenberg seine 95 Thesen?', ['Martin Luther', 'Johannes Gutenberg', 'Karl der Große', 'Friedrich Schiller'], 0,
    'Marcin Luter - początek reformacji (1517).', { tags: ['reformation', 'personen'] }),
  q.mc('ge5', 'lk-geschichte', 2, 'Wer erfand in Mainz den Buchdruck mit beweglichen Lettern?', ['Johannes Gutenberg', 'Albert Einstein', 'Carl Benz', 'Wilhelm Röntgen'], 0,
    'Johannes Gutenberg, ok. 1450, Moguncja.', { tags: ['erfindungen', 'personen'] }),
  q.mc('ge6', 'lk-geschichte', 3, 'Welcher Herrscher wurde im Jahr 800 zum Kaiser gekrönt und liegt im Aachener Dom begraben?', ['Karl der Große', 'Otto der Große', 'Friedrich Barbarossa', 'Ludwig II.'], 0,
    'Karol Wielki - koronowany w Rzymie w 800 r., pochowany w Akwizgranie.', { tags: ['mittelalter', 'personen'] }),
  q.mc('ge7', 'lk-geschichte', 3, 'Welcher deutsche Bundeskanzler kniete 1970 vor dem Denkmal der Helden des Warschauer Ghettos nieder?', ['Willy Brandt', 'Konrad Adenauer', 'Helmut Kohl', 'Helmut Schmidt'], 0,
    'Willy Brandt, 7 grudnia 1970 (Kniefall von Warschau); Pokojowa Nagroda Nobla 1971.', { tags: ['personen', 'polen'] }),
  q.mc('ge8', 'lk-geschichte', 3, 'Welche Stadt war von 1949 bis 1990 Hauptstadt der Bundesrepublik Deutschland (BRD)?', ['Bonn', 'Berlin', 'Frankfurt am Main', 'Köln'], 0,
    'Bonn - stolica RFN (Berlin Wschodni był stolicą NRD).', { tags: ['brd'] }),
  q.input('ge9', 'lk-geschichte', 3, 'Wie heißt der deutsche Nationalfeiertag am 3. Oktober? Tag der ___ ___', ['Deutschen Einheit'],
    'Tag der Deutschen Einheit (Dzień Jedności Niemiec).', { prompt: 'Uzupełnij (pisownia ma znaczenie).', tags: ['einheit', 'feiertage'] }),
  q.mc('ge10', 'lk-geschichte', 3, 'Auf welcher Burg übersetzte Martin Luther das Neue Testament ins Deutsche?', ['auf der Wartburg', 'auf der Burg Hohenzollern', 'auf der Kaiserburg Nürnberg', 'auf Burg Eltz'], 0,
    'Wartburg koło Eisenach (1521/22) - także obiekt UNESCO.', { tags: ['reformation', 'unesco-link'] }),

  // ----- Kultur & Persönlichkeiten -----
  q.mc('ku1', 'lk-kultur', 1, 'Wer schrieb „Faust“?', ['Johann Wolfgang von Goethe', 'Friedrich Schiller', 'Thomas Mann', 'Heinrich Heine'], 0,
    'Goethe - „Faust” (cz. I 1808). Mieszkał w Weimarze.', { tags: ['literatur'] }),
  q.mc('ku2', 'lk-kultur', 2, 'Wer war KEIN Komponist?', ['Friedrich Schiller', 'Johann Sebastian Bach', 'Richard Wagner', 'Ludwig van Beethoven'], 0,
    'Schiller był poetą i dramatopisarzem (m.in. „Oda do radości”, do której muzykę napisał Beethoven).', { tags: ['musik'] }),
  q.mc('ku3', 'lk-kultur', 2, 'Wie heißen die Brüder, die berühmte Märchen wie „Hänsel und Gretel“ sammelten?', ['die Brüder Grimm', 'die Brüder Mann', 'die Brüder Humboldt', 'die Brüder Wright'], 0,
    'Jacob i Wilhelm Grimm.', { tags: ['literatur'] }),
  q.mc('ku4', 'lk-kultur', 2, 'In welcher Stadt wurde Ludwig van Beethoven geboren?', ['Bonn', 'Wien', 'Salzburg', 'Leipzig'], 0,
    'Beethoven urodził się w Bonn (1770), zmarł w Wiedniu (1827).', { tags: ['musik'] }),
  q.mc('ku5', 'lk-kultur', 2, 'In welcher Stadt findet jedes Jahr das Oktoberfest statt?', ['München', 'Köln', 'Berlin', 'Stuttgart'], 0,
    'Oktoberfest - Monachium, rozpoczyna się we wrześniu.', { tags: ['feste'] }),
  q.mc('ku6', 'lk-kultur', 3, 'Welcher Physiker erhielt 1901 den ersten Nobelpreis für Physik für die Entdeckung der X-Strahlen?', ['Wilhelm Conrad Röntgen', 'Albert Einstein', 'Max Planck', 'Otto Hahn'], 0,
    'Wilhelm Conrad Röntgen - promienie X (Röntgenstrahlen).', { tags: ['nobel', 'personen'] }),
  q.mc('ku7', 'lk-kultur', 3, 'In welcher Stadt wurde Albert Einstein geboren?', ['Ulm', 'Berlin', 'München', 'Bern'], 0,
    'Einstein urodził się w Ulm (1879); teorię względności rozwijał m.in. w Bernie.', { tags: ['personen'] }),
  q.mc('ku8', 'lk-kultur', 3, 'Welche Figur steht als Symbol für Freiheit auf dem Bremer Marktplatz?', ['der Roland', 'der Michel', 'die Bavaria', 'der Bär'], 0,
    'Posąg Rolanda (1404) - symbol wolności miasta; razem z ratuszem na liście UNESCO (2004).', { tags: ['symbole', 'unesco-link'] }),
  q.mc('ku9', 'lk-kultur', 2, 'Welche Tiere sind die „Bremer Stadtmusikanten“?', ['Esel, Hund, Katze und Hahn', 'Pferd, Kuh, Schaf und Ziege', 'Bär, Wolf, Fuchs und Hase', 'Hund, Katze, Maus und Vogel'], 0,
    'Osioł, pies, kot i kogut - baśń braci Grimm.', { tags: ['maerchen'] }),
  q.mc('ku10', 'lk-kultur', 3, 'Wo wohnte Johann Wolfgang von Goethe den größten Teil seines Lebens?', ['in Weimar', 'in Frankfurt am Main', 'in Leipzig', 'in Berlin'], 0,
    'Urodzony we Frankfurcie (1749), od 1775 w Weimarze (Klassisches Weimar - UNESCO).', { tags: ['literatur', 'unesco-link'] }),
  q.mc('ku11', 'lk-kultur', 3, 'Welches Porzellan ist das älteste in Europa und kommt aus Sachsen?', ['Meißner Porzellan', 'Rosenthal', 'Wiener Porzellan', 'Villeroy & Boch'], 0,
    'Manufaktura w Miśni (od 1710) - skrzyżowane miecze.', { tags: ['kultur-de'] }),
  q.mc('ku12', 'lk-kultur', 3, 'In welcher Stadt ist Johann Sebastian Bach Thomaskantor gewesen?', ['Leipzig', 'Dresden', 'Eisenach', 'Weimar'], 0,
    'Bach był kantorem w kościele św. Tomasza w Lipsku (1723-1750); urodził się w Eisenach.', { tags: ['musik'] }),
  q.mc('ku13', 'lk-kultur', 3, 'Welcher Komponist gründete die Festspiele in Bayreuth?', ['Richard Wagner', 'Richard Strauss', 'Johann Strauss', 'Carl Orff'], 0,
    'Richard Wagner - Bayreuther Festspiele (od 1876).', { tags: ['musik'] }),
  q.mc('ku14', 'lk-kultur', 2, 'Wo findet der bekannteste Karneval Deutschlands statt?', ['in Köln', 'in Hamburg', 'in Dresden', 'in Kiel'], 0,
    'Kolonia (i Nadrenia) - Karneval; „Kölle Alaaf!”.', { tags: ['feste'] }),
  q.mc('ku15', 'lk-kultur', 3, 'Wie heißt der berühmte Weihnachtsmarkt in Nürnberg?', ['Christkindlesmarkt', 'Striezelmarkt', 'Wintermarkt', 'Adventsmarkt'], 0,
    'Christkindlesmarkt - Norymberga. Striezelmarkt - Drezno (najstarszy).', { tags: ['feste'] }),
]

// Generowane z danych: stolice krajów związkowych (typowe pytanie otwarte etapu rejonowego)
const capitalsDE: Question[] = BUNDESLAENDER.filter((b) => b.name !== b.capital).map((b, i) =>
  q.input(`cap-de-${i}`, 'lk-deutschland', b.name === 'Hessen' || b.name === 'Nordrhein-Westfalen' ? 3 : 2,
    `Wie heißt die Landeshauptstadt von ${b.name}?`, [b.capital],
    `${b.name} → **${b.capital}**. ${b.note}.`,
    { prompt: 'Odpowiedz po niemiecku (pełna poprawność pisowni).', tags: ['hauptstaedte'] }),
)
const capitalsAT: Question[] = OESTERREICH_LAENDER.filter((b) => b.name !== b.capital).map((b, i) =>
  q.input(`cap-at-${i}`, 'lk-oesterreich', 3, `Wie heißt die Landeshauptstadt von ${b.name}?`, [b.capital, b.capital.replace('St.', 'Sankt')],
    `${b.name} → **${b.capital}**. ${b.note}.`,
    { prompt: 'Odpowiedz po niemiecku (pełna poprawność pisowni).', tags: ['hauptstaedte-at'] }),
)

export const LANDESKUNDE_QUESTIONS: Question[] = [...handcrafted, ...capitalsDE, ...capitalsAT]
