import type { Question } from '../../types'
import { mkFactory, SRC } from './helpers'

const q = mkFactory({ category: 'reaktionen', source: SRC.reakcje, idPrefix: 'sr', stage: ['szkolny', 'rejonowy'] })
const T = 'reaktionen-alltag'

export const REACTION_QUESTIONS: Question[] = [
  q.reaction('r1', T, 1, 'Ciocia proponuje ci kolejny kawałek ciasta, ale już nie jesteś głodny. Co mówisz?',
    ['Nein danke, ich bin schon satt.', 'Nein, der Kuchen schmeckt mir nicht.', 'Ja, gern, noch ein Stück bitte.'], 0,
    'Uprzejma odmowa: „ich bin schon satt”. Druga opcja jest niegrzeczna, trzecia to zgoda.', { tags: ['ablehnen'] }),
  q.reaction('r2', T, 1, 'Twój kolega nie zdał ważnego testu. Jak go pocieszysz?',
    ['Kopf hoch! Beim nächsten Mal klappt es bestimmt.', 'Herzlichen Glückwunsch!', 'Das ist mir egal.'], 0,
    'Współczucie/pocieszenie: „Kopf hoch!”, „Das tut mir leid”.', { tags: ['mitgefuehl'] }),
  q.reaction('r3', T, 2, 'Nie wiesz, czy pojechać na wakacje nad morze, czy w góry. Prosisz przyjaciółkę o radę.',
    ['Was würdest du mir empfehlen?', 'Ich empfehle dir das Meer.', 'Wohin fährst du in den Ferien?'], 0,
    'Prośba o radę: „Was würdest du mir empfehlen?”. Opcja 2 to udzielanie rady, 3 - pytanie o jej plany.', { tags: ['rat-fragen'] }),
  q.reaction('r4', T, 1, 'Nie zrozumiałeś, co powiedziała pani w informacji na dworcu.',
    ['Könnten Sie das bitte wiederholen?', 'Was hast du gesagt?', 'Sprich lauter!'], 0,
    'Obca osoba dorosła → forma **Sie** + uprzejmy Konjunktiv II.', { tags: ['nachfragen', 'register'] }),
  q.reaction('r5', T, 2, 'Kolega zaprasza cię do kina w sobotę, ale masz już inne plany.',
    ['Schade, am Samstag kann ich leider nicht. Vielleicht nächste Woche?', 'Ich gehe nie ins Kino.', 'Toll, ich komme gern!'], 0,
    'Uprzejma odmowa z propozycją alternatywy.', { tags: ['ablehnen'] }),
  q.reaction('r6', T, 2, 'Kolega mówi: „Ich habe die Prüfung mit einer Eins bestanden!” Reagujesz:',
    ['Super, herzlichen Glückwunsch!', 'Gute Besserung!', 'Das tut mir leid.'], 0,
    'Gratulacje. „Gute Besserung” = życzenie zdrowia.', { tags: ['gratulieren'] }),
  q.reaction('r7', T, 2, 'Przyjaciel jest chory i leży w łóżku. Na koniec rozmowy mówisz:',
    ['Gute Besserung!', 'Viel Spaß!', 'Guten Appetit!'], 0,
    'Chory → **Gute Besserung!**', { tags: ['wuensche'] }),
  q.reaction('r8', T, 2, 'Pytasz przechodnia w Wiedniu o drogę do katedry św. Szczepana.',
    ['Entschuldigung, wie komme ich zum Stephansdom?', 'Hey, wo ist der Dom?', 'Wann ist der Stephansdom?'], 0,
    'Obcy → forma uprzejma „Entschuldigung, wie komme ich zu...?”.', { tags: ['weg-fragen'] }),
  q.reaction('r9', T, 2, 'Kolega twierdzi, że matematyka to najnudniejszy przedmiot. Masz inne zdanie.',
    ['Das sehe ich anders. Mathe finde ich spannend.', 'Da hast du völlig recht.', 'Ich weiß nicht, was Mathe ist.'], 0,
    'Wyrażenie niezgody: „Das sehe ich anders.” / „Da bin ich anderer Meinung.”', { tags: ['meinung'] }),
  q.reaction('r10', T, 2, 'Dowiadujesz się, że twój ulubiony zespół zagra koncert w twoim mieście. Wyrażasz radość.',
    ['Wie toll! Da muss ich unbedingt hin!', 'Wie schade!', 'Na und?'], 0,
    'Radość/entuzjazm.', { tags: ['freude'] }),
  q.reaction('r11', T, 3, 'Spóźniłeś się na lekcję. Wchodzisz do klasy i mówisz do nauczyciela:',
    ['Entschuldigen Sie bitte die Verspätung. Mein Bus hatte Verspätung.', 'Hallo, ich bin da!', 'Tschüs, bis morgen!'], 0,
    'Przeprosiny w formie **Sie** z wyjaśnieniem.', { tags: ['entschuldigen', 'register'] }),
  q.reaction('r12', T, 3, 'W sklepie chcesz zwrócić za małą bluzę.',
    ['Kann ich diesen Pullover umtauschen? Er ist mir zu klein.', 'Ich möchte diesen Pullover kaufen.', 'Wo ist die Umkleidekabine?'], 0,
    'Wymiana/zwrot: „umtauschen” / „zurückgeben”.', { tags: ['einkaufen'] }),
  q.reaction('r13', T, 2, 'Siostra ma zaraz ważny występ i bardzo się stresuje. Dodajesz jej otuchy.',
    ['Du schaffst das! Ich drücke dir die Daumen.', 'Das wird bestimmt schlecht.', 'Warum bist du so nervös?'], 0,
    '„Ich drücke dir die Daumen” = trzymam kciuki.', { tags: ['ermutigen'] }),
  q.reaction('r14', T, 3, 'W muzeum ktoś robi zdjęcia z lampą błyskową. Jesteś pracownikiem muzeum.',
    ['Entschuldigung, hier darf man nicht mit Blitz fotografieren.', 'Sie müssen hier fotografieren.', 'Machen Sie bitte ein Foto von mir.'], 0,
    'Zakaz: „hier darf man nicht...”.', { tags: ['verbot'] }),
  q.reaction('r15', T, 2, 'Przyjaciel opowiada ci niewiarygodną historię. Jesteś zdziwiony.',
    ['Echt? Das gibt es doch nicht!', 'Das weiß ich schon.', 'Das ist langweilig.'], 0,
    'Zdziwienie: „Echt?”, „Wirklich?”, „Das gibt es doch nicht!”.', { tags: ['erstaunen'] }),
  q.reaction('r16', T, 3, 'Chcesz wymienić złotówki na euro w kantorze.',
    ['Ich möchte bitte Złoty in Euro wechseln.', 'Ich möchte bitte Euro bezahlen.', 'Wo kann ich Geld verdienen?'], 0,
    'Wymiana pieniędzy = Geld **wechseln** / **umtauschen**.', { tags: ['geld'] }),
  q.reaction('r17', T, 3, 'Twój pociąg ma opóźnienie i nie zdążysz na przesiadkę. Pytasz konduktora:',
    ['Erreiche ich meinen Anschlusszug nach München noch?', 'Wann fährt der Zug ab?', 'Wo ist der Speisewagen?'], 0,
    'Przesiadka = der **Anschluss** / Anschlusszug.', { tags: ['reisen'] }),
  q.reaction('r18', T, 2, 'Gość dziękuje ci za pomoc. Odpowiadasz:',
    ['Gern geschehen!', 'Bitte schön, was darf es sein?', 'Danke, gleichfalls!'], 0,
    'Odpowiedź na „Danke”: **Gern geschehen!** / Bitte!', { tags: ['danken'] }),
  q.reaction('r19', T, 3, 'Ktoś życzy ci „Schöne Feiertage!”. Odpowiadasz:',
    ['Danke, gleichfalls!', 'Gern geschehen!', 'Gute Besserung!'], 0,
    'Odwzajemnienie życzeń: **Danke, gleichfalls!**', { tags: ['wuensche'] }),
  q.reaction('r20', T, 3, 'Twoja koleżanka pyta: „Hast du Lust, am Wochenende mit uns wandern zu gehen?” Zgadzasz się.',
    ['Klar, gern! Wann treffen wir uns?', 'Nein, ich habe keine Zeit.', 'Ich war schon wandern.'], 0,
    'Przyjęcie zaproszenia + pytanie o szczegóły.', { tags: ['zustimmen'] }),
  q.reaction('r21', T, 3, 'Chcesz uprzejmie poprosić obcą osobę w pociągu, żeby przesunęła swoją torbę z wolnego miejsca.',
    ['Entschuldigung, ist hier noch frei? Könnten Sie bitte Ihre Tasche wegnehmen?', 'Nimm deine Tasche weg!', 'Das ist meine Tasche.'], 0,
    'Obca osoba → Sie + Konjunktiv II.', { tags: ['bitten', 'register'] }),
  q.reaction('r22', T, 2, 'Kolega z przyjemnością je obiad. Wchodzisz do kuchni i mówisz:',
    ['Guten Appetit!', 'Prost!', 'Gesundheit!'], 0,
    'Przy jedzeniu: **Guten Appetit!** (Prost - toast, Gesundheit - po kichnięciu).', { tags: ['wuensche'] }),
  q.reaction('r23', T, 3, 'Twój kolega proponuje: „Wollen wir morgen ins Schwimmbad gehen?” Nie jesteś pewien.',
    ['Mal sehen, ich sage dir morgen früh Bescheid.', 'Ja, gestern war ich schon da.', 'Das Schwimmbad ist groß.'], 0,
    'Niezdecydowanie: „Mal sehen”, „Ich sage dir Bescheid”.', { tags: ['unsicher'] }),
  q.reaction('r24', T, 3, 'W restauracji chcesz zapłacić.',
    ['Wir möchten bitte zahlen.', 'Ich möchte bitte bestellen.', 'Die Speisekarte, bitte.'], 0,
    'Rachunek: „Zahlen, bitte!” / „Wir möchten bitte zahlen.”', { tags: ['restaurant'] }),
  q.reaction('r25', T, 3, 'Znajomy mówi: „Ich habe mir das Bein gebrochen.” Reagujesz:',
    ['Oh nein, das tut mir leid! Gute Besserung!', 'Toll, das freut mich!', 'Macht nichts.'], 0,
    'Współczucie + życzenie zdrowia.', { tags: ['mitgefuehl'] }),
  q.reaction('r26', T, 3, 'Chcesz zaproponować koledze, żeby zrobili razem projekt o Wiedniu.',
    ['Wie wäre es, wenn wir das Projekt über Wien zusammen machen?', 'Hast du das Projekt schon gemacht?', 'Wien ist die Hauptstadt von Österreich.'], 0,
    'Propozycja: „Wie wäre es, wenn...?” / „Wollen wir...?”', { tags: ['vorschlagen'] }),
  q.reaction('r27', T, 2, 'Kichnąłeś, a kolega mówi „Gesundheit!”. Odpowiadasz:',
    ['Danke!', 'Bitte!', 'Gleichfalls!'], 0,
    'Na „Gesundheit!” odpowiadamy „Danke!”.', { tags: ['wuensche'] }),
  q.reaction('r28', T, 3, 'Przyjaciółka pyta, który prezent wybrać dla mamy. Radzisz jej:',
    ['An deiner Stelle würde ich ihr Blumen schenken.', 'Ich habe meiner Mutter ein Buch geschenkt.', 'Deine Mutter hat bald Geburtstag.'], 0,
    'Rada: „An deiner Stelle würde ich...”', { tags: ['rat-geben'] }),
  q.reaction('r29', T, 3, 'W hotelu recepcjonistka pyta: „Wie lange bleiben Sie?” Odpowiadasz:',
    ['Drei Nächte, bis Sonntag.', 'Seit drei Tagen.', 'Um drei Uhr.'], 0,
    '„Wie lange?” pyta o czas trwania. „Seit drei Tagen” = od trzech dni (przeszłość).', { tags: ['reisen', 'fragewort'] }),
  q.reaction('r30', T, 3, 'Kolega zgubił twoją książkę i przeprasza. Nie gniewasz się.',
    ['Kein Problem, das kann jedem passieren.', 'Das ist eine Katastrophe!', 'Ich bin sehr böse auf dich.'], 0,
    'Przyjęcie przeprosin: „Kein Problem”, „Macht nichts”, „Schon gut”.', { tags: ['entschuldigung-annehmen'] }),
]
