import type { Question } from '../../types'
import { mkFactory, SRC } from './helpers'

const q = mkFactory({ category: 'wortschatz', source: SRC.lexgram, idPrefix: 'ws' })
const ANT = 'Napisz antonim podkreślonego wyrazu w poprawnej formie (pełna poprawność gramatyczna i ortograficzna).'

export const VOCAB_QUESTIONS: Question[] = [
  // ---------- Antonyme (zad. 6 szkolny) ----------
  q.input('an1', 'antonyme', 1, 'Das ist ein sehr [teures] Handy. → Das ist ein sehr ___ Handy.', ['billiges', 'günstiges'],
    'teuer ↔ billig/günstig; końcówka -es musi zostać (ein + neutrum).', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an2', 'antonyme', 1, 'Mach bitte das Fenster [auf]! → Mach bitte das Fenster ___!', ['zu'],
    'aufmachen ↔ zumachen - zmienia się tylko przedrostek.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-trennbar'] }),
  q.input('an3', 'antonyme', 2, 'Der Unterricht [endet] um 14 Uhr. → Der Unterricht ___ um 14 Uhr.', ['beginnt', 'fängt an'],
    'enden ↔ beginnen/anfangen - forma 3. os. l.poj.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-verb'] }),
  q.input('an4', 'antonyme', 2, 'Es ist [Viertel vor] zehn. → Es ist ___ zehn.', ['Viertel nach'],
    'Viertel vor ↔ Viertel nach.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-zeit'] }),
  q.input('an5', 'antonyme', 2, 'Kannst du bitte den Fernseher [einschalten]? → Kannst du bitte den Fernseher ___?', ['ausschalten', 'ausmachen'],
    'einschalten ↔ ausschalten.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-trennbar'] }),
  q.input('an6', 'antonyme', 2, 'Steig hier [aus]! → Steig hier ___!', ['ein'],
    'aussteigen ↔ einsteigen: Steig ... ein!', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-trennbar'] }),
  q.input('an7', 'antonyme', 2, 'Unser Team hat das Spiel [gewonnen]. → Unser Team hat das Spiel ___.', ['verloren'],
    'gewinnen ↔ verlieren; Partizip II: verloren.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-verb'] }),
  q.input('an8', 'antonyme', 2, 'Das war ein [langweiliger] Film. → Das war ein ___ Film.', ['spannender', 'interessanter', 'lustiger'],
    'langweilig ↔ spannend/interessant; ein + maskulin Nom → -er.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an9', 'antonyme', 2, 'Im Sommer ist das Wasser im See [warm]. → Im Sommer ist das Wasser im See ___.', ['kalt', 'kühl'],
    'warm ↔ kalt.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an10', 'antonyme', 2, 'Zieh deine Jacke [aus]! → Zieh deine Jacke ___!', ['an'],
    'ausziehen ↔ anziehen.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-trennbar'] }),
  q.input('an11', 'antonyme', 3, 'Ich habe [alles] verstanden. → Ich habe ___ verstanden.', ['nichts'],
    'alles ↔ nichts.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-pron'] }),
  q.input('an12', 'antonyme', 3, 'Im Museum ist Fotografieren [erlaubt]. → Im Museum ist Fotografieren ___.', ['verboten'],
    'erlaubt ↔ verboten.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an13', 'antonyme', 3, 'Die Flasche ist schon [leer]. → Die Flasche ist noch ___.', ['voll'],
    'leer ↔ voll.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an14', 'antonyme', 3, 'Das ist eine [schwierige] Aufgabe. → Das ist eine ___ Aufgabe.', ['leichte', 'einfache'],
    'schwierig ↔ leicht/einfach; eine + feminin → -e.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an15', 'antonyme', 3, 'Er kommt [immer] zu spät. → Er kommt ___ zu spät.', ['nie', 'niemals'],
    'immer ↔ nie.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adv'] }),
  q.input('an16', 'antonyme', 3, 'Wir haben einen [hässlichen] Hund gesehen. → Wir haben einen ___ Hund gesehen.', ['schönen', 'hübschen', 'süßen'],
    'hässlich ↔ schön/hübsch; einen (Akk m) → -en.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an17', 'antonyme', 3, 'Ich stehe in der Schlange [vor] dir. → Ich stehe in der Schlange ___ dir.', ['hinter', 'nach'],
    'vor ↔ hinter (miejsce w kolejce).', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-praep'] }),
  q.input('an18', 'antonyme', 3, 'Heute bin ich sehr [früh] aufgestanden. → Heute bin ich sehr ___ aufgestanden.', ['spät'],
    'früh ↔ spät.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adv'] }),
  q.input('an19', 'antonyme', 3, 'Die Musik ist zu [laut]. → Die Musik ist zu ___.', ['leise'],
    'laut ↔ leise.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an20', 'antonyme', 3, 'Hier hat [jemand] angerufen. → Hier hat ___ angerufen.', ['niemand'],
    'jemand ↔ niemand.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-pron'] }),
  q.input('an21', 'antonyme', 2, 'Der Koffer ist sehr [schwer]. → Der Koffer ist sehr ___.', ['leicht'],
    'schwer (waga) ↔ leicht.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-adj'] }),
  q.input('an22', 'antonyme', 3, 'Ich habe meinen Schlüssel [gefunden]. → Ich habe meinen Schlüssel ___.', ['verloren'],
    'finden ↔ verlieren; Partizip: verloren.', { prompt: ANT, stage: ['szkolny'], tags: ['antonym-verb'] }),

  // ---------- Wortbildung / Wortformen (zad. 6 rejonowy) ----------
  q.input('wb1', 'wortbildung', 2, 'Die ___ (freundlich) der Menschen in Wien hat mich überrascht.', ['Freundlichkeit'],
    'freundlich + -keit → die Freundlichkeit (wielka litera!).', { prompt: 'Utwórz od wyrazu w nawiasie poprawną formę pasującą do zdania.', tags: ['nomen-bildung'] }),
  q.input('wb2', 'wortbildung', 2, 'Morgen wird es ___ (die Sonne) und warm.', ['sonnig'],
    'die Sonne → sonnig (przymiotnik na -ig).', { prompt: 'Utwórz od wyrazu w nawiasie poprawną formę pasującą do zdania.', tags: ['adj-bildung'] }),
  q.input('wb3', 'wortbildung', 3, 'Das kleine Haus heißt auf Deutsch auch das ___ .', ['Häuschen'],
    'Diminutyw: -chen + przegłos → das Häuschen.', { prompt: 'Wpisz zdrobnienie.', tags: ['diminutiv'] }),
  q.input('wb4', 'wortbildung', 3, 'Vor der Reise gibt es immer viele ___ (die Reise + die Vorbereitung, Plural).', ['Reisevorbereitungen'],
    'Kompozytum: die Reise + die Vorbereitung → die Reisevorbereitungen.', { prompt: 'Utwórz od wyrazu w nawiasie poprawną formę pasującą do zdania.', tags: ['kompositum'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('wb5', 'wortbildung', 3, 'Die Dirndl sind ___ (Kleidungsstück, Plural), die man in Bayern und Österreich trägt.', ['Kleidungsstücke'],
    'das Kleidungsstück → die Kleidungsstücke.', { prompt: 'Wpisz poprawną formę wyrazu w nawiasie.', tags: ['plural'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('wb6', 'wortbildung', 3, 'Das Wetter heute ist noch ___ (schlecht, stopień wyższy) als gestern.', ['schlechter'],
    'schlecht → schlechter.', { prompt: 'Wpisz poprawną formę wyrazu w nawiasie.', tags: ['komparativ'] }),
  q.input('wb7', 'wortbildung', 2, 'Unsere Klasse macht nächste Woche einen ___ (die Klasse + der Ausflug) nach Krakau.', ['Klassenausflug'],
    'die Klasse + -n- + der Ausflug → der Klassenausflug; einen (Akk m).', { prompt: 'Utwórz złożenie.', tags: ['kompositum'] }),
  q.input('wb8', 'wortbildung', 3, 'Neuschwanstein ist ein ___ (Märchen) Schloss. (przymiotnik z końcówką)', ['märchenhaftes'],
    'das Märchen → märchenhaft; ein + neutrum → märchenhaft**es**.', { prompt: 'Utwórz przymiotnik od wyrazu w nawiasie i dodaj końcówkę.', tags: ['adj-bildung'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('wb9', 'wortbildung', 3, 'Für Touristen ist die ___ (erreichen) des Museums sehr wichtig.', ['Erreichbarkeit'],
    'erreichen → erreichbar → die Erreichbarkeit.', { prompt: 'Utwórz rzeczownik od wyrazu w nawiasie.', tags: ['nomen-bildung'], stage: ['wojewodzki'] }),
  q.mc('wb10', 'wortbildung', 2, 'Welches Nomen ist feminin?', ['Entscheidung', 'Frühling', 'Museum', 'Mädchen'], 0,
    'Przyrostek -ung → zawsze **die**. Frühling (der), Museum (das), Mädchen (das).', { tags: ['genus-suffix'] }),
  q.mc('wb11', 'wortbildung', 2, 'Welcher Artikel passt zu „Weltkulturerbe”?', ['das', 'die', 'der', 'den'], 0,
    'Rodzaj kompozytum = ostatni człon: **das** Erbe → das Weltkulturerbe.', { tags: ['kompositum', 'genus'] }),
  q.mc('wb12', 'wortbildung', 3, 'Welcher Artikel passt zu „Bundesland”?', ['das', 'der', 'die', 'dem'], 0,
    'das Land → **das** Bundesland; Plural: die Bundesländer.', { tags: ['kompositum', 'genus'] }),

  // ---------- Kollokationen ----------
  q.mc('kl1', 'kollokationen', 2, 'Ich kann mich nicht entscheiden. Kannst du die Entscheidung für mich ___?', ['treffen', 'machen', 'tun', 'geben'], 0,
    'eine Entscheidung **treffen** (nie „machen”).', { tags: ['kollokation'] }),
  q.mc('kl2', 'kollokationen', 1, 'Darf ich Ihnen eine Frage ___?', ['stellen', 'fragen', 'machen', 'sagen'], 0,
    'eine Frage **stellen**.', { tags: ['kollokation'] }),
  q.mc('kl3', 'kollokationen', 2, 'Ich habe heute keine Lust ___ Hausaufgaben.', ['auf', 'für', 'zu', 'an'], 0,
    'Lust **auf** + Akk.', { tags: ['kollokation'] }),
  q.mc('kl4', 'kollokationen', 2, 'Sag mir bitte ___, wenn du angekommen bist.', ['Bescheid', 'Nachricht', 'Wissen', 'Info'], 0,
    'jemandem **Bescheid** sagen = dać znać.', { tags: ['kollokation'] }),
  q.mc('kl5', 'kollokationen', 3, 'Geld spielt für mich keine große ___.', ['Rolle', 'Bedeutung', 'Sache', 'Frage'], 0,
    'eine Rolle **spielen** = odgrywać rolę.', { tags: ['kollokation'] }),
  q.mc('kl6', 'kollokationen', 3, 'Leider ist Tom durch die Prüfung ___.', ['gefallen', 'gegangen', 'gekommen', 'gestanden'], 0,
    'durch die Prüfung **fallen** = oblać egzamin (Perfekt z sein: ist gefallen).', { tags: ['kollokation'] }),
  q.mc('kl7', 'kollokationen', 2, 'Bitte nehmen Sie ___!', ['Platz', 'Stuhl', 'Sitz', 'Ort'], 0,
    '**Platz nehmen** = usiąść (formalnie).', { tags: ['kollokation'] }),
  q.mc('kl8', 'kollokationen', 3, 'Unsere Lehrerin legt großen ___ auf Pünktlichkeit.', ['Wert', 'Sinn', 'Preis', 'Druck'], 0,
    '**Wert legen auf** + Akk = przykładać wagę do.', { tags: ['kollokation'] }),
  q.mc('kl9', 'kollokationen', 2, 'Für die Fahrt mit dem Zug brauchst du eine ___.', ['Fahrkarte', 'Eintrittskarte', 'Postkarte', 'Landkarte'], 0,
    'Bilet na przejazd = **die Fahrkarte**; Eintrittskarte = bilet wstępu (kino, muzeum).', { tags: ['wortfeld-reisen'] }),
  q.mc('kl10', 'kollokationen', 3, 'Die Bedeutung dieses Wortes kann ich im Wörterbuch ___.', ['nachschlagen', 'nachsehen lassen', 'aufschlagen', 'vorschlagen'], 0,
    'ein Wort **nachschlagen** = sprawdzić w słowniku. vorschlagen = zaproponować.', { tags: ['kollokation'] }),

  // ---------- Rechtschreibung / Buchstaben ergänzen (zad. 8 rejonowy) ----------
  q.input('rt1', 'rechtschreibung', 2, 'Ich weiß, ___ du morgen Geburtstag hast. (das/dass)', ['dass'],
    'Spójnik „że” → **dass**.', { prompt: 'Wpisz poprawny wyraz.', tags: ['das-dass'] }),
  q.input('rt2', 'rechtschreibung', 2, 'Das Buch, ___ auf dem Tisch liegt, gehört mir. (das/dass)', ['das'],
    'Zaimek względny (= welches) → **das**.', { prompt: 'Wpisz poprawny wyraz.', tags: ['das-dass'] }),
  q.mc('rt3', 'rechtschreibung', 2, 'Welches Wort ist richtig geschrieben?', ['die Straße', 'die Strasse', 'die Strase', 'die Sraße'], 0,
    'Po długiej samogłosce → **ß**: die Straße.', { prompt: 'Wybierz poprawną pisownię.', tags: ['ss-sz'] }),
  q.mc('rt4', 'rechtschreibung', 2, 'Welches Wort ist richtig geschrieben?', ['das Schloss', 'das Schloß', 'das Schlos', 'das Schlosß'], 0,
    'Po krótkiej samogłosce → **ss** (Schloß to stara pisownia).', { prompt: 'Wybierz poprawną pisownię.', tags: ['ss-sz'] }),
  q.input('rt5', 'rechtschreibung', 3, 'Für das Konzert brauchst du eine E _ _ _ _ _ _ _ _ karte. (bilet wstępu - wpisz całe słowo)', ['Eintrittskarte'],
    'die Eintrittskarte (der Eintritt + -s- + die Karte).', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt6', 'rechtschreibung', 3, 'Wir haben den Bus leider v _ _ _ _ _ _ t. (spóźniliśmy się na autobus - wpisz całe słowo)', ['verpasst'],
    'den Bus verpassen → verpasst (po krótkim a → ss).', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt7', 'rechtschreibung', 3, 'Die Fahrkarte ist nur heute g _ _ _ _ g. (ważny - wpisz całe słowo)', ['gültig'],
    'gültig - ważny (bilet, dokument).', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt8', 'rechtschreibung', 3, 'Am 24. Dezember feiern wir H _ _ _ _ _ _ _ _ nd. (Wigilia - wpisz całe słowo)', ['Heiligabend'],
    'der Heiligabend = Wigilia.', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben', 'feste'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt9', 'rechtschreibung', 3, 'Der Laden ist sonntags g _ _ _ _ _ _ _ _ n. (zamknięty - wpisz całe słowo)', ['geschlossen'],
    'geschlossen (Partizip od schließen): krótkie o → ss.', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben', 'ss-sz'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt10', 'rechtschreibung', 3, 'Mein Bruder und ich sehen uns sehr ä _ _ _ _ _ h. (podobni - wpisz całe słowo)', ['ähnlich'],
    'ähnlich - podobny (z h!).', { prompt: 'Uzupełnij wyraz (wpisz całe słowo).', tags: ['buchstaben'], stage: ['rejonowy', 'wojewodzki'] }),
  q.input('rt11', 'rechtschreibung', 2, 'Wir treffen uns am ___ (poniedziałek).', ['Montag'],
    'Dni tygodnia z wielkiej litery: am Montag (ale: montags).', { prompt: 'Wpisz wyraz po niemiecku.', tags: ['gross-klein'] }),
  q.mc('rt12', 'rechtschreibung', 3, 'Welche Schreibweise ist korrekt?', ['beim Lesen', 'beim lesen', 'bei dem lesen', 'Beim lesen'], 0,
    'Rzeczownik odczasownikowy → wielka litera: beim **L**esen.', { prompt: 'Wybierz poprawną pisownię.', tags: ['gross-klein'] }),
]
