import type { Topic } from '../types'

/**
 * Curriculum zbudowane na podstawie:
 * - Programu merytorycznego j. niemieckiego 2026/27 (MKO) - umiejętności i tematy etapów
 * - analizy arkuszy etapu szkolnego 2022/23-2025/26, rejonowego 2023/24-2025/26, wojewódzkiego 2025/26
 * Pole `evidence` mówi, gdzie dany temat faktycznie pojawił się w zadaniach konkursowych.
 */
export const TOPICS: Topic[] = [
  // ================= GRAMMATIK =================
  {
    id: 'verben-praepositionen',
    category: 'grammatik',
    title: 'Verben mit Präpositionen',
    titlePl: 'Czasowniki z przyimkami (rekcja)',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Co roku: zad. 3 szkolny (Worauf? Wonach?), zad. 8 wojewódzki (bitten um, abhängen von, sich freuen auf).',
    lesson: {
      intro:
        'Czasownik „wybiera” przyimek i przypadek - tego nie da się wywnioskować, trzeba to **znać na pamięć razem z przypadkiem**. Na konkursie pojawia się w trzech formach: luka z przyimkiem, pytanie **Wo(r)+przyimek** i dopasowanie pytania do odpowiedzi.',
      table: {
        head: ['Czasownik', 'Przyimek + przypadek', 'Przykład'],
        rows: [
          ['sich freuen', 'auf + Akk (przyszłość)', 'Ich freue mich auf die Ferien.'],
          ['sich freuen', 'über + Akk (teraźniejszość/przeszłość)', 'Ich freue mich über das Geschenk.'],
          ['warten', 'auf + Akk', 'Wir warten auf den Bus.'],
          ['sich interessieren', 'für + Akk', 'Er interessiert sich für Geschichte.'],
          ['denken', 'an + Akk', 'Ich denke oft an dich.'],
          ['sich erinnern', 'an + Akk', 'Erinnerst du dich an den Ausflug?'],
          ['bitten', 'um + Akk', 'Sie bittet um Hilfe.'],
          ['fragen', 'nach + Dat', 'Er fragt nach dem Weg.'],
          ['suchen', 'nach + Dat', 'Ich suche nach meinem Schlüssel.'],
          ['abhängen', 'von + Dat', 'Das hängt vom Wetter ab.'],
          ['träumen', 'von + Dat', 'Sie träumt von einer Reise.'],
          ['teilnehmen', 'an + Dat', 'Er nimmt an dem Wettbewerb teil.'],
          ['sich kümmern', 'um + Akk', 'Wer kümmert sich um den Hund?'],
          ['sich beschäftigen', 'mit + Dat', 'Ich beschäftige mich mit Musik.'],
          ['Angst haben', 'vor + Dat', 'Hast du Angst vor Spinnen?'],
          ['sich bedanken', 'bei + Dat (osoba) / für + Akk (rzecz)', 'Ich bedanke mich bei dir für die Einladung.'],
          ['sich ärgern', 'über + Akk', 'Er ärgert sich über den Stau.'],
          ['sich gewöhnen', 'an + Akk', 'Ich habe mich an das Klima gewöhnt.'],
        ],
      },
      examples: [
        { de: 'Worauf wartest du? - Auf die Antwort meines Lehrers.', pl: 'Na co czekasz?' },
        { de: 'Wonach suchst du? - Nach meinem Handy.', pl: 'Czego szukasz?' },
        { de: 'Auf wen wartest du? - Auf meine Schwester.', pl: 'Na kogo czekasz? (osoba → przyimek + wen/wem)' },
      ],
      pitfalls: [
        'Polski wpływa na wybór przyimka: „czekać NA” = auf (OK), ale „pytać O drogę” = fragen **nach**, nie „über”.',
        '**sich freuen auf** (coś przed nami) vs **sich freuen über** (coś, co już jest) - klasyczny dystraktor.',
        'teilnehmen **an + Dativ**: an **dem** (am) Wettbewerb, nie „an den”.',
        'Przy osobach NIE używamy wo-/da-: „Auf wen?”, „auf ihn”, a nie „worauf”, „darauf”.',
      ],
      wrongRight: [
        { wrong: 'Ich warte für den Bus.', right: 'Ich warte auf den Bus.', why: 'warten zawsze z auf + Akk.' },
        { wrong: 'Er fragt über den Weg.', right: 'Er fragt nach dem Weg.', why: 'fragen nach + Dat.' },
        { wrong: 'Ich interessiere mich an Kunst.', right: 'Ich interessiere mich für Kunst.', why: 'sich interessieren für + Akk.' },
        { wrong: 'Das hängt von das Wetter ab.', right: 'Das hängt vom Wetter ab.', why: 'von wymaga celownika: von dem = vom.' },
      ],
    },
  },
  {
    id: 'praepositionaladverbien',
    category: 'grammatik',
    title: 'Präpositionaladverbien & Fragewörter',
    titlePl: 'worauf/darauf, wessen, wobei',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 3 etapu szkolnego 2024/25 i 2025/26: Worauf, Wonach, Wessen, Wobei, Wie weit.',
    lesson: {
      intro:
        'Gdy przyimek odnosi się do **rzeczy lub sprawy**, łączymy go z **wo-** (pytanie) lub **da-** (odpowiedź/odesłanie). Jeśli przyimek zaczyna się od samogłoski, wstawiamy **-r-**: wo**r**auf, da**r**über. Do **osób** używamy przyimka + zaimka.',
      table: {
        head: ['Przyimek', 'Pytanie (rzecz)', 'Odesłanie', 'Osoba'],
        rows: [
          ['auf', 'worauf?', 'darauf', 'auf wen? / auf ihn'],
          ['über', 'worüber?', 'darüber', 'über wen? / über sie'],
          ['an', 'woran?', 'daran', 'an wen? / an ihn'],
          ['mit', 'womit?', 'damit', 'mit wem? / mit ihr'],
          ['nach', 'wonach?', 'danach', 'nach wem?'],
          ['von', 'wovon?', 'davon', 'von wem?'],
          ['für', 'wofür?', 'dafür', 'für wen?'],
          ['bei', 'wobei?', 'dabei', 'bei wem?'],
        ],
      },
      examples: [
        { de: 'Worüber habt ihr gesprochen? - Über den Film.', pl: 'O czym rozmawialiście?' },
        { de: 'Wessen Rucksack ist das? - Das ist Pauls Rucksack.', pl: 'Czyj to plecak? (Genitiv)' },
        { de: 'Wobei kann ich dir helfen? - Bei den Hausaufgaben.', pl: 'W czym mogę ci pomóc?' },
        { de: 'Ich freue mich darauf, dich zu sehen.', pl: 'da- zapowiada zdanie z zu/dass' },
      ],
      pitfalls: [
        'Odpowiedź musi zawierać **ten sam przyimek**: Worauf...? → Auf...; Wonach...? → Nach... To najszybszy klucz w zadaniu pytanie-odpowiedź.',
        '**Wessen** = czyj (Genitiv) - odpowiedź to zwykle „Pauls / meines Bruders”.',
        '„Wie weit” pyta o odległość (Wie weit ist es bis zum Bahnhof?), „Wie lange” o czas trwania.',
      ],
      wrongRight: [
        { wrong: 'Auf was wartest du?', right: 'Worauf wartest du?', why: '„auf was” jest potoczne - na konkursie wo(r)-.' },
        { wrong: 'Worauf wartest du? - Auf meinen Bruder.', right: 'Auf wen wartest du? - Auf meinen Bruder.', why: 'Osoba → auf wen.' },
        { wrong: 'Ich denke daran an meine Oma.', right: 'Ich denke an meine Oma.', why: 'da- tylko odsyła - nie dublujemy.' },
      ],
    },
  },
  {
    id: 'kasus',
    category: 'grammatik',
    title: 'Kasus & Artikel',
    titlePl: 'Przypadki i rodzajniki',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny i zad. 4, 6 rejonowy: formy rodzajnika, n-Deklination, Dativ Plural (Nächten).',
    lesson: {
      intro:
        'Precyzja zaczyna się od rodzajnika. Najczęstsze błędy u płynnych mówców: **Dativ Plural (-n)**, **n-Deklination** i **Genitiv**. Te formy „słychać” mniej w mowie, a na konkursie są punktowane zero-jedynkowo.',
      table: {
        head: ['', 'maskulin', 'feminin', 'neutral', 'Plural'],
        rows: [
          ['Nom', 'der / ein', 'die / eine', 'das / ein', 'die / -'],
          ['Akk', 'den / einen', 'die / eine', 'das / ein', 'die / -'],
          ['Dat', 'dem / einem', 'der / einer', 'dem / einem', 'den / - + n'],
          ['Gen', 'des / eines + (e)s', 'der / einer', 'des / eines + (e)s', 'der / -'],
        ],
      },
      rules: [
        { title: 'Dativ Plural', body: 'Rzeczownik w Dativ Plural dostaje **-n** (jeśli nie kończy się na -n lub -s): mit den Kindern, in drei Nächten, mit den Autos.' },
        { title: 'n-Deklination', body: 'Rodzaj męski osobowy/zwierzęta na -e i kilka innych: der Junge → den/dem/des Junge**n**; der Student, der Mensch, der Nachbar, der Kollege, der Held, der Name (des Namens), der Herr (dem Herrn).' },
        { title: 'Genitiv', body: 'der Mann → des Mann**es**; das Kind → des Kind**es**; Genitiv po wegen, trotz, während, statt, innerhalb.' },
      ],
      examples: [
        { de: 'Ich habe mit dem Nachbarn gesprochen.' },
        { de: 'Wir haben in zwei Nächten nur wenig geschlafen.', pl: 'Dativ Plural: die Nächte → in den Nächten' },
        { de: 'Das Auto meines Vaters ist neu.' },
      ],
      pitfalls: [
        '„mit den Freunde” - brak -n w Dativ Plural to najczęstszy błąd native-like mówców.',
        'Herr → Herrn (Sg.) ale Herren (Pl.): „Sehr geehrter Herr Müller” (Nom!), „an Herrn Müller”.',
        'Po „ohne, für, durch, gegen, um” zawsze Akkusativ; po „aus, bei, mit, nach, seit, von, zu” zawsze Dativ.',
      ],
      wrongRight: [
        { wrong: 'Ich spiele mit meinen Freunde.', right: 'Ich spiele mit meinen Freunden.', why: 'Dativ Plural: -n.' },
        { wrong: 'Ich frage den Student.', right: 'Ich frage den Studenten.', why: 'n-Deklination.' },
        { wrong: 'Das Fahrrad von meinem Bruder...', right: 'Das Fahrrad meines Bruders...', why: 'W piśmie konkursowym lepszy Genitiv.' },
      ],
    },
  },
  {
    id: 'praepositionen',
    category: 'grammatik',
    title: 'Präpositionen',
    titlePl: 'Przyimki z Akk/Dat/Gen',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny 2025/26 (Bei diesem Wetter), 2024/25 (zu + Dat), zad. 4 rejonowy (zu/an/auf).',
    lesson: {
      intro: 'Przyimki mają stały przypadek. Dodatkowo liczą się **ściągnięcia** (zum, zur, beim, vom, im, am, ins) i **idiomatyczne połączenia** (bei diesem Wetter, zu Fuß, mit dem Zug, auf Deutsch).',
      table: {
        head: ['Przypadek', 'Przyimki'],
        rows: [
          ['Akkusativ', 'durch, für, gegen, ohne, um, bis, entlang (po rzeczowniku)'],
          ['Dativ', 'aus, bei, mit, nach, seit, von, zu, gegenüber, ab'],
          ['Genitiv', 'wegen, trotz, während, statt/anstatt, innerhalb, außerhalb'],
        ],
      },
      rules: [
        { title: 'Kierunek: zu / nach / in', body: '**nach** + miasta/kraje bez rodzajnika (nach Wien) i nach Hause; **in** + kraje z rodzajnikiem (in die Schweiz, in die Türkei); **zu** + osoby, instytucje (zum Arzt, zur Schule).' },
        { title: 'Miejsce: bei / in / auf', body: '**bei** + osoba/firma (beim Arzt, bei Oma); zu Hause; in der Schweiz; auf dem Land.' },
        { title: 'Czas', body: '**am** Montag / am 5. Oktober; **um** 9 Uhr; **im** Oktober / im Sommer; **seit** zwei Jahren (trwa nadal); **vor** zwei Jahren (temu).' },
      ],
      examples: [
        { de: 'Bei diesem Wetter bleiben wir zu Hause.' },
        { de: 'Seit drei Jahren lerne ich Klavier.' },
        { de: 'Wegen des Regens fällt das Spiel aus.' },
      ],
      pitfalls: [
        '„seit” (od - wciąż trwa) vs „vor” (temu) vs „ab” (od - w przyszłość).',
        'nach Hause (kierunek) vs zu Hause (miejsce).',
        'in die Schweiz, in die USA, in den Iran - kraje z rodzajnikiem nie łączą się z nach.',
      ],
      wrongRight: [
        { wrong: 'Ich fahre zu Wien.', right: 'Ich fahre nach Wien.', why: 'Miasta: nach.' },
        { wrong: 'Ich fahre nach die Schweiz.', right: 'Ich fahre in die Schweiz.', why: 'Kraj z rodzajnikiem: in + Akk.' },
        { wrong: 'Ich wohne hier vor drei Jahren.', right: 'Ich wohne hier seit drei Jahren.', why: 'Trwa nadal → seit.' },
      ],
    },
  },
  {
    id: 'wechselpraepositionen',
    category: 'grammatik',
    title: 'Wechselpräpositionen',
    titlePl: 'Przyimki zmiennorządne (Wo? / Wohin?)',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Wojewódzki 2025/26 zad. 8 (przyimek + rodzajnik), typowe pułapki Dat/Akk w zadaniach luk.',
    lesson: {
      intro: 'in, an, auf, über, unter, vor, hinter, neben, zwischen: **Wohin? → Akkusativ** (ruch/zmiana miejsca), **Wo? → Dativ** (położenie). Pary czasowników: legen/liegen, stellen/stehen, setzen/sitzen, hängen (ich hänge das Bild **an die** Wand → das Bild hängt **an der** Wand).',
      examples: [
        { de: 'Ich lege das Buch auf den Tisch. → Das Buch liegt auf dem Tisch.' },
        { de: 'Wir gehen ins Kino. → Wir sind im Kino.' },
        { de: 'Er hat das Plakat an die Wand gehängt.' },
      ],
      pitfalls: [
        '„ankommen **in** + Dativ”: Wir kommen in Berlin / im Hotel an (nie „in das Hotel”).',
        'Znaczenie przenośne ma stały przypadek: denken an + Akk, teilnehmen an + Dat, Angst vor + Dat.',
        'Czasowniki ruchu w obrębie miejsca: Er läuft im Park (biega po parku) vs Er läuft in den Park (wbiega do parku).',
      ],
      wrongRight: [
        { wrong: 'Ich stelle die Vase auf dem Tisch.', right: 'Ich stelle die Vase auf den Tisch.', why: 'stellen = ruch → Akk.' },
        { wrong: 'Wir sind in das Museum angekommen.', right: 'Wir sind im Museum angekommen.', why: 'ankommen + Wo? → Dat.' },
      ],
    },
  },
  {
    id: 'adjektivdeklination',
    category: 'grammatik',
    title: 'Adjektivdeklination',
    titlePl: 'Odmiana przymiotnika',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 7 szkolny 2025/26 (bekannte), zad. 4/6 rejonowy (freie/freier/freien, klassischen).',
    lesson: {
      intro: 'Zasada „jednego sygnału”: jeśli rodzajnik **już pokazuje** rodzaj i przypadek, przymiotnik dostaje słabe -e/-en. Jeśli nie pokazuje (brak rodzajnika, ein bez końcówki), sygnał przejmuje przymiotnik.',
      table: {
        head: ['', 'der-Wort (słaba)', 'ein-Wort (mieszana)', 'bez rodzajnika (mocna)'],
        rows: [
          ['Nom m', 'der alte Mann', 'ein alter Mann', 'alter Wein'],
          ['Nom n', 'das kleine Kind', 'ein kleines Kind', 'kaltes Wasser'],
          ['Nom f', 'die neue Stadt', 'eine neue Stadt', 'frische Milch'],
          ['Akk m', 'den alten Mann', 'einen alten Mann', 'alten Wein'],
          ['Dat', 'dem/der alten ...', 'einem/einer alten ...', 'altem Wein / frischer Milch'],
          ['Plural', 'die alten Häuser', 'keine alten Häuser', 'alte Häuser'],
        ],
      },
      examples: [
        { de: 'Mit freundlichen Grüßen', pl: 'mocna odmiana, Dativ Plural' },
        { de: 'Das ist ein bekanntes Museum.' },
        { de: 'Wir wohnen in einer kleinen Stadt.' },
      ],
      pitfalls: [
        'Po „viele, einige, wenige, mehrere” → mocna odmiana: viele junge Leute (nie „jungen”).',
        'Po „alle, beide, keine, meine” w Plural → -en: alle jungen Leute, meine besten Freunde.',
        '„ein” w Nom m i Nom/Akk n nie ma końcówki → przymiotnik: -er / -es.',
      ],
      wrongRight: [
        { wrong: 'Mit freundliche Grüße', right: 'Mit freundlichen Grüßen', why: 'mit + Dativ Plural, mocna odmiana: -en.' },
        { wrong: 'ein interessante Buch', right: 'ein interessantes Buch', why: 'ein nie pokazuje neutrum → -es.' },
        { wrong: 'viele jungen Leute', right: 'viele junge Leute', why: 'viele → odmiana mocna.' },
      ],
    },
  },
  {
    id: 'komparation',
    category: 'grammatik',
    title: 'Komparation',
    titlePl: 'Stopniowanie przymiotników',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Zad. 3 szkolny 2025/26 (porównanie), zad. 6 rejonowy (praktischer, superlatywy), woj. 6.5 (häufiger).',
    lesson: {
      intro: 'Stopień wyższy: **-er** (+ często przegłos), najwyższy: **am -sten** / der -ste. Porównanie: **so ... wie** (równość), **-er als** (nierówność).',
      table: {
        head: ['Stopień równy', 'Wyższy', 'Najwyższy'],
        rows: [
          ['gut', 'besser', 'am besten'],
          ['viel', 'mehr', 'am meisten'],
          ['gern', 'lieber', 'am liebsten'],
          ['hoch', 'höher', 'am höchsten'],
          ['nah', 'näher', 'am nächsten'],
          ['groß', 'größer', 'am größten'],
          ['alt / jung', 'älter / jünger', 'am ältesten / am jüngsten'],
          ['teuer', 'teurer', 'am teuersten'],
          ['dunkel', 'dunkler', 'am dunkelsten'],
        ],
      },
      examples: [
        { de: 'Die Zugspitze ist höher als der Watzmann.' },
        { de: 'Mein Bruder ist genauso groß wie ich.' },
        { de: 'Das ist der höchste Berg Deutschlands.' },
      ],
      pitfalls: [
        '**als** po stopniu wyższym, **wie** przy równości - nigdy „größer wie”.',
        'hoch → der hohe Berg (bez c!), ale höher, am höchsten.',
        'Przymiotnik w stopniu wyższym przed rzeczownikiem też się odmienia: ein größeres Haus.',
      ],
      wrongRight: [
        { wrong: 'Er ist größer wie ich.', right: 'Er ist größer als ich.', why: 'Stopień wyższy + als.' },
        { wrong: 'Das ist am besten Film.', right: 'Das ist der beste Film.', why: 'Przed rzeczownikiem: der beste.' },
        { wrong: 'ein hocher Turm', right: 'ein hoher Turm', why: 'hoch traci -c- przy odmianie.' },
      ],
    },
  },
  {
    id: 'wortstellung',
    category: 'grammatik',
    title: 'Wortstellung',
    titlePl: 'Szyk zdania (Haupt- und Nebensatz)',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 2 (luki zdaniowe) i transformacje zdań na etapie wojewódzkim (bevor, wie alt er ist).',
    lesson: {
      intro: 'Trzy pozycje czasownika: **2. miejsce** w zdaniu głównym (także po inwersji), **koniec** w zdaniu podrzędnym, **1. miejsce** w pytaniu tak/nie i trybie rozkazującym.',
      rules: [
        { title: 'Inwersja', body: 'Gdy zdanie zaczyna się od czegoś innego niż podmiot, czasownik zostaje na 2. miejscu, a podmiot idzie za nim: **Morgen fahre ich** nach Berlin.' },
        { title: 'Nebensatz', body: 'Po weil, dass, obwohl, wenn, als, ob, damit... czasownik osobowy na koniec: ..., weil ich morgen nach Berlin **fahre**. Z czasownikiem modalnym: ..., weil ich morgen **fahren muss**.' },
        { title: 'Nebensatz na początku', body: 'Zdanie podrzędne zajmuje 1. pozycję → czasownik zdania głównego od razu po przecinku: **Weil es regnet, bleiben wir** zu Hause.' },
        { title: 'TeKaMoLo', body: 'Kolejność okoliczników: Temporal - Kausal - Modal - Lokal: Ich fahre morgen wegen der Prüfung mit dem Zug nach Warschau.' },
      ],
      examples: [
        { de: 'Nachdem wir gegessen hatten, gingen wir spazieren.' },
        { de: 'Ich weiß nicht, ob er heute kommt.' },
        { de: 'Er sagt, dass er das Buch schon gelesen hat.' },
      ],
      pitfalls: [
        'Perfekt w zdaniu podrzędnym: posiłkowy na **samym końcu**: ..., weil ich das Buch gelesen **habe**.',
        'Czasownik rozdzielny w zdaniu podrzędnym łączy się: ..., weil der Film um 8 Uhr **anfängt**.',
        'Podwójny bezokolicznik: ..., weil er nicht **hat kommen können** (wyższy poziom - wojewódzki).',
      ],
      wrongRight: [
        { wrong: 'Morgen ich fahre nach Berlin.', right: 'Morgen fahre ich nach Berlin.', why: 'Inwersja: czasownik na 2. miejscu.' },
        { wrong: '..., weil ich habe keine Zeit.', right: '..., weil ich keine Zeit habe.', why: 'weil → czasownik na koniec (w piśmie).' },
        { wrong: 'Wenn es regnet, wir bleiben zu Hause.', right: 'Wenn es regnet, bleiben wir zu Hause.', why: 'Po Nebensatz od razu czasownik.' },
      ],
    },
  },
  {
    id: 'konnektoren',
    category: 'grammatik',
    title: 'Konnektoren',
    titlePl: 'Spójniki: weil, denn, obwohl, deshalb, trotzdem',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5.4 szkolny 2025/26 (denn vs obwohl), zad. 2 (luki zdaniowe - aber, deshalb, denn).',
    lesson: {
      intro: 'Spójniki dzielimy według **wpływu na szyk**. To decyduje o poprawności - a znaczenie o tym, czy zdanie ma sens (przyczyna vs przyzwolenie!).',
      table: {
        head: ['Grupa', 'Spójniki', 'Szyk'],
        rows: [
          ['Pozycja 0 (ADUSO)', 'aber, denn, und, sondern, oder', 'Hauptsatz bez zmian: ..., denn ich habe Hunger.'],
          ['Podrzędne', 'weil, da, obwohl, dass, wenn, als, ob, damit, bevor, nachdem, während, seit, bis', 'Czasownik na koniec'],
          ['Przysłówki (pozycja 1)', 'deshalb, deswegen, darum, trotzdem, außerdem, dann, sonst, also', 'Inwersja: ..., deshalb bleibe ich.'],
        ],
      },
      rules: [
        { title: 'Przyczyna', body: 'weil / da / denn (dlaczego?) ↔ skutek: deshalb / deswegen / darum.' },
        { title: 'Przyzwolenie', body: '**obwohl** + Nebensatz (chociaż) ↔ **trotzdem** + inwersja (mimo to) ↔ **trotz** + Genitiv.' },
        { title: 'sondern vs aber', body: '**sondern** tylko po zaprzeczeniu, gdy korygujemy: nicht A, sondern B. Nicht nur ... sondern auch.' },
      ],
      examples: [
        { de: 'Obwohl es regnet, gehen wir spazieren.' },
        { de: 'Es regnet. Trotzdem gehen wir spazieren.' },
        { de: 'Ich bleibe zu Hause, denn ich bin krank.' },
        { de: 'Das ist nicht mein Heft, sondern deins.' },
      ],
      pitfalls: [
        'Najpierw sprawdź **logikę**: przyczyna (weil/denn) czy kontrast (obwohl/trotzdem)? Dystraktory na konkursie są gramatycznie poprawne, ale bez sensu.',
        '„denn” nie przesuwa czasownika; „weil” przesuwa.',
        'Po „außerdem”, „deshalb”, „trotzdem” - inwersja, nie koniec zdania.',
      ],
      wrongRight: [
        { wrong: 'Ich gehe raus, obwohl die Sonne scheint.', right: 'Ich gehe raus, weil die Sonne scheint.', why: 'Logika: słońce jest powodem, nie przeszkodą.' },
        { wrong: 'Es regnet, trotzdem wir gehen raus.', right: 'Es regnet, trotzdem gehen wir raus.', why: 'trotzdem → inwersja.' },
        { wrong: 'Nicht Anna, aber Paul hat gewonnen.', right: 'Nicht Anna, sondern Paul hat gewonnen.', why: 'Korekta po negacji → sondern.' },
      ],
    },
  },
  {
    id: 'wenn-als-ob',
    category: 'grammatik',
    title: 'wenn / als / wann / ob',
    titlePl: 'Kiedy? Jeśli? Czy?',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny 2024/25: wenn vs als.',
    lesson: {
      intro: 'Cztery słowa, które po polsku często tłumaczymy tak samo. Klucz: **jednorazowo w przeszłości → als**; powtarzalnie lub teraz/przyszłość → **wenn**; pytanie o czas → **wann**; pytanie zależne tak/nie → **ob**.',
      table: {
        head: ['Słowo', 'Kiedy używać', 'Przykład'],
        rows: [
          ['als', 'jednorazowe zdarzenie / okres w przeszłości', 'Als ich in Wien wohnte, ging ich oft ins Museum.'],
          ['wenn', 'powtarzalne (także w przeszłości) lub warunek', 'Immer wenn es regnete, spielten wir drinnen.'],
          ['wann', 'pytanie o czas (także zależne)', 'Weißt du, wann der Zug kommt?'],
          ['ob', 'czy (pytanie zależne tak/nie)', 'Ich weiß nicht, ob er kommt.'],
        ],
      },
      examples: [
        { de: 'Als ich zehn Jahre alt war, bekam ich einen Hund.' },
        { de: 'Wenn ich Zeit habe, helfe ich dir.' },
        { de: 'Sie fragt, ob wir mitkommen.' },
      ],
      pitfalls: [
        'Okres życia to też jedno zdarzenie: „Als ich klein war...” (nie wenn).',
        '„immer wenn / jedes Mal wenn” w przeszłości → wenn.',
        '„ob” to NIE „wenn”: Ich weiß nicht, ob... (czy), a nie „wenn”.',
      ],
      wrongRight: [
        { wrong: 'Wenn ich gestern nach Hause kam, ...', right: 'Als ich gestern nach Hause kam, ...', why: 'Jednorazowo w przeszłości → als.' },
        { wrong: 'Ich weiß nicht, wenn er kommt.', right: 'Ich weiß nicht, ob er kommt. / ..., wann er kommt.', why: 'czy → ob; kiedy → wann.' },
      ],
    },
  },
  {
    id: 'perfekt',
    category: 'grammatik',
    title: 'Perfekt & Partizip II',
    titlePl: 'Czas przeszły Perfekt',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 7 rejonowy 2023/24 i 2024/25 (hat begonnen, hat gedreht), zad. 6 wojewódzki (Partizip).',
    lesson: {
      intro: 'Dwie decyzje: **haben czy sein** oraz **poprawny imiesłów**. Płynni mówcy mylą się głównie w imiesłowach czasowników nieregularnych i w czasownikach na -ieren / nierozdzielnych (bez ge-).',
      rules: [
        { title: 'sein', body: 'zmiana miejsca (gehen, fahren, fliegen, kommen), zmiana stanu (aufwachen, einschlafen, sterben, werden, wachsen) + sein, bleiben, passieren, geschehen, begegnen, gelingen.' },
        { title: 'Bez ge-', body: 'Przedrostki nierozdzielne be-, emp-, ent-, er-, ge-, miss-, ver-, zer- (verstanden, besucht, erzählt) oraz -ieren (studiert, fotografiert, passiert).' },
        { title: 'Rozdzielne', body: 'ge- w środku: aufgestanden, eingekauft, angefangen, ferngesehen.' },
      ],
      table: {
        head: ['Infinitiv', 'Partizip II', 'Hilfsverb'],
        rows: [
          ['beginnen', 'begonnen', 'haben'],
          ['bringen', 'gebracht', 'haben'],
          ['denken', 'gedacht', 'haben'],
          ['bleiben', 'geblieben', 'sein'],
          ['vergessen', 'vergessen', 'haben'],
          ['verlieren', 'verloren', 'haben'],
          ['ziehen / umziehen', 'gezogen / umgezogen', 'haben / sein'],
          ['treffen', 'getroffen', 'haben'],
          ['steigen / aussteigen', 'gestiegen / ausgestiegen', 'sein'],
          ['nennen', 'genannt', 'haben'],
          ['schneiden', 'geschnitten', 'haben'],
          ['werfen', 'geworfen', 'haben'],
        ],
      },
      examples: [
        { de: 'Der Film hat um acht Uhr begonnen.' },
        { de: 'Wir sind nach Salzburg umgezogen.' },
        { de: 'Ich habe das Wort nicht verstanden.' },
      ],
      pitfalls: [
        'fahren: „Ich bin nach Wien gefahren” ale „Ich habe das Auto in die Garage gefahren” (z dopełnieniem → haben).',
        'W Austrii/Bawarii mówi się „ich bin gesessen/gestanden” - na konkursie bezpieczniej: **habe gesessen/gestanden**.',
        'gewinnen → gewonnen, beginnen → begonnen, schwimmen → geschwommen (ist).',
      ],
      wrongRight: [
        { wrong: 'Ich habe nach Berlin gefahren.', right: 'Ich bin nach Berlin gefahren.', why: 'Ruch → sein.' },
        { wrong: 'Er hat das nicht geverstanden.', right: 'Er hat das nicht verstanden.', why: 'ver- → bez ge-.' },
        { wrong: 'Sie hat in Wien gestudiert.', right: 'Sie hat in Wien studiert.', why: '-ieren → bez ge-.' },
      ],
    },
  },
  {
    id: 'praeteritum',
    category: 'grammatik',
    title: 'Präteritum & Plusquamperfekt',
    titlePl: 'Czas przeszły prosty i zaprzeszły',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 7 rejonowy (war, gab), teksty czytane (biografie, historia) - narracja w Präteritum.',
    lesson: {
      intro: 'W tekstach pisanych i historycznych (UNESCO!) dominuje **Präteritum**. **Plusquamperfekt** (hatte/war + Partizip II) = coś wydarzyło się **przed** innym zdarzeniem w przeszłości - typowo po **nachdem**.',
      table: {
        head: ['Infinitiv', 'Präteritum (er/sie/es)', 'Partizip II'],
        rows: [
          ['sein', 'war', 'gewesen'],
          ['haben', 'hatte', 'gehabt'],
          ['werden', 'wurde', 'geworden'],
          ['geben', 'gab', 'gegeben'],
          ['bauen', 'baute', 'gebaut'],
          ['entstehen', 'entstand', 'entstanden'],
          ['gründen', 'gründete', 'gegründet'],
          ['lassen', 'ließ', 'gelassen'],
          ['liegen', 'lag', 'gelegen'],
          ['ziehen', 'zog', 'gezogen'],
          ['stehen', 'stand', 'gestanden'],
          ['finden', 'fand', 'gefunden'],
          ['wissen', 'wusste', 'gewusst'],
          ['kennen', 'kannte', 'gekannt'],
        ],
      },
      examples: [
        { de: 'Karl der Große ließ die Pfalzkapelle in Aachen bauen.' },
        { de: 'Nachdem der Dom fertig war, kamen viele Pilger nach Köln.' },
        { de: 'Nachdem wir gegessen hatten, gingen wir ins Museum.' },
      ],
      pitfalls: [
        'Po **nachdem** czasy się przesuwają: nachdem + Plusquamperfekt → Präteritum; nachdem + Perfekt → Präsens.',
        'Präteritum 1. i 3. os. l.poj. bez końcówki: ich/er **kam**, ich/er **war**.',
        'Mieszane: bringen - brachte, denken - dachte, kennen - kannte, wissen - wusste.',
      ],
      wrongRight: [
        { wrong: 'Nachdem wir essen, gingen wir.', right: 'Nachdem wir gegessen hatten, gingen wir.', why: 'Wcześniejsza czynność → Plusquamperfekt.' },
        { wrong: 'Er denkte an sie.', right: 'Er dachte an sie.', why: 'denken - czasownik mieszany.' },
      ],
    },
  },
  {
    id: 'zeitformen',
    category: 'grammatik',
    title: 'Präsens, Futur I & Zeitgefüge',
    titlePl: 'Czasy: teraźniejszy, przyszły, dobór czasu',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Zad. 7 rejonowy - dobór czasu w tekście (mieszane czasy), zad. 6 (koniugacja).',
    lesson: {
      intro: 'W Präsens pułapką są **zmiany samogłoski** (du fährst, er liest, du isst) i końcówki po -t/-d (er arbeitet, du findest). **Futur I**: werden + bezokolicznik - przypuszczenie lub mocna zapowiedź; o przyszłości zwykle mówimy w Präsens + określenie czasu.',
      table: {
        head: ['Infinitiv', 'du', 'er/sie/es'],
        rows: [
          ['fahren', 'fährst', 'fährt'],
          ['lesen', 'liest', 'liest'],
          ['essen', 'isst', 'isst'],
          ['nehmen', 'nimmst', 'nimmt'],
          ['werden', 'wirst', 'wird'],
          ['wissen', 'weißt', 'weiß'],
          ['halten', 'hältst', 'hält'],
          ['laufen', 'läufst', 'läuft'],
          ['treten', 'trittst', 'tritt'],
        ],
      },
      examples: [
        { de: 'Morgen fahre ich nach Krakau.', pl: 'przyszłość w Präsens' },
        { de: 'Er wird wohl krank sein.', pl: 'Futur I - przypuszczenie' },
        { de: 'Du isst zu schnell.' },
      ],
      pitfalls: [
        'Tryb rozkazujący czasowników e→i: **Iss!**, **Nimm!**, **Lies!** (bez -st), ale a→ä nie przechodzi: **Fahr!** (nie „Fähr”).',
        'Uzgadniaj czas w całym tekście - na konkursie tekst o historii → Präteritum/Perfekt.',
      ],
      wrongRight: [
        { wrong: 'Du nehmst den Bus.', right: 'Du nimmst den Bus.', why: 'e → i.' },
        { wrong: 'Fähr langsamer!', right: 'Fahr langsamer!', why: 'Imperativ du: bez przegłosu.' },
        { wrong: 'Esse dein Gemüse!', right: 'Iss dein Gemüse!', why: 'e → i także w Imperativ.' },
      ],
    },
  },
  {
    id: 'modalverben',
    category: 'grammatik',
    title: 'Modalverben',
    titlePl: 'Czasowniki modalne',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5.5 szkolny 2025/26 (darfst), woj. 10.2 (es ist mir nicht erlaubt → ich darf nicht), rejonowy 7 (kann).',
    lesson: {
      intro: 'Sześć czasowników, ale różnice znaczeniowe są konkursowe: **dürfen** (pozwolenie; nicht dürfen = zakaz), **müssen** (konieczność; nicht müssen = nie trzeba), **sollen** (ktoś mi każe / rada), **mögen/möchte**, **können**, **wollen**.',
      table: {
        head: ['', 'können', 'müssen', 'dürfen', 'sollen', 'wollen', 'mögen'],
        rows: [
          ['ich', 'kann', 'muss', 'darf', 'soll', 'will', 'mag'],
          ['du', 'kannst', 'musst', 'darfst', 'sollst', 'willst', 'magst'],
          ['er', 'kann', 'muss', 'darf', 'soll', 'will', 'mag'],
          ['Prät.', 'konnte', 'musste', 'durfte', 'sollte', 'wollte', 'mochte'],
        ],
      },
      rules: [
        { title: 'Parafrazy (transformacje!)', body: 'es ist erlaubt → dürfen; es ist verboten → nicht dürfen; es ist nötig / notwendig → müssen; es ist nicht nötig → nicht müssen / nicht brauchen zu; die Absicht haben → wollen; in der Lage sein / fähig sein → können.' },
      ],
      examples: [
        { de: 'Hier darf man nicht rauchen.', pl: 'zakaz' },
        { de: 'Du musst nicht kommen.', pl: 'nie musisz (ale możesz)' },
        { de: 'Der Arzt sagt, ich soll mehr schlafen.' },
      ],
      pitfalls: [
        '„nicht müssen” ≠ „nicht dürfen”! (nie trzeba vs nie wolno).',
        'Präteritum bez przegłosu: konnte, musste, durfte.',
        'Perfekt z bezokolicznikiem: Ich habe nicht kommen **können** (podwójny bezokolicznik).',
      ],
      wrongRight: [
        { wrong: 'Du darfst nicht kommen (= nie musisz).', right: 'Du musst nicht kommen.', why: 'Brak konieczności → nicht müssen.' },
        { wrong: 'Ich musste nicht gehen, weil es verboten war.', right: 'Ich durfte nicht gehen, weil es verboten war.', why: 'Zakaz → nicht dürfen.' },
      ],
    },
  },
  {
    id: 'konjunktiv2',
    category: 'grammatik',
    title: 'Konjunktiv II',
    titlePl: 'Tryb przypuszczający',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Reakcje językowe (rady, uprzejme prośby: Könnten Sie..., An deiner Stelle würde ich...).',
    lesson: {
      intro: 'Trzy zastosowania na konkursie: **uprzejma prośba** (Könnten Sie ...? Würden Sie ...?), **rada** (Du solltest ... / An deiner Stelle würde ich ...), **życzenie/warunek nierzeczywisty** (Wenn ich Zeit hätte, ...).',
      table: {
        head: ['Infinitiv', 'Konjunktiv II'],
        rows: [
          ['sein', 'wäre'],
          ['haben', 'hätte'],
          ['werden', 'würde'],
          ['können', 'könnte'],
          ['müssen', 'müsste'],
          ['dürfen', 'dürfte'],
          ['sollen', 'sollte (bez przegłosu)'],
          ['wissen', 'wüsste'],
          ['kommen / gehen', 'käme / ginge (lub würde kommen)'],
        ],
      },
      examples: [
        { de: 'Könnten Sie das bitte wiederholen?' },
        { de: 'An deiner Stelle würde ich mehr lernen.' },
        { de: 'Wenn ich reich wäre, würde ich um die Welt reisen.' },
        { de: 'Wenn ich das gewusst hätte, wäre ich früher gekommen.', pl: 'przeszłość' },
      ],
      pitfalls: [
        'W zdaniu z „wenn” nie używamy „würde” przy sein/haben/modalnych: Wenn ich Zeit **hätte** (nie „haben würde”).',
        'Przeszłość: hätte/wäre + Partizip II.',
        '„Ich hätte gern ...” = uprzejme zamówienie (w sklepie, restauracji).',
      ],
      wrongRight: [
        { wrong: 'Wenn ich Zeit habe würde, ...', right: 'Wenn ich Zeit hätte, ...', why: 'haben → hätte.' },
        { wrong: 'Kannst du mir helfen? (do nauczyciela)', right: 'Könnten Sie mir bitte helfen?', why: 'Rejestr formalny + Konjunktiv II.' },
      ],
    },
  },
  {
    id: 'passiv',
    category: 'grammatik',
    title: 'Passiv',
    titlePl: 'Strona bierna',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny 2024/25, zad. 7 rejonowy 2025/26 (Freiburg - Passiv), teksty o zabytkach („wurde ... gebaut”).',
    lesson: {
      intro: 'Vorgangspassiv = **werden + Partizip II**. W tekstach o zabytkach UNESCO to forma nr 1: „Der Dom **wurde** 1248 **begonnen** und 1880 **vollendet**.”',
      table: {
        head: ['Czas', 'Forma', 'Przykład'],
        rows: [
          ['Präsens', 'wird + P II', 'Das Schloss wird renoviert.'],
          ['Präteritum', 'wurde + P II', 'Das Schloss wurde 1886 eröffnet.'],
          ['Perfekt', 'ist + P II + worden', 'Das Schloss ist renoviert worden.'],
          ['Plusquamp.', 'war + P II + worden', 'Es war schon verkauft worden.'],
          ['z modalnym', 'Modal + P II + werden', 'Das Schloss muss renoviert werden.'],
          ['Zustandspassiv', 'sein + P II', 'Das Museum ist heute geschlossen.'],
        ],
      },
      examples: [
        { de: 'Die Altstadt wurde 1993 in die Welterbeliste aufgenommen.' },
        { de: 'Der Brief wurde von meiner Oma geschrieben.', pl: 'sprawca: von + Dat' },
        { de: 'In Österreich wird Deutsch gesprochen.' },
      ],
      pitfalls: [
        'W Perfekt Passiv: **worden** (nie „geworden”): Das Haus ist gebaut worden.',
        'Sprawca osobowy: **von** + Dativ; przyczyna/środek: **durch** + Akk.',
        'Nie myl z Futur I: „Er wird kommen” (przyszłość) vs „Er wird gefragt” (strona bierna).',
      ],
      wrongRight: [
        { wrong: 'Das Haus ist 1900 gebaut geworden.', right: 'Das Haus ist 1900 gebaut worden.', why: 'Perfekt Passiv → worden.' },
        { wrong: 'Der Dom wurde von 1248 bis 1880 gebaut wird.', right: 'Der Dom wurde von 1248 bis 1880 gebaut.', why: 'Jedno werden w Präteritum.' },
      ],
    },
  },
  {
    id: 'relativsaetze',
    category: 'grammatik',
    title: 'Relativsätze',
    titlePl: 'Zdania względne',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Transformacje na etapie wojewódzkim, luki zdaniowe; szczególnie Relativpronomen w Dativ i z przyimkiem.',
    lesson: {
      intro: 'Zaimek względny bierze **rodzaj i liczbę** od rzeczownika, do którego się odnosi, a **przypadek** od swojej funkcji w zdaniu względnym. Czasownik na końcu.',
      table: {
        head: ['', 'm', 'n', 'f', 'Pl'],
        rows: [
          ['Nom', 'der', 'das', 'die', 'die'],
          ['Akk', 'den', 'das', 'die', 'die'],
          ['Dat', 'dem', 'dem', 'der', '**denen**'],
          ['Gen', 'dessen', 'dessen', 'deren', 'deren'],
        ],
      },
      examples: [
        { de: 'Das ist der Freund, dem ich das Buch geliehen habe.', pl: 'leihen + Dat' },
        { de: 'Die Kinder, mit denen ich spiele, sind nett.' },
        { de: 'Der Schüler, dessen Vater Arzt ist, heißt Tom.' },
        { de: 'Wien ist die Stadt, in der ich sieben Jahre gewohnt habe.' },
        { de: 'Das ist alles, was ich weiß.', pl: 'was po alles, nichts, etwas, das Beste' },
      ],
      pitfalls: [
        'Dativ Plural: **denen** (nie „den”).',
        'Przyimek stoi **przed** zaimkiem: die Stadt, **in der** ...; der Freund, **auf den** ich warte.',
        '„wo” po miejscach jest poprawne (die Stadt, wo ich wohne), ale na konkursie częściej wymagana forma z przyimkiem.',
        '„was” po alles/nichts/etwas/das + superlatyw i po całym zdaniu: Er kam zu spät, was mich ärgerte.',
      ],
      wrongRight: [
        { wrong: 'Die Leute, mit den ich spreche...', right: 'Die Leute, mit denen ich spreche...', why: 'Dat Pl → denen.' },
        { wrong: 'Der Mann, der ich geholfen habe...', right: 'Der Mann, dem ich geholfen habe...', why: 'helfen + Dativ → dem.' },
        { wrong: 'Das ist alles, das ich weiß.', right: 'Das ist alles, was ich weiß.', why: 'Po alles → was.' },
      ],
    },
  },
  {
    id: 'reflexivverben',
    category: 'grammatik',
    title: 'Reflexivverben',
    titlePl: 'Czasowniki zwrotne (mich/mir)',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny 2025/26 (freust du dich) i 2024/25 (dir/dich), rejonowy 6 (anziehen).',
    lesson: {
      intro: 'Zaimek zwrotny jest w **Akkusativ**, chyba że w zdaniu jest już inne dopełnienie w bierniku - wtedy w **Dativ**. Różnica widoczna tylko przy ich/du: mich/mir, dich/dir.',
      table: {
        head: ['Osoba', 'Akk', 'Dat'],
        rows: [
          ['ich', 'mich', 'mir'],
          ['du', 'dich', 'dir'],
          ['er/sie/es', 'sich', 'sich'],
          ['wir', 'uns', 'uns'],
          ['ihr', 'euch', 'euch'],
          ['sie/Sie', 'sich', 'sich'],
        ],
      },
      examples: [
        { de: 'Ich wasche mich. → Ich wasche mir die Hände.' },
        { de: 'Du ziehst dich an. → Du ziehst dir eine Jacke an.' },
        { de: 'Ich kann mir das nicht vorstellen.', pl: 'sich (Dat) etwas vorstellen' },
        { de: 'Hast du dir das Knie verletzt?' },
      ],
      pitfalls: [
        'Zawsze z Dativ: sich (Dat) etwas wünschen / merken / vorstellen / ansehen / leisten.',
        'Po polsku zwrotne, po niemiecku nie: sich uczyć = lernen; bać się = Angst haben (ale: sich fürchten).',
        'Niemieckie zwrotne, polskie nie: sich erkälten (przeziębić się - OK), sich beeilen (spieszyć się), sich bedanken (dziękować).',
      ],
      wrongRight: [
        { wrong: 'Ich wasche mich die Hände.', right: 'Ich wasche mir die Hände.', why: 'die Hände = Akk → zaimek w Dat.' },
        { wrong: 'Ich lerne mich Deutsch.', right: 'Ich lerne Deutsch.', why: 'lernen nie jest zwrotne.' },
        { wrong: 'Kannst du dich das vorstellen?', right: 'Kannst du dir das vorstellen?', why: 'sich (Dat) etwas vorstellen.' },
      ],
    },
  },
  {
    id: 'pronomen',
    category: 'grammatik',
    title: 'Pronomen',
    titlePl: 'Zaimki osobowe i dzierżawcze',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Zad. 6 rejonowy 2023/24 (DEIN → deinem), zad. 6.4 wojewódzki (zaimek + Dativ).',
    lesson: {
      intro: 'Zaimki dzierżawcze odmieniają się jak **ein/kein**. Przy zaimkach osobowych pilnuj **Dativ**: ihm/ihr/ihnen, i czasowników z Dativ (helfen, danken, gefallen, gehören, gratulieren, schmecken, passen).',
      table: {
        head: ['Nom', 'Akk', 'Dat', 'Possessiv'],
        rows: [
          ['ich', 'mich', 'mir', 'mein'],
          ['du', 'dich', 'dir', 'dein'],
          ['er', 'ihn', 'ihm', 'sein'],
          ['sie', 'sie', 'ihr', 'ihr'],
          ['es', 'es', 'ihm', 'sein'],
          ['wir', 'uns', 'uns', 'unser'],
          ['ihr', 'euch', 'euch', 'euer (eure!)'],
          ['sie/Sie', 'sie/Sie', 'ihnen/Ihnen', 'ihr/Ihr'],
        ],
      },
      examples: [
        { de: 'Ich gratuliere dir zum Geburtstag.' },
        { de: 'Wie gefällt Ihnen die Stadt?' },
        { de: 'Wir fahren mit eurem Auto.' },
      ],
      pitfalls: [
        'euer → eure, eurem (e wypada): „eure Schule” (nie „euere”).',
        'Kolejność: rzeczownik Dat przed Akk, ale zaimek Akk przed Dat: Ich gebe **es ihm**.',
        'Formalnie: Ihnen / Ihr wielką literą.',
      ],
      wrongRight: [
        { wrong: 'Ich helfe dich.', right: 'Ich helfe dir.', why: 'helfen + Dativ.' },
        { wrong: 'mit deinen Bruder', right: 'mit deinem Bruder', why: 'mit + Dat, maskulin.' },
        { wrong: 'Ich gebe ihm es.', right: 'Ich gebe es ihm.', why: 'Dwa zaimki: Akk przed Dat.' },
      ],
    },
  },
  {
    id: 'infinitiv-zu',
    category: 'grammatik',
    title: 'Infinitiv mit zu, um/ohne/statt ... zu',
    titlePl: 'Bezokolicznik z zu',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Transformacje na etapie wojewódzkim; konstrukcje celu (um ... zu / damit).',
    lesson: {
      intro: '**zu + Infinitiv** po wyrażeniach typu: Lust haben, versuchen, vergessen, anfangen, Zeit haben, es ist wichtig. **um ... zu** = cel (ten sam podmiot), **damit** = cel (różne podmioty), **ohne ... zu** = bez robienia, **statt ... zu** = zamiast.',
      examples: [
        { de: 'Ich habe keine Lust, heute ins Kino zu gehen.' },
        { de: 'Ich lerne viel, um den Wettbewerb zu gewinnen.' },
        { de: 'Ich erkläre es dir, damit du es verstehst.' },
        { de: 'Er ging, ohne sich zu verabschieden.' },
        { de: 'Statt zu lernen, spielt er Computer.' },
        { de: 'Vergiss nicht, die Tür abzuschließen.', pl: 'rozdzielny: ab-zu-schließen' },
      ],
      pitfalls: [
        'Czasowniki rozdzielne: zu w środku - an**zu**rufen, auf**zu**stehen.',
        'Bez zu po modalnych, werden, lassen, oraz sehen/hören/gehen: Ich gehe schwimmen.',
        'um ... zu tylko przy **tym samym podmiocie**; inaczej damit.',
      ],
      wrongRight: [
        { wrong: 'Ich lerne, um meine Eltern froh zu sein.', right: 'Ich lerne, damit meine Eltern froh sind.', why: 'Różne podmioty → damit.' },
        { wrong: 'Ich vergesse zu anrufen dich.', right: 'Ich vergesse, dich anzurufen.', why: 'zu w środku, bezokolicznik na końcu.' },
      ],
    },
  },
  {
    id: 'trennbare-verben',
    category: 'grammatik',
    title: 'Trennbare / untrennbare Verben',
    titlePl: 'Czasowniki rozdzielnie i nierozdzielnie złożone',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Antonimy etapu szkolnego (einschalten/ausschalten, aussteigen, ausziehen/anziehen), zad. 8 rejonowe (abholen).',
    lesson: {
      intro: 'Przedrostek rozdzielny idzie na koniec zdania głównego; nierozdzielny zostaje. Antonimy konkursowe często zmieniają **tylko przedrostek**: ein-/aus-, an-/aus-, auf-/zu-, ab-/an-.',
      table: {
        head: ['Czasownik', 'Antonim'],
        rows: [
          ['einschalten', 'ausschalten'],
          ['anmachen', 'ausmachen'],
          ['aufmachen', 'zumachen'],
          ['einsteigen', 'aussteigen'],
          ['anziehen', 'ausziehen'],
          ['abfahren', 'ankommen'],
          ['einpacken', 'auspacken'],
          ['zunehmen', 'abnehmen'],
          ['sich anmelden', 'sich abmelden'],
          ['einatmen', 'ausatmen'],
        ],
      },
      examples: [
        { de: 'Der Zug fährt um 7 Uhr ab und kommt um 9 Uhr an.' },
        { de: 'Bitte schalte das Licht aus!' },
        { de: 'Er übersetzt den Text. (untrennbar: über- nieakcentowane)' },
      ],
      pitfalls: [
        'Antonim musi zachować **formę**: „Steig aus!” → „Steig ein!”, „Er schaltet ... ein” → „Er schaltet ... aus”.',
        'Niektóre przedrostki bywają oba: umfahren (objechać - nierozdzielny) vs umfahren (przejechać kogoś - rozdzielny).',
      ],
      wrongRight: [
        { wrong: 'Ich einkaufe heute.', right: 'Ich kaufe heute ein.', why: 'Rozdzielny w zdaniu głównym.' },
        { wrong: 'Steig aus! → Steig an!', right: 'Steig ein!', why: 'aussteigen ↔ einsteigen.' },
      ],
    },
  },
  {
    id: 'indirekte-fragen',
    category: 'grammatik',
    title: 'Indirekte Fragen',
    titlePl: 'Pytania zależne',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Wojewódzki 2025/26 zad. 10.4 (transformacja: wie alt er ist).',
    lesson: {
      intro: 'Pytanie zależne = zdanie podrzędne. Zaimek pytający (wo, wie, wann, warum, wie alt...) lub **ob** + czasownik na końcu. Uprzejme pytania formalne: „Können Sie mir sagen, wo der Bahnhof ist?”',
      examples: [
        { de: 'Wie alt ist er? → Weißt du, wie alt er ist?' },
        { de: 'Kommt sie morgen? → Ich frage mich, ob sie morgen kommt.' },
        { de: 'Wo kann ich Tickets kaufen? → Können Sie mir sagen, wo ich Tickets kaufen kann?' },
      ],
      pitfalls: [
        'Brak inwersji: „..., wo ist der Bahnhof” jest błędem → „..., wo der Bahnhof ist”.',
        'Pytanie tak/nie → **ob**, nie „wenn”.',
      ],
      wrongRight: [
        { wrong: 'Kannst du mir sagen, wann beginnt der Film?', right: 'Kannst du mir sagen, wann der Film beginnt?', why: 'Czasownik na koniec.' },
        { wrong: 'Ich weiß nicht, kommt er.', right: 'Ich weiß nicht, ob er kommt.', why: 'Tak/nie → ob.' },
      ],
    },
  },
  {
    id: 'imperativ',
    category: 'grammatik',
    title: 'Imperativ',
    titlePl: 'Tryb rozkazujący',
    stages: ['szkolny', 'rejonowy'],
    priority: 2,
    evidence: 'Zad. 4 rejonowy 2023/24 (Fahr/Fahrt/Fährt), zad. 6 (ESSEN → iss).',
    lesson: {
      intro: 'du: temat bez -st (i bez przegłosu a→ä), ale z e→i; ihr: jak w Präsens; Sie: odwrócony szyk.',
      table: {
        head: ['Infinitiv', 'du', 'ihr', 'Sie'],
        rows: [
          ['fahren', 'Fahr!', 'Fahrt!', 'Fahren Sie!'],
          ['essen', 'Iss!', 'Esst!', 'Essen Sie!'],
          ['nehmen', 'Nimm!', 'Nehmt!', 'Nehmen Sie!'],
          ['sein', 'Sei!', 'Seid!', 'Seien Sie!'],
          ['arbeiten', 'Arbeite!', 'Arbeitet!', 'Arbeiten Sie!'],
          ['aufstehen', 'Steh auf!', 'Steht auf!', 'Stehen Sie auf!'],
        ],
      },
      examples: [{ de: 'Sei bitte leise!' }, { de: 'Lies den Text genau!' }, { de: 'Seid pünktlich!' }],
      pitfalls: ['„Seid” (imperatyw ihr) vs „seit” (od kiedy) - pisownia!', 'Fahr! / Lauf! / Schlaf! - bez przegłosu.'],
      wrongRight: [
        { wrong: 'Seit leise, Kinder!', right: 'Seid leise, Kinder!', why: 'Imperativ od sein: seid.' },
        { wrong: 'Lese das!', right: 'Lies das!', why: 'e → ie.' },
      ],
    },
  },
  {
    id: 'negation',
    category: 'grammatik',
    title: 'Negation',
    titlePl: 'Przeczenie: kein, nicht, nichts, nie',
    stages: ['szkolny', 'rejonowy'],
    priority: 3,
    evidence: 'Pośrednio w zadaniach P/F i reakcjach (Doch! vs Ja!).',
    lesson: {
      intro: '**kein** przed rzeczownikiem z ein lub bez rodzajnika; **nicht** w pozostałych przypadkach. Na pytanie przeczące odpowiadamy twierdząco **Doch!**',
      examples: [
        { de: 'Hast du keine Zeit? - Doch, ich habe Zeit.' },
        { de: 'Ich habe noch nie so etwas gesehen.' },
        { de: 'Er hat nichts gesagt.' },
        { de: 'Das ist nicht mein Buch, sondern dein Buch.' },
      ],
      pitfalls: ['„nicht ein” zamiast „kein” to błąd.', 'noch nicht (jeszcze nie) ↔ schon; nicht mehr (już nie) ↔ noch.', 'jemand ↔ niemand, etwas ↔ nichts, immer ↔ nie, überall ↔ nirgends.'],
      wrongRight: [
        { wrong: 'Ich habe nicht ein Auto.', right: 'Ich habe kein Auto.', why: 'ein → kein.' },
        { wrong: 'Kommst du nicht? - Ja, ich komme.', right: 'Kommst du nicht? - Doch, ich komme.', why: 'Zaprzeczenie przeczenia → Doch.' },
      ],
    },
  },
  {
    id: 'temporal',
    category: 'grammatik',
    title: 'Temporale Konstruktionen',
    titlePl: 'Czas: bevor, nachdem, während, seit, bis, Uhrzeit',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Antonimy „Viertel vor → Viertel nach”, „endet → beginnt” (szkolny 2025/26), woj. 10.1 (bevor).',
    lesson: {
      intro: 'Spójniki czasowe i ich przyimkowe odpowiedniki są podstawą transformacji: **bevor ↔ vor + Dat**, **nachdem ↔ nach + Dat**, **während (spójnik) ↔ während + Gen**, **seit(dem)**, **bis**.',
      table: {
        head: ['Spójnik (Nebensatz)', 'Przyimek', 'Przykład'],
        rows: [
          ['bevor', 'vor + Dat', 'Bevor ich esse, ... = Vor dem Essen ...'],
          ['nachdem', 'nach + Dat', 'Nachdem er angekommen war, ... = Nach seiner Ankunft ...'],
          ['während', 'während + Gen', 'Während ich schlief, ... = Während meines Schlafs ...'],
          ['seit(dem)', 'seit + Dat', 'Seitdem sie hier wohnt, ... = Seit ihrem Umzug ...'],
          ['bis', 'bis zu + Dat', 'Bis wir ankommen, ... = Bis zu unserer Ankunft ...'],
        ],
      },
      examples: [
        { de: 'Es ist Viertel nach acht. (8:15) / Es ist Viertel vor neun. (8:45)' },
        { de: 'Es ist halb zehn. (9:30!)', pl: 'halb zehn = wpół do dziesiątej' },
        { de: 'Bevor du gehst, mach bitte das Fenster zu.' },
      ],
      pitfalls: ['**halb zehn = 9:30**, nie 10:30.', 'Antonimy czasowe: früh ↔ spät, vorher ↔ nachher, anfangen/beginnen ↔ aufhören/enden, schon ↔ noch nicht.'],
      wrongRight: [
        { wrong: 'Nachdem ich esse, gehe ich.', right: 'Nachdem ich gegessen habe, gehe ich.', why: 'nachdem = czynność wcześniejsza.' },
        { wrong: 'Vor ich gehe, ...', right: 'Bevor ich gehe, ...', why: 'vor to przyimek; spójnik to bevor.' },
      ],
    },
  },
  {
    id: 'genitiv',
    category: 'grammatik',
    title: 'Genitiv',
    titlePl: 'Dopełniacz',
    stages: ['rejonowy', 'wojewodzki'],
    priority: 2,
    evidence: 'Teksty o zabytkach (die Residenz des Fürstbischofs), pytania Wessen?, przyimki wegen/trotz.',
    lesson: {
      intro: 'Genitiv to znak precyzyjnego, pisanego niemieckiego. Rodzaj m/n: **des + -(e)s**; f/Pl: **der**. Imiona własne: **Goethes Werke**, **Ludwigs Schlösser**.',
      examples: [
        { de: 'Das ist das Schloss des Königs.' },
        { de: 'Trotz des Regens fand das Konzert statt.' },
        { de: 'Die Werke Goethes / Goethes Werke' },
        { de: 'Während der Ferien war ich in Tirol.' },
      ],
      pitfalls: ['Rzeczowniki jednosylabowe m/n: -es (des Hauses, des Mannes).', 'n-Deklination: des Jungen, des Studenten; wyjątek: des Namens, des Herzens.'],
      wrongRight: [
        { wrong: 'wegen dem Wetter', right: 'wegen des Wetters', why: 'W języku pisanym wegen + Genitiv.' },
        { wrong: 'das Haus des Mann', right: 'das Haus des Mannes', why: 'Genitiv m: -es.' },
      ],
    },
  },

  // ================= WORTSCHATZ =================
  {
    id: 'antonyme',
    category: 'wortschatz',
    title: 'Antonyme',
    titlePl: 'Antonimy (zad. 6 etapu szkolnego)',
    stages: ['szkolny'],
    priority: 1,
    evidence: 'Stałe zadanie 6 etapu szkolnego 2022-2025: 5 antonimów, pełna poprawność gramatyczna i ortograficzna.',
    lesson: {
      intro: 'Zadanie wygląda banalnie, ale punkt dostaje się tylko za **idealną formę**: antonim musi pasować do zdania gramatycznie (końcówka przymiotnika, forma czasownika, przedrostek).',
      table: {
        head: ['Słowo', 'Antonim', 'Uwaga'],
        rows: [
          ['teuer', 'billig / günstig', ''],
          ['hässlich', 'schön / hübsch', ''],
          ['langweilig', 'interessant / spannend', ''],
          ['leicht', 'schwer / schwierig', 'leicht (waga) → schwer'],
          ['voll', 'leer', ''],
          ['laut', 'leise', ''],
          ['früh', 'spät', ''],
          ['gewinnen', 'verlieren', 'hat gewonnen → hat verloren'],
          ['beginnen / anfangen', 'enden / aufhören', ''],
          ['öffnen / aufmachen', 'schließen / zumachen', ''],
          ['vergessen', 'sich erinnern', 'zmiana konstrukcji!'],
          ['erlauben', 'verbieten', 'erlaubt → verboten'],
          ['Viertel vor', 'Viertel nach', ''],
          ['vor dir', 'nach dir / hinter dir', 'kontekst!'],
          ['immer', 'nie', ''],
          ['alles', 'nichts', ''],
          ['jemand', 'niemand', ''],
          ['Frage', 'Antwort', ''],
          ['Anfang', 'Ende', ''],
          ['Freund', 'Feind', ''],
        ],
      },
      examples: [
        { de: 'Das ist ein teures Handy. → Das ist ein billiges Handy.', pl: 'końcówka -es zostaje!' },
        { de: 'Der Film endet um 20 Uhr. → Der Film beginnt um 20 Uhr.' },
      ],
      pitfalls: [
        'Przepisz **końcówkę**: „ein hässliches Bild” → „ein schönes Bild”.',
        'Zachowaj **osobę i czas**: „er hat gewonnen” → „er hat verloren”.',
        'Rzeczowniki z **wielką literą**, poprawne „ß/ss”, przegłosy.',
      ],
      wrongRight: [
        { wrong: 'ein teures Auto → ein billig Auto', right: 'ein billiges Auto', why: 'Końcówka przymiotnika.' },
        { wrong: 'Er schaltet den Fernseher ein → aus schaltet', right: 'Er schaltet den Fernseher aus.', why: 'Przedrostek na koniec.' },
      ],
    },
  },
  {
    id: 'wortbildung',
    category: 'wortschatz',
    title: 'Wortbildung',
    titlePl: 'Słowotwórstwo',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 6 rejonowe (formy słów z nawiasu), zad. 8 (uzupełnianie liter: Klassenausflug, Reisevorbereitungen).',
    lesson: {
      intro: 'Na etapie rejonowym trzeba **przekształcić słowo** w nawiasie w odpowiednią formę (rzeczownik, przymiotnik, liczba mnoga, stopień). Znajomość przyrostków daje też rodzaj!',
      table: {
        head: ['Przyrostek', 'Rodzaj / funkcja', 'Przykład'],
        rows: [
          ['-ung, -heit, -keit, -schaft, -ion, -tät', 'die', 'die Erfahrung, die Freiheit, die Möglichkeit'],
          ['-chen, -lein, -ment, -um', 'das', 'das Mädchen, das Museum'],
          ['-er, -ling, -ismus', 'der (zwykle)', 'der Lehrer, der Frühling'],
          ['-ig, -lich, -isch, -bar, -los, -voll', 'przymiotnik', 'sonnig, freundlich, praktisch, essbar, arbeitslos'],
          ['Kompositum', 'rodzaj = ostatni człon', 'die Klasse + der Ausflug = der Klassenausflug'],
        ],
      },
      examples: [
        { de: 'freundlich → die Freundlichkeit', pl: 'przymiotnik → rzeczownik' },
        { de: 'die Sonne → sonnig; das Glück → glücklich', pl: 'rzeczownik → przymiotnik' },
        { de: 'die Reise + die Vorbereitung → die Reisevorbereitungen', pl: 'Fugen-s/-n' },
      ],
      pitfalls: ['Łącznik -s-: Geburtstag, Arbeitsplatz; -n-: Klassenfahrt, Sonnenbrille.', 'Diminutyw zawsze das + często przegłos: das Häuschen, das Kleidchen.'],
      wrongRight: [
        { wrong: 'die Freundlichheit', right: 'die Freundlichkeit', why: 'Po -lich → -keit.' },
        { wrong: 'der Klasseausflug', right: 'der Klassenausflug', why: 'Łącznik -n-.' },
      ],
    },
  },
  {
    id: 'kollokationen',
    category: 'wortschatz',
    title: 'Kollokationen & Wendungen',
    titlePl: 'Związki wyrazowe',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 5 szkolny 2024/25 (Lust auf), zad. 7 teksty z lukami (wybór leksykalny), zad. 4 rejonowy (idiomy).',
    lesson: {
      intro: 'Płynny mówca zna te zwroty „na ucho”, ale w wersji pisanej łatwo o kalkę z polskiego lub angielskiego. Konkurs lubi wybór **właściwego czasownika** do rzeczownika.',
      table: {
        head: ['Zwrot', 'Znaczenie'],
        rows: [
          ['eine Entscheidung treffen', 'podjąć decyzję'],
          ['eine Frage stellen', 'zadać pytanie'],
          ['Lust auf etwas haben', 'mieć ochotę na coś'],
          ['eine Rolle spielen', 'odgrywać rolę'],
          ['Bescheid sagen / geben', 'dać znać'],
          ['in Frage kommen', 'wchodzić w grę'],
          ['eine Prüfung ablegen / bestehen', 'zdawać / zdać egzamin'],
          ['durch die Prüfung fallen', 'oblać egzamin'],
          ['Platz nehmen', 'usiąść'],
          ['Rücksicht nehmen auf', 'brać pod uwagę'],
          ['zur Verfügung stehen', 'być do dyspozycji'],
          ['ums Leben kommen', 'zginąć'],
          ['Wert legen auf', 'przykładać wagę do'],
          ['einen Vorschlag machen', 'złożyć propozycję'],
          ['recht haben', 'mieć rację'],
        ],
      },
      examples: [{ de: 'Hast du Lust auf eine Pizza?' }, { de: 'Kannst du mir Bescheid sagen, wenn du ankommst?' }],
      pitfalls: ['„eine Entscheidung machen” to kalka z angielskiego → treffen.', '„eine Prüfung machen/schreiben” = pisać, „bestehen” = zdać.'],
      wrongRight: [
        { wrong: 'eine Frage fragen', right: 'eine Frage stellen', why: 'Kolokacja.' },
        { wrong: 'Ich habe Lust für Eis.', right: 'Ich habe Lust auf Eis.', why: 'Lust auf + Akk.' },
      ],
    },
  },
  {
    id: 'rechtschreibung',
    category: 'wortschatz',
    title: 'Rechtschreibung',
    titlePl: 'Ortografia (ß/ss, wielkie litery)',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 8 rejonowy (uzupełnianie liter - pełna poprawność), zad. 10 (pisownia nazw własnych).',
    lesson: {
      intro: 'Konkurs wymaga „całkowitej poprawności ortograficznej”. Osoba, która dużo mówi, a mniej pisze, traci tu punkty najczęściej.',
      rules: [
        { title: 'ß czy ss', body: 'Po **długiej** samogłosce i dyftongu → ß (die Straße, groß, heißen, der Fuß). Po **krótkiej** → ss (der Fluss, dass, essen, wissen, das Schloss).' },
        { title: 'das / dass', body: '**dass** = spójnik („że”); **das** = rodzajnik lub zaimek (można zastąpić „dieses/welches”).' },
        { title: 'Wielkie litery', body: 'Rzeczowniki i rzeczowniki odczasownikowe: **das Lesen**, **beim Essen**, **etwas Neues**, **am Montag**, ale **montags** (przysłówek).' },
        { title: 'Nazwy geograficzne', body: 'der Bodensee, die Zugspitze, der Schwarzwald, Nordrhein-Westfalen, Mecklenburg-Vorpommern, Baden-Württemberg; mieszkańcy: Wiener Schnitzel (przymiotnik od miasta -er zawsze wielką literą).' },
      ],
      examples: [{ de: 'Ich weiß, dass das Schloss groß ist.' }, { de: 'Wir essen Wiener Würstchen und Berliner Pfannkuchen.' }],
      pitfalls: ['„Schloß” to stara pisownia → **Schloss**.', 'Przymiotniki od narodowości małą literą: deutsch, österreichisch - ale **Deutsch** jako język w roli rzeczownika („auf Deutsch”).'],
      wrongRight: [
        { wrong: 'Ich glaube, das er kommt.', right: 'Ich glaube, dass er kommt.', why: 'Spójnik → dass.' },
        { wrong: 'die Strasse', right: 'die Straße', why: 'W Niemczech/Austrii ß (w Szwajcarii zawsze ss - ale na konkursie standard niemiecki).' },
      ],
    },
  },

  // ================= LESEN / REAKTIONEN / SCHREIBEN =================
  {
    id: 'lesen-strategien',
    category: 'lesen',
    title: 'Lesestrategien',
    titlePl: 'Strategie czytania',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 1-2 każdego etapu: P/F, luki zdaniowe (2 dystraktory), nagłówki (2 zbędne).',
    lesson: {
      intro: 'Adam czyta szybko - ryzyko to **czytanie „ogólnego sensu”**. Konkurs ukrywa pułapki w szczegółach: liczby, przeczenia, „nur/auch/noch nicht”, osoba wykonująca czynność.',
      rules: [
        { title: 'Richtig/Falsch', body: 'Szukaj fragmentu i porównaj **słowo po słowie**. Stwierdzenie prawie prawdziwe = Falsch. Uważaj na: immer/manchmal, alle/einige, schon/noch nicht, zmianę osoby.' },
        { title: 'Luki zdaniowe', body: 'Patrz na **słowa-łączniki** przed i po luce: zaimki (er, sie, das, dort), spójniki (aber, deshalb, denn), czas. Zdanie-dystraktor zwykle pasuje tematycznie, ale nie logicznie.' },
        { title: 'Nagłówki', body: 'Najpierw przeczytaj wszystkie nagłówki, potem teksty. Nagłówek = **główna myśl**, nie pojedyncze słowo z tekstu (słowo powtórzone z tekstu to często pułapka).' },
      ],
      examples: [],
      pitfalls: ['Słowo z tekstu powtórzone w odpowiedzi to często pułapka.', 'Nie odpowiadaj z wiedzy ogólnej - liczy się tylko tekst.'],
      wrongRight: [],
    },
  },
  {
    id: 'reaktionen-alltag',
    category: 'reaktionen',
    title: 'Reaktionen im Alltag',
    titlePl: 'Reakcje w sytuacjach dnia codziennego',
    stages: ['szkolny', 'rejonowy'],
    priority: 1,
    evidence: 'Zad. 4 szkolny (3 sytuacje) i zad. 3 rejonowy (6 sytuacji): odmowa, współczucie, rada, prośba, zaproszenie, zdziwienie.',
    lesson: {
      intro: 'Opis sytuacji jest po polsku, odpowiedzi po niemiecku. Wszystkie trzy opcje są często **gramatycznie poprawne** - wybierasz tę, która pasuje do **intencji** i **rejestru** (du/Sie).',
      table: {
        head: ['Funkcja', 'Typowe zwroty'],
        rows: [
          ['Odmowa (uprzejma)', 'Nein danke, ich bin schon satt. / Leider kann ich nicht, ich habe schon etwas vor.'],
          ['Współczucie', 'Das tut mir leid! / So ein Pech! / Kopf hoch, das nächste Mal klappt es bestimmt.'],
          ['Prośba o radę', 'Was würdest du mir empfehlen? / Was meinst du, soll ich ...?'],
          ['Rada', 'An deiner Stelle würde ich ... / Du solltest ... / Wie wäre es mit ...?'],
          ['Prośba o powtórzenie', 'Wie bitte? / Könnten Sie das bitte wiederholen?'],
          ['Zgoda / niezgoda', 'Da hast du recht. / Da bin ich anderer Meinung. / Das sehe ich anders.'],
          ['Zdziwienie', 'Wirklich? / Das gibt es doch nicht! / Echt?'],
          ['Radość', 'Toll! / Das freut mich! / Super, das ist ja fantastisch!'],
          ['Gratulacje', 'Herzlichen Glückwunsch! / Gratuliere!'],
          ['Przeprosiny', 'Entschuldigung, das war keine Absicht. / Es tut mir leid, dass ich zu spät komme.'],
          ['Zachęta', 'Du schaffst das! / Nur Mut! / Gib nicht auf!'],
          ['Pytanie o drogę', 'Entschuldigung, wie komme ich zum Bahnhof?'],
          ['Zakaz', 'Hier darf man nicht fotografieren. / Das ist leider nicht erlaubt.'],
        ],
      },
      examples: [{ de: '— Möchtest du noch ein Stück Kuchen? — Nein danke, ich bin schon satt.' }],
      pitfalls: [
        'Rejestr: do obcego dorosłego, w urzędzie, w sklepie → **Sie**; do kolegi → du.',
        '„Gute Besserung!” = życzenie zdrowia (chory), nie „Viel Glück!”.',
        '„Mahlzeit!”, „Guten Appetit!” - przy jedzeniu; „Prost!” - przy toaście.',
        'Uważaj na odpowiedzi „na temat”, ale na **inne pytanie** (np. odpowiedź o czasie na pytanie o miejsce).',
      ],
      wrongRight: [
        { wrong: '(kolega oblał egzamin) Herzlichen Glückwunsch!', right: 'Das tut mir leid. Nächstes Mal klappt es bestimmt!', why: 'Współczucie, nie gratulacje.' },
        { wrong: '(pani w kasie) Kannst du mir helfen?', right: 'Können Sie mir bitte helfen?', why: 'Rejestr formalny.' },
      ],
    },
  },
  {
    id: 'email',
    category: 'schreiben',
    title: 'E-Mail & Blogeintrag',
    titlePl: 'E-mail / wpis na blogu (zad. 9)',
    stages: ['szkolny'],
    priority: 1,
    evidence: 'Zad. 9 etapu szkolnego 2022-2025: 3 punkty treści (każdy rozwinięty = 1 pkt) + poprawność: ≤5 błędów = 2 pkt, 6-10 = 1 pkt, >10 = 0 pkt. Podpis XYZ.',
    lesson: {
      intro: 'To 5 punktów z 40 - czyli 12,5% wyniku. Ocenia się: **3 elementy treści** (każdy musi być **rozwinięty**, nie tylko wspomniany) i **poprawność** (maks. 5 błędów = 2 pkt). Długość nie jest podana, ale praktycznie 60-100 słów wystarcza. Dłużej = więcej okazji do błędów.',
      rules: [
        { title: 'Struktura', body: 'Anrede → 1 zdanie wstępu → punkt 1 (2 zdania) → punkt 2 (2 zdania) → punkt 3 (2 zdania) → zakończenie → Gruß → **XYZ** (nigdy własne imię!).' },
        { title: 'Rozwinięcie = 2 zdania', body: 'Informacja + szczegół/uzasadnienie. „Das Hotel war toll.” to za mało. „Das Hotel lag direkt am Strand und hatte einen großen Pool, deshalb waren wir jeden Tag schwimmen.” - rozwinięte.' },
        { title: 'Bezpieczna gramatyka', body: 'Pisz zdaniami, które na 100% umiesz: weil/dass/wenn, Perfekt, modalne. Nie eksperymentuj z konstrukcjami, których nie jesteś pewien.' },
        { title: 'Kontrola', body: 'Przeczytaj 2 razy: raz pod kątem czasowników (pozycja, forma), raz pod kątem końcówek i wielkich liter.' },
      ],
      table: {
        head: ['Element', 'Nieformalnie', 'Formalnie'],
        rows: [
          ['Anrede', 'Liebe Anna, / Lieber Tom, / Hallo Max,', 'Sehr geehrte Frau Schmidt, / Sehr geehrter Herr Braun,'],
          ['Wstęp', 'danke für deine Mail! / Wie geht es dir?', 'ich schreibe Ihnen, weil ...'],
          ['Zakończenie', 'Schreib mir bald! / Ich freue mich auf deine Antwort.', 'Ich freue mich auf Ihre Antwort.'],
          ['Gruß', 'Viele Grüße / Liebe Grüße / Bis bald', 'Mit freundlichen Grüßen'],
        ],
      },
      examples: [
        { de: 'Liebe Lena,\nvielen Dank für deinen Besuch letzte Woche! Es war wirklich toll mit dir.' },
      ],
      pitfalls: [
        'Po przecinku w nagłówku („Liebe Lena,”) piszemy **małą literą**: „vielen Dank...”.',
        'Brak jednego z 3 punktów = strata punktu treści, nawet jeśli reszta jest świetna.',
        'Podpis: **XYZ** - własne imię może skutkować dyskwalifikacją pracy (anonimowość).',
        'Blog = zwracasz się do wielu czytelników: „Liebe Leserinnen und Leser,” / „ihr”.',
      ],
      wrongRight: [
        { wrong: 'Liebe Lena,\nVielen Dank...', right: 'Liebe Lena,\nvielen Dank...', why: 'Po przecinku - mała litera.' },
        { wrong: 'Sehr geehrter Frau Schmidt', right: 'Sehr geehrte Frau Schmidt', why: 'Frau → geehrte.' },
        { wrong: 'Mit freundlichen Grüße', right: 'Mit freundlichen Grüßen', why: 'Dativ Plural.' },
      ],
    },
  },

  // ================= LANDESKUNDE =================
  {
    id: 'lk-deutschland',
    category: 'landeskunde',
    title: 'Deutschland',
    titlePl: 'Niemcy: geografia i Bundesländer',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 8 szkolny co roku (Zugspitze, największa wyspa, rzeka Berlina), zad. 9-10 rejonowy 2025/26 (stolice krajów związkowych).',
  },
  {
    id: 'lk-oesterreich',
    category: 'landeskunde',
    title: 'Österreich',
    titlePl: 'Austria',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 8 szkolny: liczba krajów związkowych Austrii, rzeka Wiednia, Mozartkugel.',
  },
  {
    id: 'lk-schweiz',
    category: 'landeskunde',
    title: 'Schweiz & Liechtenstein',
    titlePl: 'Szwajcaria i Liechtenstein',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zad. 8 szkolny: nazwa oficjalna (Schweizerische Eidgenossenschaft), liczba kantonów, Käsefondue.',
  },
  {
    id: 'lk-geschichte',
    category: 'landeskunde',
    title: 'Geschichte',
    titlePl: 'Historia',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Zjednoczenie 1990, upadek muru 1989, NRD (rejonowy 2023/24), Luter, Willy Brandt (wojewódzki 2025/26).',
  },
  {
    id: 'lk-kultur',
    category: 'landeskunde',
    title: 'Kultur & Persönlichkeiten',
    titlePl: 'Kultura i znane postacie',
    stages: ['szkolny', 'rejonowy', 'wojewodzki'],
    priority: 1,
    evidence: 'Gutenberg, Goethe/Faust, kompozytorzy (Bach, Wagner, Beethoven), nobliści, święta i tradycje.',
  },

  // ================= UNESCO =================
  {
    id: 'unesco-grundlagen',
    category: 'unesco',
    title: 'UNESCO-Welterbe: Grundlagen',
    titlePl: 'Czym jest Światowe Dziedzictwo',
    stages: ['rejonowy'],
    priority: 1,
    evidence: 'Program 2026/27, etap rejonowy: „wybrane obiekty światowego dziedzictwa kulturowego UNESCO w Niemczech”.',
  },
  {
    id: 'unesco-objekte',
    category: 'unesco',
    title: 'Welterbestätten in Deutschland',
    titlePl: 'Obiekty UNESCO w Niemczech',
    stages: ['rejonowy'],
    priority: 1,
    evidence: 'Program 2026/27: historia, położenie, przynależność do krajów związkowych, walory, ciekawostki.',
  },
  {
    id: 'unesco-wortschatz',
    category: 'unesco',
    title: 'Wortschatz: Kultur & Reisen',
    titlePl: 'Słownictwo: kultura, turystyka, przyroda',
    stages: ['rejonowy'],
    priority: 2,
    evidence: 'Program 2026/27: słownictwo - kultura (obiekty kultury materialnej, twórcy i ich dzieła), podróżowanie i turystyka, przyroda.',
  },

  // ================= NATUR / HÖREN =================
  {
    id: 'naturdenkmale',
    category: 'natur',
    title: 'Naturdenkmale & Nationalparks',
    titlePl: 'Pomniki przyrody i parki narodowe',
    stages: ['wojewodzki'],
    priority: 1,
    evidence: 'Program 2026/27, etap wojewódzki: wybrane pomniki przyrody w Niemczech (historia, położenie, kraj związkowy, walory turystyczne).',
  },
  {
    id: 'hoeren-alltag',
    category: 'hoeren',
    title: 'Hörverstehen',
    titlePl: 'Rozumienie ze słuchu',
    stages: ['wojewodzki'],
    priority: 2,
    evidence: 'Wojewódzki 2025/26: zad. 1 (4 pkt, A-D) i zad. 2 (6 pkt, R/F), tekst słuchany dwukrotnie.',
  },
]

export const TOPIC_BY_ID: Record<string, Topic> = Object.fromEntries(TOPICS.map((t) => [t.id, t]))
