/**
 * UNESCO-Welterbe in Deutschland - baza wiedzy dla etapu rejonowego 2026/27.
 *
 * Program merytoryczny 2026/27 mówi o „wybranych obiektach światowego dziedzictwa kulturowego UNESCO
 * w Niemczech” i nie podaje zamkniętej listy. Dlatego:
 *  - core: true  → obiekt wprost opisany w źródłach wskazanych w programie (deutschland.de, weg.de,
 *                  welterbedeutschland.de, DW, kmk.org, geo.de) - PRIORYTET
 *  - core: false → pozostałe obiekty z oficjalnej listy (55 obiektów, stan 2025) - rozszerzenie
 * Dane (rok wpisu, kraj związkowy) zweryfikowane z listą UNESCO / KMK.
 */

export type SiteKind = 'kirche' | 'kloster' | 'schloss' | 'burg' | 'altstadt' | 'industrie' | 'moderne' | 'landschaft' | 'natur' | 'archaeologie' | 'garten'

export interface UnescoSite {
  id: string
  name: string // nazwa niemiecka
  namePl: string
  place: string
  lands: string[] // ISO DE-XX
  lat: number
  lon: number
  year: number
  extended?: string
  kind: SiteKind
  nature?: boolean
  core: boolean
  what: string // czym jest (PL)
  history: string // historia (PL)
  why: string // dlaczego UNESCO (PL)
  deutsch: string // krótko po niemiecku (2-3 zdania do nauki na pamięć)
  features: string[]
  facts: string[] // ciekawostki konkursowe
  vocab: [string, string][]
  keywords: string[] // do quizu „rozpoznaj obiekt”
}

export const LAND_NAMES: Record<string, string> = {
  'DE-BW': 'Baden-Württemberg',
  'DE-BY': 'Bayern',
  'DE-BE': 'Berlin',
  'DE-BB': 'Brandenburg',
  'DE-HB': 'Bremen',
  'DE-HH': 'Hamburg',
  'DE-HE': 'Hessen',
  'DE-MV': 'Mecklenburg-Vorpommern',
  'DE-NI': 'Niedersachsen',
  'DE-NW': 'Nordrhein-Westfalen',
  'DE-RP': 'Rheinland-Pfalz',
  'DE-SL': 'Saarland',
  'DE-SN': 'Sachsen',
  'DE-ST': 'Sachsen-Anhalt',
  'DE-SH': 'Schleswig-Holstein',
  'DE-TH': 'Thüringen',
}

export const KIND_LABEL: Record<SiteKind, string> = {
  kirche: 'Dom / Kirche',
  kloster: 'Kloster',
  schloss: 'Schloss / Residenz',
  burg: 'Burg',
  altstadt: 'Altstadt',
  industrie: 'Industriekultur',
  moderne: 'Moderne Architektur',
  landschaft: 'Kulturlandschaft',
  natur: 'Weltnaturerbe',
  archaeologie: 'Archäologie',
  garten: 'Park / Garten',
}

export const UNESCO_SITES: UnescoSite[] = [
  {
    id: 'aachen',
    name: 'Aachener Dom',
    namePl: 'Katedra w Akwizgranie',
    place: 'Aachen',
    lands: ['DE-NW'],
    lat: 50.775, lon: 6.084,
    year: 1978,
    kind: 'kirche',
    core: true,
    what: 'Katedra, której sercem jest ośmioboczna Kaplica Palatynalna (Pfalzkapelle) Karola Wielkiego.',
    history: 'Karol Wielki kazał zbudować kaplicę pod koniec VIII w. (poświęcona ok. 800-805). Został w niej pochowany w 814 r. Przez ok. 600 lat (936-1531) koronowano tu ok. 30 królów niemieckich. Gotyckie prezbiterium („szklana kaplica”) dobudowano w XIV-XV w.',
    why: 'Pierwszy niemiecki obiekt na liście UNESCO (1978). Arcydzieło architektury karolińskiej - symbol odnowienia cesarstwa na Zachodzie.',
    deutsch: 'Der Aachener Dom war 1978 die erste deutsche Welterbestätte. Karl der Große ließ die achteckige Pfalzkapelle um 800 bauen und wurde hier begraben. Über 600 Jahre lang wurden im Dom deutsche Könige gekrönt.',
    features: ['Oktogon (ośmiobok) - Pfalzkapelle', 'Tron Karola Wielkiego (Karlsthron)', 'Relikwiarz Karola (Karlsschrein) i Marii', 'Gotycka „szklana kaplica” z wysokimi witrażami'],
    facts: ['Najstarsza katedra w Północnej Europie', 'Pierwszy wpis Niemiec na listę UNESCO - 1978', 'Ok. 30 koronacji królów niemieckich'],
    vocab: [['die Pfalzkapelle', 'kaplica palatynalna'], ['das Achteck / Oktogon', 'ośmiobok'], ['krönen', 'koronować'], ['die Krönung', 'koronacja'], ['begraben', 'pochowany']],
    keywords: ['Karl der Große', 'Krönungskirche', 'Oktogon', 'erste deutsche Welterbestätte'],
  },
  {
    id: 'koeln',
    name: 'Kölner Dom',
    namePl: 'Katedra w Kolonii',
    place: 'Köln',
    lands: ['DE-NW'],
    lat: 50.941, lon: 6.958,
    year: 1996,
    kind: 'kirche',
    core: true,
    what: 'Gotycka katedra katolicka nad Renem, jeden z najczęściej odwiedzanych zabytków Niemiec.',
    history: 'Budowę rozpoczęto w 1248 r. Ok. 1520-1560 prace przerwano - przez stulecia na nieukończonej wieży stał drewniany dźwig. Budowę dokończono w XIX w. według odnalezionych średniowiecznych planów - zakończenie 1880. W latach 1880-1884 był najwyższą budowlą świata. Przetrwał II wojnę światową mimo wielu trafień bombami.',
    why: 'Wyjątkowe dzieło gotyku, budowane ponad 600 lat - świadectwo trwałości wiary i europejskiej tradycji architektonicznej. W latach 2004-2006 był na Czerwonej Liście zagrożonego dziedzictwa (plany wieżowców po drugiej stronie Renu).',
    deutsch: 'Der Bau des Kölner Doms begann 1248 und wurde erst 1880 vollendet. Die beiden Türme sind rund 157 Meter hoch. Im Dom befindet sich der Dreikönigenschrein. Seit 1996 gehört der Dom zum UNESCO-Welterbe.',
    features: ['Dwie wieże ok. 157 m', 'Relikwiarz Trzech Króli (Dreikönigenschrein)', '533 stopnie na platformę widokową wieży południowej', 'Okno Gerharda Richtera (2007)'],
    facts: ['Ok. 6 mln odwiedzających rocznie', 'Budowa trwała 632 lata (1248-1880)', 'Czerwona Lista UNESCO 2004-2006', 'W 1880 r. najwyższy budynek świata'],
    vocab: [['die Gotik', 'gotyk'], ['der Turm, die Türme', 'wieża'], ['vollenden', 'ukończyć'], ['der Schrein', 'relikwiarz'], ['das Wahrzeichen', 'symbol miasta']],
    keywords: ['1248', '1880', 'Dreikönigenschrein', 'zwei Türme', 'Rhein'],
  },
  {
    id: 'speyer',
    name: 'Dom zu Speyer',
    namePl: 'Katedra w Spirze',
    place: 'Speyer',
    lands: ['DE-RP'],
    lat: 49.317, lon: 8.442,
    year: 1981,
    kind: 'kirche',
    core: true,
    what: 'Cesarska katedra romańska nad Renem - największy zachowany kościół romański na świecie.',
    history: 'Budowę zapoczątkował cesarz Konrad II z dynastii salickiej ok. 1030 r. Katedra stała się miejscem pochówku cesarzy i królów niemieckich (8 władców). Wielokrotnie niszczona (m.in. 1689) i odbudowywana.',
    why: 'Jedno z najważniejszych dzieł architektury romańskiej, symbol władzy cesarskiej w średniowieczu.',
    deutsch: 'Der Dom zu Speyer ist die größte erhaltene romanische Kirche der Welt. Kaiser Konrad II. begann den Bau um 1030. In der Krypta liegen acht deutsche Kaiser und Könige begraben.',
    features: ['Styl romański (Romanik)', 'Krypta - największa sala romańska', 'Groby cesarzy salickich'],
    facts: ['Największy zachowany kościół romański świata', 'Kaiserdom - „katedra cesarska”', 'Wpis 1981'],
    vocab: [['die Romanik', 'romanizm'], ['die Krypta', 'krypta'], ['der Kaiser', 'cesarz'], ['das Grab', 'grób']],
    keywords: ['größte romanische Kirche', 'Kaisergräber', 'Salier', 'Konrad II.'],
  },
  {
    id: 'maulbronn',
    name: 'Kloster Maulbronn',
    namePl: 'Klasztor Maulbronn',
    place: 'Maulbronn',
    lands: ['DE-BW'],
    lat: 49.0, lon: 8.813,
    year: 1993,
    kind: 'kloster',
    core: true,
    what: 'Średniowieczny klasztor cystersów - najlepiej zachowany zespół klasztorny na północ od Alp.',
    history: 'Założony w 1147 r. przez cystersów. Po reformacji (1556) działała tu szkoła protestancka - uczył się w niej m.in. poeta Hermann Hesse (powieść „Unterm Rad”) i astronom Johannes Kepler.',
    why: 'Kompletny, otoczony murami zespół klasztorny z budynkami gospodarczymi i systemem wodnym - pokazuje życie cystersów.',
    deutsch: 'Kloster Maulbronn in Baden-Württemberg wurde 1147 von Zisterziensermönchen gegründet. Es ist die am besten erhaltene mittelalterliche Klosteranlage nördlich der Alpen. Hermann Hesse war hier Schüler.',
    features: ['Krużganek (Kreuzgang)', 'Studnia klasztorna w kaplicy (Brunnenhaus)', 'Mury obronne i budynki gospodarcze'],
    facts: ['Legenda: mnisi wymyślili tu Maultaschen, żeby „ukryć” mięso przed Bogiem w poście („Herrgottsbscheißerle”)', 'Hermann Hesse i Johannes Kepler byli uczniami szkoły klasztornej'],
    vocab: [['das Kloster', 'klasztor'], ['der Mönch', 'mnich'], ['der Kreuzgang', 'krużganek'], ['die Zisterzienser', 'cystersi']],
    keywords: ['Zisterzienser', 'Maultaschen', 'Hermann Hesse', '1147'],
  },
  {
    id: 'luther',
    name: 'Luthergedenkstätten in Eisleben und Wittenberg',
    namePl: 'Miejsca pamięci Lutra w Eisleben i Wittenberdze',
    place: 'Lutherstadt Eisleben, Lutherstadt Wittenberg',
    lands: ['DE-ST'],
    lat: 51.866, lon: 12.646,
    year: 1996,
    kind: 'altstadt',
    core: true,
    what: 'Domy i kościoły związane z życiem Marcina Lutra i reformacją.',
    history: 'Luter urodził się (1483) i zmarł (1546) w Eisleben. W Wittenberdze wykładał na uniwersytecie i w 1517 r. ogłosił 95 tez - według tradycji przybił je do drzwi Kościoła Zamkowego. Początek reformacji.',
    why: 'Autentyczne miejsca jednego z najważniejszych wydarzeń w historii Europy - reformacji.',
    deutsch: 'Die Luthergedenkstätten liegen in Sachsen-Anhalt. In Eisleben wurde Martin Luther 1483 geboren und starb dort 1546. In Wittenberg veröffentlichte er 1517 seine 95 Thesen.',
    features: ['Dom urodzenia i dom śmierci Lutra (Eisleben)', 'Lutherhaus i Melanchthonhaus (Wittenberga)', 'Kościół Zamkowy z „drzwiami tez” (Thesentür)', 'Kościół Miejski - kościół kaznodziejski Lutra'],
    facts: ['Obie miejscowości noszą oficjalnie przydomek „Lutherstadt”', 'Lutherhaus - największe muzeum reformacji na świecie'],
    vocab: [['die Reformation', 'reformacja'], ['die These', 'teza'], ['die Gedenkstätte', 'miejsce pamięci'], ['predigen', 'wygłaszać kazania']],
    keywords: ['95 Thesen', '1517', 'Martin Luther', 'Reformation'],
  },
  {
    id: 'wartburg',
    name: 'Wartburg',
    namePl: 'Zamek Wartburg',
    place: 'Eisenach',
    lands: ['DE-TH'],
    lat: 50.966, lon: 10.307,
    year: 1999,
    kind: 'burg',
    core: true,
    what: 'Średniowieczny zamek na wzgórzu nad Eisenach - symbol historii Niemiec.',
    history: 'Według legendy założona ok. 1067 r. przez Ludwika Skoczka („Wart, Berg, du sollst mir eine Burg werden!”). Mieszkała tu św. Elżbieta Węgierska. W 1521/22 Luter, ukrywając się jako „Junker Jörg”, przetłumaczył tu Nowy Testament na niemiecki. W 1817 r. odbył się tu Wartburgfest studentów - ważny dla ruchu narodowego i barw czarno-czerwono-złotych.',
    why: 'Wybitny przykład zamku feudalnego i miejsce wydarzeń ważnych dla kultury niemieckiej (język, reformacja, jedność narodowa).',
    deutsch: 'Die Wartburg bei Eisenach in Thüringen wurde um 1067 gegründet. Hier übersetzte Martin Luther 1521/22 das Neue Testament ins Deutsche. 1817 feierten Studenten hier das Wartburgfest.',
    features: ['Izba Lutra (Lutherstube)', 'Pałac romański (Palas)', 'Sala Śpiewaków - legenda o Sängerkrieg'],
    facts: ['Tłumaczenie Lutra ujednoliciło język niemiecki', 'Wartburgfest 1817 - barwy czarno-czerwono-złote', 'Legenda o kałamarzu rzuconym w diabła'],
    vocab: [['die Burg', 'zamek (obronny)'], ['übersetzen', 'tłumaczyć'], ['das Neue Testament', 'Nowy Testament'], ['sich verstecken', 'ukrywać się']],
    keywords: ['Eisenach', 'Luther übersetzte die Bibel', 'Junker Jörg', 'Wartburgfest'],
  },
  {
    id: 'luebeck',
    name: 'Hansestadt Lübeck',
    namePl: 'Hanzeatyckie miasto Lubeka',
    place: 'Lübeck',
    lands: ['DE-SH'],
    lat: 53.866, lon: 10.686,
    year: 1987,
    kind: 'altstadt',
    core: true,
    what: 'Stare miasto na wyspie, dawna „królowa Hanzy”.',
    history: 'Założona w 1143 r., stała się stolicą Związku Hanzeatyckiego (Hanse) - potężnego związku miast kupieckich. Bogactwo kupców widać w ceglanych kościołach i kamienicach.',
    why: 'Pierwsze całe stare miasto w Europie Północnej wpisane na listę (1987); wzór dla gotyku ceglanego (Backsteingotik) w regionie Bałtyku.',
    deutsch: 'Lübeck war im Mittelalter die „Königin der Hanse“. Die Altstadt liegt auf einer Insel und ist seit 1987 Welterbe. Das Holstentor ist das Wahrzeichen der Stadt.',
    features: ['Holstentor - brama miejska', 'Marienkirche - wzór dla kościołów gotyku ceglanego', 'Ratusz', 'Buddenbrookhaus (Thomas Mann)'],
    facts: ['Słynie z marcepanu (Lübecker Marzipan)', 'Miasto trzech noblistów: Thomas Mann, Willy Brandt, Günter Grass (związany z Lubeką)'],
    vocab: [['die Hanse', 'Hanza'], ['der Kaufmann', 'kupiec'], ['die Backsteingotik', 'gotyk ceglany'], ['das Tor', 'brama']],
    keywords: ['Holstentor', 'Königin der Hanse', 'Marzipan', 'Backsteingotik'],
  },
  {
    id: 'stralsund-wismar',
    name: 'Historische Altstädte Stralsund und Wismar',
    namePl: 'Stare miasta Stralsundu i Wismaru',
    place: 'Stralsund, Wismar',
    lands: ['DE-MV'],
    lat: 54.315, lon: 13.09,
    year: 2002,
    kind: 'altstadt',
    core: true,
    what: 'Dwa hanzeatyckie miasta portowe nad Bałtykiem z gotykiem ceglanym.',
    history: 'Rozkwit w średniowieczu dzięki Hanzie. Po wojnie trzydziestoletniej (1648) przez ok. 150-200 lat należały do Szwecji - stąd szwedzkie wpływy.',
    why: 'Doskonale zachowane średniowieczne układy miast hanzeatyckich i architektura ceglana.',
    deutsch: 'Stralsund und Wismar in Mecklenburg-Vorpommern sind alte Hansestädte an der Ostsee. Nach dem Dreißigjährigen Krieg gehörten sie lange zu Schweden. Seit 2002 sind sie gemeinsam Welterbe.',
    features: ['Ratusz w Stralsundzie z fasadą ozdobną', 'Kościoły ceglane (St. Nikolai, St. Marien)', 'Ozeaneum w Stralsundzie'],
    facts: ['Okres szwedzki: Wismar do 1803 (formalnie 1903), Stralsund do 1815'],
    vocab: [['die Hansestadt', 'miasto hanzeatyckie'], ['der Hafen', 'port'], ['der Giebel', 'szczyt domu']],
    keywords: ['Schweden', 'Ostsee', 'Hansestädte', 'Backstein'],
  },
  {
    id: 'regensburg',
    name: 'Altstadt von Regensburg mit Stadtamhof',
    namePl: 'Stare miasto w Ratyzbonie',
    place: 'Regensburg',
    lands: ['DE-BY'],
    lat: 49.019, lon: 12.097,
    year: 2006,
    kind: 'altstadt',
    core: true,
    what: 'Średniowieczne miasto nad Dunajem, niemal nienaruszone przez wojnę.',
    history: 'Rzymski obóz Castra Regina (179 r.). W średniowieczu ważny ośrodek handlu. W latach 1663-1806 obradował tu Wieczysty Sejm Rzeszy (Immerwährender Reichstag). Most Kamienny zbudowano w XII w. (ok. 1135-1146).',
    why: 'Największe w Niemczech zachowane średniowieczne stare miasto - świadectwo ponad 2000 lat historii.',
    deutsch: 'Die Altstadt von Regensburg liegt an der Donau und gehört seit 2006 zum Welterbe. Die Steinerne Brücke stammt aus dem 12. Jahrhundert. Im Zweiten Weltkrieg wurde die Stadt kaum zerstört.',
    features: ['Most Kamienny (Steinerne Brücke)', 'Katedra św. Piotra (gotyk)', 'Wieże patrycjuszowskie', 'Historische Wurstkuchl - jedna z najstarszych jadłodajni'],
    facts: ['Rzymski obóz z 179 r.', 'Wieczysty Sejm Rzeszy 1663-1806'],
    vocab: [['die Steinerne Brücke', 'Most Kamienny'], ['verschont bleiben', 'zostać oszczędzonym'], ['das Mittelalter', 'średniowiecze']],
    keywords: ['Steinerne Brücke', 'Donau', 'Reichstag', 'Castra Regina'],
  },
  {
    id: 'bauhaus',
    name: 'Das Bauhaus und seine Stätten in Weimar, Dessau und Bernau',
    namePl: 'Bauhaus i jego obiekty w Weimarze, Dessau i Bernau',
    place: 'Weimar, Dessau, Bernau',
    lands: ['DE-TH', 'DE-ST', 'DE-BB'],
    lat: 51.84, lon: 12.227,
    year: 1996,
    extended: '2017 (Bernau, Laubenganghäuser w Dessau)',
    kind: 'moderne',
    core: true,
    what: 'Budynki słynnej szkoły architektury i sztuki Bauhaus.',
    history: 'Szkołę założył Walter Gropius w 1919 r. w Weimarze. W 1925 r. przeniosła się do Dessau (słynny budynek ze szklaną fasadą), w 1932 do Berlina, gdzie w 1933 r. zamknięto ją pod presją nazistów.',
    why: 'Bauhaus zrewolucjonizował architekturę i design XX w. - funkcjonalność, proste formy, nowe materiały (szkło, stal, beton).',
    deutsch: 'Das Bauhaus wurde 1919 von Walter Gropius in Weimar gegründet und zog 1925 nach Dessau. Die Schule prägte die moderne Architektur und das Design weltweit. 1933 musste sie schließen.',
    features: ['Budynek Bauhausu w Dessau (szklana ściana kurtynowa)', 'Domy Mistrzów (Meisterhäuser)', 'Haus am Horn w Weimarze', 'Szkoła związków zawodowych ADGB w Bernau'],
    facts: ['Zasada: forma wynika z funkcji', '2019 - 100-lecie Bauhausu', 'Nauczyciele: Paul Klee, Wassily Kandinsky'],
    vocab: [['die Architektur', 'architektura'], ['das Design', 'wzornictwo'], ['gründen', 'założyć'], ['schlicht', 'prosty, skromny']],
    keywords: ['Walter Gropius', '1919', 'Dessau', 'Design'],
  },
  {
    id: 'berliner-moderne',
    name: 'Siedlungen der Berliner Moderne',
    namePl: 'Osiedla berlińskiego modernizmu',
    place: 'Berlin',
    lands: ['DE-BE'],
    lat: 52.452, lon: 13.448,
    year: 2008,
    extended: '2026 (Waldsiedlung Zehlendorf - wg KMK)',
    kind: 'moderne',
    core: true,
    what: 'Nowoczesne osiedla mieszkaniowe z lat 1910-1933, m.in. Hufeisensiedlung i Großsiedlung Siemensstadt.',
    history: 'Po I wojnie światowej w Berlinie brakowało tanich, zdrowych mieszkań. Architekci (m.in. Bruno Taut) budowali jasne, kolorowe osiedla z zielenią dla robotników.',
    why: 'Nowy typ budownictwa socjalnego, który wpłynął na architekturę mieszkaniową na całym świecie.',
    deutsch: 'Die Siedlungen der Berliner Moderne entstanden zwischen 1910 und 1933. Sie boten Arbeiterfamilien helle und gesunde Wohnungen mit Gärten. Bekannt ist die Hufeisensiedlung in Britz.',
    features: ['Hufeisensiedlung Britz (w kształcie podkowy)', 'Großsiedlung Siemensstadt', 'Gartenstadt Falkenberg („Tuszkastensiedlung” - kolorowe fasady)', 'Weiße Stadt'],
    facts: ['Architekt Bruno Taut', 'Mieszkania są zamieszkane do dziś'],
    vocab: [['die Siedlung', 'osiedle'], ['das Hufeisen', 'podkowa'], ['die Wohnung', 'mieszkanie']],
    keywords: ['Hufeisensiedlung', 'Siemensstadt', 'Bruno Taut', 'Wohnungen für Arbeiter'],
  },
  {
    id: 'weissenhof',
    name: 'Weißenhofsiedlung (Le Corbusier)',
    namePl: 'Osiedle Weißenhof - domy Le Corbusiera',
    place: 'Stuttgart',
    lands: ['DE-BW'],
    lat: 48.8, lon: 9.177,
    year: 2016,
    kind: 'moderne',
    core: true,
    what: 'Dwa domy Le Corbusiera na wzorcowym osiedlu Weißenhof - część międzynarodowego wpisu „Dzieło architektoniczne Le Corbusiera”.',
    history: 'Osiedle zbudowano w 1927 r. na wystawę Deutscher Werkbund pod kierunkiem Ludwiga Miesa van der Rohe. Budowało je 17 architektów z kilku krajów.',
    why: 'Wpis transgraniczny (7 krajów, 17 obiektów) - wkład Le Corbusiera w ruch nowoczesny.',
    deutsch: 'Die Weißenhofsiedlung in Stuttgart entstand 1927 für eine Bauausstellung. Zwei Häuser von Le Corbusier gehören seit 2016 zum Welterbe.',
    features: ['Płaskie dachy, białe fasady', 'Weißenhofmuseum w domu Le Corbusiera'],
    facts: ['Wpis obejmuje obiekty w 7 krajach na 3 kontynentach'],
    vocab: [['die Ausstellung', 'wystawa'], ['das Flachdach', 'płaski dach']],
    keywords: ['Le Corbusier', 'Stuttgart', '1927', 'Werkbund'],
  },
  {
    id: 'potsdam',
    name: 'Schlösser und Parks von Potsdam und Berlin',
    namePl: 'Pałace i parki Poczdamu i Berlina (Sanssouci)',
    place: 'Potsdam, Berlin',
    lands: ['DE-BB', 'DE-BE'],
    lat: 52.404, lon: 13.038,
    year: 1990,
    extended: '1992, 1999',
    kind: 'schloss',
    core: true,
    what: 'Zespół pałaców i parków królów pruskich, z pałacem Sanssouci na czele.',
    history: 'Fryderyk Wielki kazał zbudować w latach 1745-1747 letni pałac Sanssouci (fr. „bez trosk”). Później powstały m.in. Nowy Pałac i Cecilienhof, gdzie w 1945 r. odbyła się konferencja poczdamska.',
    why: 'Wyjątkowy zespół architektury i sztuki ogrodowej XVIII-XIX w. - „pruski Wersal”.',
    deutsch: 'Schloss Sanssouci in Potsdam ließ Friedrich der Große 1745-1747 als Sommerschloss bauen. Der Name bedeutet auf Französisch „ohne Sorge“. Im Schloss Cecilienhof fand 1945 die Potsdamer Konferenz statt.',
    features: ['Sanssouci z tarasami winnic', 'Nowy Pałac (Neues Palais)', 'Cecilienhof', 'Most Glienicke - „most szpiegów”'],
    facts: ['Na grobie Fryderyka Wielkiego ludzie kładą ziemniaki - rozpowszechnił uprawę ziemniaków w Prusach', 'Największy obiekt UNESCO w Niemczech pod względem liczby budowli'],
    vocab: [['das Sommerschloss', 'pałac letni'], ['der Weinberg', 'winnica'], ['die Sorge', 'troska'], ['preußisch', 'pruski']],
    keywords: ['ohne Sorge', 'Friedrich der Große', 'Potsdamer Konferenz', 'Kartoffeln'],
  },
  {
    id: 'zollverein',
    name: 'Zeche Zollverein',
    namePl: 'Kopalnia Zollverein',
    place: 'Essen',
    lands: ['DE-NW'],
    lat: 51.486, lon: 7.047,
    year: 2001,
    kind: 'industrie',
    core: true,
    what: 'Dawna kopalnia węgla kamiennego i koksownia w Zagłębiu Ruhry.',
    history: 'Działała od 1851 do 1986 r. (koksownia do 1993 r.). Szyb XII z 1932 r. w stylu Bauhausu nazywano „najpiękniejszą kopalnią świata”.',
    why: 'Symbol rozwoju przemysłu ciężkiego w Europie i wybitna architektura przemysłowa.',
    deutsch: 'Die Zeche Zollverein in Essen war von 1851 bis 1986 ein Steinkohlebergwerk. Der Schacht XII im Bauhaus-Stil gilt als „schönste Zeche der Welt“. Heute gibt es dort Museen und Veranstaltungen.',
    features: ['Wieża wyciągowa szybu XII (Doppelbock)', 'Ruhr Museum', 'Red Dot Design Museum', 'Lodowisko w koksowni zimą'],
    facts: ['„Najpiękniejsza kopalnia świata”', 'Symbol przemiany Zagłębia Ruhry: od przemysłu do kultury'],
    vocab: [['die Zeche', 'kopalnia'], ['die Kohle', 'węgiel'], ['der Bergbau', 'górnictwo'], ['der Schacht', 'szyb'], ['stilllegen', 'wyłączyć z eksploatacji']],
    keywords: ['Ruhrgebiet', 'Steinkohle', 'Schacht XII', 'schönste Zeche der Welt'],
  },
  {
    id: 'voelklingen',
    name: 'Völklinger Hütte',
    namePl: 'Huta Völklingen',
    place: 'Völklingen',
    lands: ['DE-SL'],
    lat: 49.245, lon: 6.841,
    year: 1994,
    kind: 'industrie',
    core: true,
    what: 'Kompletnie zachowana huta żelaza z okresu industrializacji.',
    history: 'Huta działała od 1873 do 1986 r. Produkowała surówkę żelaza (Roheisen). Po zamknięciu stała się muzeum i miejscem wystaw.',
    why: 'Pierwszy zabytek przemysłowy z epoki industrializacji wpisany na listę UNESCO - jedyna na świecie w pełni zachowana huta z XIX/XX w.',
    deutsch: 'Die Völklinger Hütte im Saarland produzierte von 1873 bis 1986 Roheisen. Sie war das erste Industriedenkmal aus der Zeit der Industrialisierung auf der Welterbeliste. Heute kann man auf die Hochöfen steigen.',
    features: ['Wielkie piece (Hochöfen) z platformą widokową', 'Hala dmuchaw (Gebläsehalle)', 'Park ogród „Paradies”'],
    facts: ['Powierzchnia ok. 600 000 m²', 'Wystawy sztuki współczesnej'],
    vocab: [['die Hütte / das Eisenwerk', 'huta'], ['der Hochofen', 'wielki piec'], ['das Roheisen', 'surówka'], ['das Industriedenkmal', 'zabytek przemysłowy']],
    keywords: ['Saarland', 'Roheisen', 'Hochofen', 'erstes Industriedenkmal'],
  },
  {
    id: 'speicherstadt',
    name: 'Speicherstadt und Kontorhausviertel mit Chilehaus',
    namePl: 'Speicherstadt i dzielnica biurowców z Chilehaus',
    place: 'Hamburg',
    lands: ['DE-HH'],
    lat: 53.543, lon: 9.99,
    year: 2015,
    kind: 'industrie',
    core: true,
    what: 'Największy na świecie zespół magazynów portowych na palach oraz dzielnica biurowców z cegły.',
    history: 'Speicherstadt zbudowano w latach 1883-1927 na dębowych palach na wyspach Łaby. Kontorhausviertel z Chilehaus (1922-1924, architekt Fritz Höger) powstał w latach 20. XX w.',
    why: 'Symbol rozwoju handlu międzynarodowego na przełomie XIX i XX w. i ekspresjonizmu ceglanego.',
    deutsch: 'Die Speicherstadt in Hamburg ist der größte historische Lagerhauskomplex der Welt. Sie steht auf Eichenpfählen. Das Chilehaus sieht aus wie ein Schiffsbug.',
    features: ['Magazyny z kanałami (Fleete)', 'Chilehaus w kształcie dziobu statku', 'Miniatur Wunderland - największa makieta kolejowa świata'],
    facts: ['Magazynowano tu kawę, herbatę, przyprawy, dywany', 'Chilehaus - nazwa od handlu saletrą z Chile'],
    vocab: [['der Speicher / das Lagerhaus', 'magazyn'], ['der Pfahl', 'pal'], ['der Bug', 'dziób statku'], ['der Hafen', 'port']],
    keywords: ['Hamburg', 'Lagerhäuser', 'Chilehaus', 'Eichenpfähle'],
  },
  {
    id: 'mittelrhein',
    name: 'Oberes Mittelrheintal',
    namePl: 'Dolina Środkowego Renu',
    place: 'Bingen – Rüdesheim – Koblenz',
    lands: ['DE-RP', 'DE-HE'],
    lat: 50.139, lon: 7.729,
    year: 2002,
    kind: 'landschaft',
    core: true,
    what: 'Ok. 65-kilometrowy odcinek doliny Renu z zamkami, winnicami i skałą Lorelei.',
    history: 'Od starożytności ważny szlak handlowy. W średniowieczu na wzgórzach powstały dziesiątki zamków (pobieranie cła od statków). W XIX w. dolina stała się symbolem romantyzmu.',
    why: 'Wyjątkowy krajobraz kulturowy - połączenie natury, zamków, winnic i miasteczek kształtowane przez 2000 lat.',
    deutsch: 'Das Obere Mittelrheintal zwischen Bingen und Koblenz ist etwa 65 Kilometer lang. Hier stehen über 40 Burgen und Schlösser. Berühmt ist der Loreley-Felsen, über den Heinrich Heine ein Gedicht schrieb.',
    features: ['Skała Lorelei (ok. 132 m)', 'Zamek Pfalzgrafenstein na wyspie koło Kaub', 'Marksburg - jedyny nigdy niezniszczony zamek na wzgórzu w dolinie', 'Winnice na stromych zboczach'],
    facts: ['Legenda: piękna Lorelei śpiewem rozpraszała żeglarzy', 'Wiersz Heinricha Heinego „Die Lore-Ley” (1824)', 'Niemcy rozważali most na tym odcinku - dyskusja o zagrożeniu statusu'],
    vocab: [['das Tal', 'dolina'], ['der Felsen', 'skała'], ['die Sage', 'legenda, podanie'], ['der Zoll', 'cło'], ['der Weinberg', 'winnica']],
    keywords: ['Loreley', 'Burgen', 'Wein', 'Bingen und Koblenz'],
  },
  {
    id: 'wattenmeer',
    name: 'Wattenmeer',
    namePl: 'Morze Wattowe',
    place: 'Nordseeküste',
    lands: ['DE-NI', 'DE-SH', 'DE-HH'],
    lat: 53.75, lon: 8.3,
    year: 2009,
    extended: '2014 (Dania)',
    kind: 'natur',
    nature: true,
    core: true,
    what: 'Największy na świecie ciągły obszar równi pływowych (watów) - wybrzeże Morza Północnego w Holandii, Niemczech i Danii.',
    history: 'Dwa razy dziennie w czasie odpływu (Ebbe) morze się cofa, a podczas przypływu (Flut) wraca. Obszar chronią parki narodowe.',
    why: 'Przyrodnicze dziedzictwo (Weltnaturerbe): unikalny ekosystem, miejsce odpoczynku milionów ptaków wędrownych.',
    deutsch: 'Das Wattenmeer an der Nordsee ist ein Weltnaturerbe. Bei Ebbe zieht sich das Meer zurück, und man kann über den Meeresboden wandern. Hier leben Seehunde und Millionen Zugvögel machen Rast.',
    features: ['Wattwandern z przewodnikiem', 'Foki (Seehunde)', 'Ptaki wędrowne'],
    facts: ['Uwaga: to dziedzictwo PRZYRODNICZE, nie kulturowe', 'Wspólny wpis z Holandią i Danią'],
    vocab: [['das Watt', 'wat'], ['die Ebbe / die Flut', 'odpływ / przypływ'], ['der Seehund', 'foka'], ['der Zugvogel', 'ptak wędrowny']],
    keywords: ['Ebbe und Flut', 'Nordsee', 'Seehunde', 'Wattwandern'],
  },
  {
    id: 'buchenwaelder',
    name: 'Alte Buchenwälder Deutschlands',
    namePl: 'Pradawne lasy bukowe',
    place: 'Jasmund, Serrahn, Grumsin, Hainich, Kellerwald',
    lands: ['DE-MV', 'DE-BB', 'DE-TH', 'DE-HE'],
    lat: 51.08, lon: 10.45,
    year: 2011,
    kind: 'natur',
    nature: true,
    core: true,
    what: 'Pięć obszarów starych lasów bukowych - część transgranicznego wpisu obejmującego wiele krajów Europy.',
    history: 'Po epoce lodowcowej buk rozprzestrzenił się w Europie. Niemieckie lasy dołączyły w 2011 r. do wpisu z Karpat (Słowacja, Ukraina).',
    why: 'Przyrodnicze dziedzictwo: pokazują naturalny rozwój lasów bukowych w Europie.',
    deutsch: 'Die Alten Buchenwälder sind seit 2011 Weltnaturerbe. Dazu gehören zum Beispiel der Nationalpark Jasmund auf Rügen und der Nationalpark Hainich in Thüringen.',
    features: ['Jasmund na Rugii (klify kredowe)', 'Hainich - ścieżka w koronach drzew (Baumkronenpfad)', 'Kellerwald-Edersee'],
    facts: ['Wpis obejmuje lasy w ponad 18 krajach Europy'],
    vocab: [['die Buche', 'buk'], ['der Wald', 'las'], ['der Nationalpark', 'park narodowy']],
    keywords: ['Buchen', 'Hainich', 'Jasmund', 'Wald'],
  },
  {
    id: 'schwerin',
    name: 'Residenzensemble Schwerin',
    namePl: 'Zespół rezydencjonalny w Schwerinie',
    place: 'Schwerin',
    lands: ['DE-MV'],
    lat: 53.624, lon: 11.419,
    year: 2024,
    kind: 'schloss',
    core: true,
    what: 'Bajkowy zamek na wyspie w jeziorze Schwerin z otaczającymi budynkami rezydencji wielkich książąt meklemburskich.',
    history: 'Zamek otrzymał obecny romantyczny wygląd w połowie XIX w. (przebudowa 1845-1857), inspirowany m.in. zamkiem Chambord we Francji. Dziś siedziba parlamentu Meklemburgii-Pomorza Przedniego.',
    why: 'Wybitny przykład historyzmu - rezydencja XIX-wiecznej monarchii.',
    deutsch: 'Das Schweriner Schloss liegt auf einer Insel im Schweriner See. Es erhielt Mitte des 19. Jahrhunderts sein heutiges romantisches Aussehen. Seit 2024 ist das Residenzensemble Welterbe. Heute tagt hier der Landtag.',
    features: ['Zamek na wyspie', 'Ogród zamkowy', 'Teatr i muzeum państwowe'],
    facts: ['Duch zamkowy „Petermännchen”', 'Siedziba Landtagu MV'],
    vocab: [['die Residenz', 'rezydencja'], ['der Landtag', 'parlament kraju związkowego'], ['der Historismus', 'historyzm']],
    keywords: ['Insel im See', 'Landtag', 'Petermännchen', '2024'],
  },
  {
    id: 'herrnhut',
    name: 'Herrnhut (Herrnhuter Siedlungen)',
    namePl: 'Herrnhut - osada Braci Morawskich',
    place: 'Herrnhut (Oberlausitz)',
    lands: ['DE-SN'],
    lat: 51.016, lon: 14.743,
    year: 2024,
    kind: 'altstadt',
    core: true,
    what: 'Osada wspólnoty religijnej Braci Morawskich (Herrnhuter Brüdergemeine) - część transgranicznego wpisu.',
    history: 'Założona w 1722 r. przez protestanckich uchodźców z Moraw na ziemi hrabiego Mikołaja Ludwika von Zinzendorfa. Stąd misjonarze wyruszali na cały świat i zakładali podobne osady.',
    why: 'Wpis transgraniczny (z Christiansfeld w Danii, Bethlehem w USA i Gracehill w Wielkiej Brytanii) - wzorcowe planowanie osad wspólnoty.',
    deutsch: 'Herrnhut in Sachsen wurde 1722 von Glaubensflüchtlingen aus Mähren gegründet. Die Herrnhuter Brüdergemeine ist weltweit bekannt. Typisch sind die Herrnhuter Sterne zur Adventszeit.',
    features: ['Plac centralny i sala zgromadzeń', 'Cmentarz Gottesacker - jednakowe płyty (równość wobec Boga)'],
    facts: ['Gwiazdy herrnhuckie (Herrnhuter Sterne) - ozdoby adwentowe', '„Losungen” - codzienne hasła biblijne wydawane od 1731 r.'],
    vocab: [['der Flüchtling', 'uchodźca'], ['die Gemeinde', 'wspólnota, gmina'], ['der Stern', 'gwiazda']],
    keywords: ['Herrnhuter Sterne', 'Zinzendorf', '1722', 'Brüdergemeine'],
  },
  {
    id: 'ludwig',
    name: 'Die Schlösser König Ludwigs II. von Bayern',
    namePl: 'Zamki króla Ludwika II Bawarskiego',
    place: 'Neuschwanstein, Linderhof, Herrenchiemsee, Schachen',
    lands: ['DE-BY'],
    lat: 47.557, lon: 10.75,
    year: 2025,
    kind: 'schloss',
    core: true,
    what: 'Neuschwanstein, Linderhof, Herrenchiemsee i Domek Królewski na Schachen - „bajkowe zamki” Ludwika II.',
    history: 'Ludwik II (1845-1886), „bajkowy król” (Märchenkönig), budował zamki jako ucieczkę od polityki - inspirowały go operami Richarda Wagnera (Neuschwanstein) i Wersal Ludwika XIV (Herrenchiemsee). Budowę Neuschwanstein rozpoczęto w 1869 r.; zamku nigdy nie ukończono - król mieszkał w nim tylko ok. 172 dni. Zmarł w tajemniczych okolicznościach w jeziorze Starnberger See w 1886 r.',
    why: 'Najnowszy niemiecki wpis (2025): wybitne świadectwa historyzmu i romantycznych ideałów XIX w.',
    deutsch: 'König Ludwig II. von Bayern ließ im 19. Jahrhundert Neuschwanstein, Linderhof und Herrenchiemsee bauen. Neuschwanstein wurde nie fertig. Seit 2025 gehören die Schlösser zum UNESCO-Welterbe.',
    features: ['Neuschwanstein - inspirowany operami Wagnera', 'Linderhof - jedyny ukończony za życia króla, Grota Wenus', 'Herrenchiemsee na wyspie Herreninsel - kopia Galerii Zwierciadlanej z Wersalu', 'Königshaus am Schachen - wnętrze w stylu mauretańskim'],
    facts: ['Neuschwanstein zainspirował zamek Śpiącej Królewny Disneya', 'Ok. 1,4 mln turystów rocznie w Neuschwanstein', 'Zamki otwarto dla zwiedzających kilka tygodni po śmierci króla (1886)'],
    vocab: [['der Märchenkönig', 'bajkowy król'], ['das Märchenschloss', 'bajkowy zamek'], ['der Spiegelsaal', 'sala zwierciadlana'], ['die Grotte', 'grota']],
    keywords: ['Märchenkönig', 'Neuschwanstein', 'Versailles', 'Richard Wagner', '2025'],
  },
  {
    id: 'bamberg',
    name: 'Altstadt von Bamberg',
    namePl: 'Stare miasto w Bambergu',
    place: 'Bamberg',
    lands: ['DE-BY'],
    lat: 49.891, lon: 10.882,
    year: 1993,
    kind: 'altstadt',
    core: true,
    what: 'Średniowieczne i barokowe miasto na siedmiu wzgórzach - „frankoński Rzym”.',
    history: 'Cesarz Henryk II założył tu w 1007 r. biskupstwo. Miasto zachowało średniowieczny układ i ok. 2400 zabytkowych budynków.',
    why: 'Wzorcowy przykład średniowiecznego miasta w Europie Środkowej z wyjątkowo dobrze zachowaną zabudową.',
    deutsch: 'Die Altstadt von Bamberg in Bayern ist seit 1993 Welterbe. Man nennt die Stadt auch „Fränkisches Rom“, weil sie auf sieben Hügeln liegt. Das Alte Rathaus steht mitten im Fluss Regnitz.',
    features: ['Katedra z „Jeźdźcem bamberskim” (Bamberger Reiter)', 'Stary Ratusz na wyspie w rzece Regnitz', 'Nowa Rezydencja (barok)', '„Mała Wenecja”'],
    facts: ['Specjalność: piwo wędzone (Rauchbier)', 'Ok. 2400 zabytkowych budynków'],
    vocab: [['der Hügel', 'wzgórze'], ['das Rathaus', 'ratusz'], ['der Reiter', 'jeździec']],
    keywords: ['Fränkisches Rom', 'Bamberger Reiter', 'Rathaus im Fluss', 'Rauchbier'],
  },
  {
    id: 'wuerzburg',
    name: 'Würzburger Residenz mit Hofgarten',
    namePl: 'Rezydencja w Würzburgu',
    place: 'Würzburg',
    lands: ['DE-BY'],
    lat: 49.793, lon: 9.938,
    year: 1981,
    kind: 'schloss',
    core: true,
    what: 'Barokowy pałac książąt-biskupów z ogrodem dworskim.',
    history: 'Budowany w latach 1720-1744 według projektu Balthasara Neumanna dla książąt-biskupów z rodu Schönborn; wnętrza ukończono ok. 1780 r. Mimo zniszczeń w 1945 r. najważniejsze sale przetrwały.',
    why: 'Jeden z najwspanialszych pałaców barokowych Europy - synteza baroku europejskiego.',
    deutsch: 'Die Würzburger Residenz ist ein barockes Schloss der Fürstbischöfe. Der Architekt war Balthasar Neumann. Über dem Treppenhaus befindet sich eines der größten Deckenfresken der Welt von Giovanni Battista Tiepolo.',
    features: ['Klatka schodowa z ogromnym freskiem Tiepola', 'Sala Cesarska (Kaisersaal)', 'Ogród dworski (Hofgarten)'],
    facts: ['Fresk Tiepola przedstawia cztery kontynenty', 'Klatka schodowa bez podpór przetrwała bombardowanie 1945'],
    vocab: [['der Fürstbischof', 'książę-biskup'], ['das Treppenhaus', 'klatka schodowa'], ['das Fresko', 'fresk'], ['der Barock', 'barok']],
    keywords: ['Balthasar Neumann', 'Tiepolo', 'Fürstbischöfe', 'Treppenhaus'],
  },
  {
    id: 'museumsinsel',
    name: 'Museumsinsel Berlin',
    namePl: 'Wyspa Muzeów w Berlinie',
    place: 'Berlin',
    lands: ['DE-BE'],
    lat: 52.52, lon: 13.398,
    year: 1999,
    kind: 'altstadt',
    core: true,
    what: 'Pięć wielkich muzeów na północnym krańcu wyspy na Sprewie.',
    history: 'Muzea powstawały w latach 1830-1930: Altes Museum (Karl Friedrich Schinkel), Neues Museum, Alte Nationalgalerie, Bode-Museum i Pergamonmuseum.',
    why: 'Wyjątkowy zespół muzealny ilustrujący rozwój muzeów jako instytucji publicznych.',
    deutsch: 'Die Museumsinsel liegt auf einer Insel in der Spree in Berlin. Hier stehen fünf Museen mit Kunst aus 6000 Jahren. Im Neuen Museum kann man die Büste der Nofretete sehen.',
    features: ['Altes Museum', 'Neues Museum - popiersie Nefretete', 'Alte Nationalgalerie', 'Bode-Museum', 'Pergamonmuseum (w długim remoncie)'],
    facts: ['6000 lat historii sztuki', 'Popiersie Nefretete ma ok. 3350 lat'],
    vocab: [['die Insel', 'wyspa'], ['die Büste', 'popiersie'], ['die Ausstellung', 'wystawa'], ['das Kunstwerk', 'dzieło sztuki']],
    keywords: ['fünf Museen', 'Spree', 'Nofretete', 'Pergamon'],
  },
  {
    id: 'trier',
    name: 'Römische Baudenkmäler, Dom und Liebfrauenkirche in Trier',
    namePl: 'Zabytki rzymskie, katedra i kościół Najświętszej Marii Panny w Trewirze',
    place: 'Trier',
    lands: ['DE-RP'],
    lat: 49.759, lon: 6.644,
    year: 1986,
    kind: 'archaeologie',
    core: true,
    what: 'Rzymskie budowle dawnej Augusta Treverorum oraz średniowieczne kościoły.',
    history: 'Rzymianie założyli miasto w 16 r. p.n.e. - uchodzi za najstarsze miasto Niemiec. W IV w. było rezydencją cesarzy rzymskich (m.in. Konstantyna Wielkiego).',
    why: 'Najlepiej zachowane zabytki rzymskie na północ od Alp i świadectwo wczesnego chrześcijaństwa.',
    deutsch: 'Trier in Rheinland-Pfalz wurde 16 v. Chr. von den Römern als Augusta Treverorum gegründet. Die Porta Nigra ist das bekannteste römische Stadttor nördlich der Alpen. Trier gilt als älteste Stadt Deutschlands.',
    features: ['Porta Nigra („Czarna Brama”)', 'Termy Cesarskie', 'Amfiteatr', 'Bazylika Konstantyna', 'Katedra - najstarsza w Niemczech'],
    facts: ['W Trewirze urodził się Karol Marks (1818)', 'Most Rzymski nad Mozelą wciąż jest używany'],
    vocab: [['die Römer', 'Rzymianie'], ['das Stadttor', 'brama miejska'], ['die Therme', 'termy'], ['das Amphitheater', 'amfiteatr']],
    keywords: ['Porta Nigra', 'Römer', 'älteste Stadt Deutschlands', 'Mosel'],
  },
  {
    id: 'bruehl',
    name: 'Schlösser Augustusburg und Falkenlust in Brühl',
    namePl: 'Pałace Augustusburg i Falkenlust w Brühl',
    place: 'Brühl (bei Köln)',
    lands: ['DE-NW'],
    lat: 50.826, lon: 6.905,
    year: 1984,
    kind: 'schloss',
    core: true,
    what: 'Rokokowa rezydencja arcybiskupa-elektora Kolonii i pobliski pałacyk myśliwski.',
    history: 'Budowę zlecił elektor Klemens August w 1725 r. Klatkę schodową zaprojektował Balthasar Neumann. W czasach, gdy stolicą RFN był Bonn, pałac służył do przyjmowania gości państwowych.',
    why: 'Jeden z pierwszych wybitnych przykładów rokoka w Niemczech.',
    deutsch: 'Die Schlösser Augustusburg und Falkenlust in Brühl sind Meisterwerke des Rokoko. Kurfürst Clemens August ließ sie ab 1725 bauen. Falkenlust war ein Jagdschloss für die Falkenjagd.',
    features: ['Klatka schodowa Balthasara Neumanna', 'Ogród francuski', 'Falkenlust - polowania z sokołami'],
    facts: ['Miejsce przyjęć państwowych prezydenta RFN do 1996 r.'],
    vocab: [['das Rokoko', 'rokoko'], ['der Kurfürst', 'elektor'], ['das Jagdschloss', 'pałac myśliwski'], ['der Falke', 'sokół']],
    keywords: ['Rokoko', 'Clemens August', 'Falkenjagd', 'Staatsempfänge'],
  },
  {
    id: 'goslar',
    name: 'Bergwerk Rammelsberg, Altstadt von Goslar und Oberharzer Wasserwirtschaft',
    namePl: 'Kopalnia Rammelsberg, stare miasto Goslar i system wodny Górnego Harzu',
    place: 'Goslar (Harz)',
    lands: ['DE-NI'],
    lat: 51.906, lon: 10.428,
    year: 1992,
    extended: '2010 (Oberharzer Wasserwirtschaft, Kloster Walkenried, Grube Samson)',
    kind: 'industrie',
    core: true,
    what: 'Kopalnia rud metali działająca ponad 1000 lat, cesarskie miasto Goslar i przedindustrialny system gospodarki wodnej.',
    history: 'W Rammelsbergu wydobywano srebro, miedź, ołów i cynk ponad 1000 lat - do 1988 r. Bogactwo kopalni sprawiło, że cesarze zbudowali w Goslarze pałac (Kaiserpfalz, XI w.). System stawów i rowów w Górnym Harzu dostarczał energii wodnej do kopalń.',
    why: 'Świadectwo tysiącletniej historii górnictwa oraz jednego z największych przedindustrialnych systemów zaopatrzenia w energię na świecie.',
    deutsch: 'Im Rammelsberg bei Goslar in Niedersachsen wurde über 1000 Jahre lang Erz abgebaut, bis 1988. Durch den Bergbau wurde Goslar reich und die Kaiser bauten hier eine Pfalz. Seit 2010 gehört auch die Oberharzer Wasserwirtschaft dazu.',
    features: ['Muzeum-kopalnia z jazdą kolejką pod ziemią', 'Kaiserpfalz w Goslarze', 'Stawy i rowy Górnego Harzu (ok. 107 stawów, 310 km rowów)', 'Klasztor Walkenried i kopalnia Samson'],
    facts: ['Wydobycie przez ponad 1000 lat', 'Zamknięcie kopalni: 1988', 'Rozszerzenie wpisu w 2010 r.'],
    vocab: [['das Bergwerk', 'kopalnia'], ['das Erz', 'ruda'], ['abbauen', 'wydobywać'], ['der Teich', 'staw'], ['die Kaiserpfalz', 'palatium cesarskie']],
    keywords: ['Rammelsberg', 'Harz', 'Erz', 'Kaiserpfalz', '1000 Jahre Bergbau'],
  },

  // ===== Pozostałe obiekty (rozszerzenie) =====
  site('wies', 'Wallfahrtskirche „Die Wies“', 'Kościół pielgrzymkowy Wies', 'Steingaden', ['DE-BY'], 47.681, 10.899, 1983, 'kirche',
    'Rokokowy kościół pielgrzymkowy braci Zimmermann (1745-1754) na łące u podnóża Alp - arcydzieło rokoka.', ['Rokoko', 'Zimmermann', 'Wallfahrt']),
  site('hildesheim', 'Dom St. Marien und Michaeliskirche in Hildesheim', 'Katedra i kościół św. Michała w Hildesheim', 'Hildesheim', ['DE-NI'], 52.149, 9.947, 1985, 'kirche',
    'Arcydzieła sztuki ottońskiej; przy katedrze rośnie „tysiącletni krzew róży”, który przetrwał bombardowanie 1945.', ['tausendjähriger Rosenstock', 'Romanik']),
  site('lorsch', 'Kloster Lorsch mit Altenmünster', 'Klasztor Lorsch', 'Lorsch', ['DE-HE'], 49.654, 8.568, 1991, 'kloster',
    'Karolińska brama-hala królewska (Königshalle) - jedna z najstarszych zachowanych budowli w Niemczech.', ['Königshalle', 'Karolinger']),
  site('quedlinburg', 'Stiftskirche, Schloss und Altstadt Quedlinburg', 'Quedlinburg', 'Quedlinburg', ['DE-ST'], 51.789, 11.141, 1994, 'altstadt',
    'Miasto z ponad 1300 domami o konstrukcji szachulcowej (Fachwerk) z sześciu stuleci.', ['Fachwerkhäuser', 'Harz']),
  site('messel', 'Grube Messel', 'Kopalnia Messel', 'Messel bei Darmstadt', ['DE-HE'], 49.917, 8.756, 1994, 'natur',
    'Stanowisko skamieniałości sprzed ok. 48 mln lat - m.in. praprzodek konia (Urpferdchen) z zawartością żołądka.', ['Fossilien', 'Urpferdchen'], true),
  site('weimar', 'Klassisches Weimar', 'Klasyczny Weimar', 'Weimar', ['DE-TH'], 50.979, 11.329, 1998, 'altstadt',
    'Miejsca związane z Goethem, Schillerem i niemiecką klasyką (dom Goethego, dom Schillera, biblioteka księżnej Anny Amalii).', ['Goethe', 'Schiller', 'Klassik']),
  site('woerlitz', 'Gartenreich Dessau-Wörlitz', 'Królestwo ogrodów Dessau-Wörlitz', 'Dessau-Wörlitz', ['DE-ST'], 51.842, 12.42, 2000, 'garten',
    'Pierwszy duży park w stylu angielskim w Europie kontynentalnej (XVIII w.) - wzorzec epoki oświecenia.', ['Landschaftspark', 'Aufklärung']),
  site('reichenau', 'Klosterinsel Reichenau', 'Klasztorna wyspa Reichenau', 'Bodensee', ['DE-BW'], 47.695, 9.063, 2000, 'kloster',
    'Wyspa na Jeziorze Bodeńskim z trzema romańskimi kościołami - centrum kultury i malarstwa książkowego we wczesnym średniowieczu.', ['Bodensee', 'Buchmalerei']),
  site('bremen', 'Rathaus und Roland auf dem Marktplatz von Bremen', 'Ratusz i posąg Rolanda w Bremie', 'Bremen', ['DE-HB'], 53.076, 8.807, 2004, 'altstadt',
    'Gotycko-renesansowy ratusz i posąg Rolanda z 1404 r. - symbol praw i wolności miejskich.', ['Roland', '1404', 'Freiheit']),
  site('muskau', 'Muskauer Park / Park Mużakowski', 'Park Mużakowski', 'Bad Muskau', ['DE-SN'], 51.548, 14.72, 2004, 'garten',
    'Park krajobrazowy księcia Hermanna von Pückler-Muskau po obu stronach Nysy Łużyckiej - wspólny obiekt Niemiec i POLSKI.', ['Pückler', 'Neiße', 'Polen']),
  site('limes', 'Grenzen des Römischen Reiches: Obergermanisch-Raetischer Limes', 'Limes górnogermańsko-retycki', 'Rheinland-Pfalz bis Bayern', ['DE-RP', 'DE-HE', 'DE-BW', 'DE-BY'], 49.3, 9.6, 2005, 'archaeologie',
    'Ok. 550 km rzymskiej granicy (wały, palisady, wieże) - część wpisu „Granice Imperium Rzymskiego” (z Murem Hadriana).', ['Römer', 'Grenze', 'Hadrianswall']),
  site('fagus', 'Fagus-Werk in Alfeld', 'Fabryka Fagus', 'Alfeld', ['DE-NI'], 51.984, 9.811, 2011, 'moderne',
    'Fabryka kopyt szewskich Waltera Gropiusa (od 1911) - prekursor nowoczesnej architektury ze szklanymi ścianami.', ['Gropius', 'Glasfassade']),
  site('bayreuth', 'Markgräfliches Opernhaus Bayreuth', 'Opera margrabiów w Bayreuth', 'Bayreuth', ['DE-BY'], 49.944, 11.578, 2012, 'schloss',
    'Barokowy teatr operowy (1745-1750) z oryginalnym drewnianym wnętrzem - zamówiony przez margrabinę Wilhelminę.', ['Barock', 'Oper', 'Wilhelmine']),
  site('kassel', 'Bergpark Wilhelmshöhe', 'Park górski Wilhelmshöhe', 'Kassel', ['DE-HE'], 51.316, 9.393, 2013, 'garten',
    'Barokowy park z posągiem Herkulesa i kaskadami wodnymi działającymi bez pomp - największy park górski Europy.', ['Herkules', 'Wasserspiele']),
  site('corvey', 'Karolingisches Westwerk und Civitas Corvey', 'Opactwo Corvey', 'Höxter', ['DE-NW'], 51.778, 9.41, 2014, 'kloster',
    'Karoliński westwerk z IX w. - jedna z niewielu zachowanych budowli tej epoki.', ['Westwerk', 'Karolinger']),
  site('alb', 'Höhlen und Eiszeitkunst der Schwäbischen Alb', 'Jaskinie i sztuka epoki lodowcowej Jury Szwabskiej', 'Schwäbische Alb', ['DE-BW'], 48.55, 9.9, 2017, 'archaeologie',
    'Jaskinie, w których znaleziono najstarsze figurki i instrumenty muzyczne świata (ok. 40 000 lat) - m.in. Wenus z Hohle Fels.', ['Venus vom Hohle Fels', 'Flöten', 'Eiszeit']),
  site('naumburg', 'Naumburger Dom', 'Katedra w Naumburgu', 'Naumburg', ['DE-ST'], 51.155, 11.804, 2018, 'kirche',
    'Katedra z rzeźbami Mistrza Naumburskiego - m.in. słynna Uta z Naumburga (XIII w.).', ['Uta von Naumburg', 'Naumburger Meister']),
  site('haithabu', 'Archäologischer Grenzkomplex Haithabu und Danewerk', 'Hedeby i Danewerk', 'Schleswig', ['DE-SH'], 54.49, 9.565, 2018, 'archaeologie',
    'Wikińska osada handlowa Haithabu i system wałów granicznych Danewerk.', ['Wikinger', 'Handel']),
  site('erzgebirge', 'Montanregion Erzgebirge/Krušnohoří', 'Region górniczy Rudawy', 'Erzgebirge', ['DE-SN'], 50.6, 13.1, 2019, 'industrie',
    'Wspólny obiekt z Czechami - 800 lat górnictwa srebra, cyny i innych rud.', ['Bergbau', 'Silber', 'Tschechien']),
  site('augsburg', 'Wassermanagement-System Augsburg', 'System gospodarki wodnej w Augsburgu', 'Augsburg', ['DE-BY'], 48.366, 10.894, 2019, 'industrie',
    'Kanały, wieże ciśnień, fontanny i elektrownie wodne rozwijane od średniowiecza.', ['Kanäle', 'Brunnen', 'Wasser']),
  site('baeder', 'Bedeutende Kurstädte Europas: Baden-Baden, Bad Ems, Bad Kissingen', 'Wielkie uzdrowiska Europy', 'Baden-Baden, Bad Ems, Bad Kissingen', ['DE-BW', 'DE-RP', 'DE-BY'], 48.761, 8.24, 2021, 'altstadt',
    'Trzy niemieckie uzdrowiska w transgranicznym wpisie 11 miast (7 krajów) - kultura kuracji XIX w.', ['Kurort', 'Heilquellen']),
  site('mathildenhoehe', 'Mathildenhöhe Darmstadt', 'Mathildenhöhe w Darmstadt', 'Darmstadt', ['DE-HE'], 49.876, 8.667, 2021, 'moderne',
    'Kolonia artystów secesji (Jugendstil) z Wieżą Weselną (Hochzeitsturm).', ['Jugendstil', 'Hochzeitsturm']),
  site('schum', 'SchUM-Stätten Speyer, Worms und Mainz', 'Miejsca SchUM', 'Speyer, Worms, Mainz', ['DE-RP'], 49.632, 8.36, 2021, 'altstadt',
    'Średniowieczne dziedzictwo żydowskie trzech gmin nad Renem (synagogi, mykwy, cmentarze).', ['jüdisches Erbe', 'Synagoge']),
  site('donaulimes', 'Grenzen des Römischen Reiches: Donaulimes (westlicher Abschnitt)', 'Limes naddunajski', 'Bayern (z Austrią i Słowacją)', ['DE-BY'], 48.9, 12.2, 2021, 'archaeologie',
    'Rzymska granica na Dunaju - wspólny wpis Niemiec, Austrii i Słowacji.', ['Römer', 'Donau']),
  site('niedergermanisch', 'Grenzen des Römischen Reiches: Niedergermanischer Limes', 'Limes dolnogermański', 'Rhein (NRW, RP)', ['DE-NW', 'DE-RP'], 51.3, 6.6, 2021, 'archaeologie',
    'Rzymska granica wzdłuż Renu - wspólny wpis z Holandią.', ['Römer', 'Rhein']),
  site('erfurt', 'Jüdisch-mittelalterliches Erbe in Erfurt', 'Średniowieczne dziedzictwo żydowskie w Erfurcie', 'Erfurt', ['DE-TH'], 50.978, 11.03, 2023, 'altstadt',
    'Stara Synagoga (jedna z najstarszych zachowanych w Europie), mykwa i Dom Kamienny.', ['Alte Synagoge', 'Mikwe']),
  site('pfahlbauten', 'Prähistorische Pfahlbauten um die Alpen', 'Prehistoryczne osady palowe wokół Alp', 'Bodensee, Federsee u.a.', ['DE-BW', 'DE-BY'], 47.72, 9.27, 2011, 'archaeologie',
    'Pozostałości osad na palach z epoki kamienia i brązu - wpis z 5 innymi krajami alpejskimi.', ['Pfahlbauten', 'Steinzeit']),
]

function site(
  id: string, name: string, namePl: string, place: string, lands: string[], lat: number, lon: number, year: number,
  kind: SiteKind, what: string, keywords: string[], nature = false,
): UnescoSite {
  return {
    id, name, namePl, place, lands, lat, lon, year, kind, nature, core: false,
    what, history: '', why: '', deutsch: '', features: [], facts: [], vocab: [], keywords,
  }
}

export const UNESCO_BY_ID: Record<string, UnescoSite> = Object.fromEntries(UNESCO_SITES.map((s) => [s.id, s]))

export const UNESCO_BASICS = {
  facts: [
    'UNESCO = Organizacja Narodów Zjednoczonych do spraw Oświaty, Nauki i Kultury; założona w 1945 r., siedziba w Paryżu.',
    'Konwencja o ochronie światowego dziedzictwa - 1972 r. Warunek wpisu: „wyjątkowa uniwersalna wartość” (außergewöhnlicher universeller Wert).',
    'Niemcy mają 55 obiektów na liście (stan 2025) - jedną z największych liczb na świecie.',
    'Pierwszy niemiecki obiekt: Katedra w Akwizgranie (1978). Najnowszy: zamki Ludwika II (2025).',
    'Dolina Łaby w Dreźnie straciła status w 2009 r. z powodu budowy mostu Waldschlößchenbrücke - jeden z nielicznych takich przypadków na świecie.',
    'Czerwona Lista (Rote Liste) = lista dziedzictwa zagrożonego. Katedra w Kolonii była na niej w latach 2004-2006.',
    'Kraje związkowe zgłaszają kandydatów → KMK tworzy wspólną listę wstępną (Tentativliste) → Komitet Światowego Dziedzictwa decyduje.',
    'Rozróżniamy: Weltkulturerbe (dziedzictwo kulturowe), Weltnaturerbe (przyrodnicze, np. Morze Wattowe, lasy bukowe, Messel).',
  ],
  vocab: [
    ['das Welterbe / das Weltkulturerbe', 'światowe dziedzictwo (kulturowe)'],
    ['das Weltnaturerbe', 'światowe dziedzictwo przyrodnicze'],
    ['die Welterbestätte', 'obiekt światowego dziedzictwa'],
    ['in die Welterbeliste aufnehmen', 'wpisać na listę'],
    ['auf der Roten Liste stehen', 'być na liście zagrożonych'],
    ['den Welterbetitel verlieren / aberkennen', 'stracić / odebrać tytuł'],
    ['das Denkmal, die Denkmäler', 'zabytek, pomnik'],
    ['die Sehenswürdigkeit', 'atrakcja turystyczna'],
    ['das Wahrzeichen', 'symbol (miasta)'],
    ['das Bauwerk', 'budowla'],
    ['der Baumeister / der Architekt', 'budowniczy / architekt'],
    ['erbauen / errichten', 'zbudować / wznieść'],
    ['die Burg / das Schloss', 'zamek obronny / pałac, zamek rezydencjonalny'],
    ['der Dom / die Kathedrale', 'katedra'],
    ['das Kloster', 'klasztor'],
    ['die Altstadt', 'stare miasto'],
    ['das Fachwerkhaus', 'dom szachulcowy'],
    ['die Romanik / die Gotik / der Barock / das Rokoko / der Jugendstil', 'romanizm / gotyk / barok / rokoko / secesja'],
    ['die Zeche / das Bergwerk', 'kopalnia'],
    ['die Führung', 'oprowadzanie z przewodnikiem'],
    ['besichtigen', 'zwiedzać'],
    ['die Aussichtsplattform', 'platforma widokowa'],
    ['der Eintritt / die Eintrittskarte', 'wstęp / bilet wstępu'],
  ] as [string, string][],
}
